[package]
name = "models"
version = "0.0.0"
publish = false

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
test-utils = []

[dependencies]
auth = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
derive_more = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
humantime = { workspace = true }
infer = "0.19.0"
iso8601 = { workspace = true }
lru = { workspace = true }
paste = "1.0.15"
recipe-schema = { workspace = true }
recipya-scraper = { workspace = true }
repository = { workspace = true }
serde = { workspace = true }
support = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
whatlang = "0.16.4"

[dev-dependencies]
app = { workspace = true }
pretty_assertions = { workspace = true }
testing = { path = "../testing", features = ["test-utils"] }
