[package]
name = "recipya-cli"
version.workspace = true
publish = true

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
app.workspace = true
auth.workspace = true
axum.workspace = true
clap = { version = "4.6.0", features = ["derive"] }
config.workspace = true
derive_more.workspace = true
diesel.workspace = true
dotenvy.workspace = true
models.workspace = true
rand.workspace = true
recipya-scraper.workspace = true
repository.workspace = true
router.workspace = true
rustls.workspace = true
support.workspace = true
tokio.workspace = true
tokio-cron-scheduler = "0.15.1"
tower-cookies.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[target.'aarch64-unknown-linux-gnu'.dependencies]
openssl = { version = "0.10.79", features = ["vendored"] }
pq-sys = { version = "0.7.5", features = ["bundled"] }

[target.'x86_64-unknown-linux-gnu'.dependencies]
openssl = { version = "0.10.79", features = ["vendored"] }
pq-sys = { version = "0.7.5", features = ["bundled"] }

[target.'x86_64-unknown-linux-musl'.dependencies]
openssl = { version = "0.10.79", features = ["vendored"] }
pq-sys = { version = "0.7.5", features = ["bundled"] }
