[package]
name = "email"
version = "0.0.0"
publish = false

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
derive_more.workspace = true
lettre = { version = "0.11.20", default-features = false, features = ["smtp-transport", "pool", "rustls-tls", "hostname", "builder"] }
mrml = "5.1.0"
support.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
temp-env = "0.3.6"
