[package]
name = "router"
version = "0.0.0"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
app.workspace = true
axum-extra = { version = "0.12.5", features = ["cookie"] }
auth.workspace = true
axum.workspace = true
axum-htmx = "0.8.1"
chrono.workspace = true
config.workspace = true
derive_more.workspace = true
email.workspace = true
futures.workspace = true
futures-util.workspace = true
humantime.workspace = true
indexmap.workspace = true
infer.workspace = true
integrations.workspace = true
iso8601.workspace = true
itertools.workspace = true
math.workspace = true
mime_guess = "2.0.5"
models = { workspace = true }
rand.workspace = true
recipya-scraper.workspace = true
repository.workspace = true
reqwest.workspace = true
rust-embed = { version = "8.11.0", features = ["axum-ex"] }
schema-org = { path = "../schema-org", features = ["json-schema"] }
serde.workspace = true
serde_json.workspace = true
serde_qs = "1.1.1"
strum_macros.workspace = true
support.workspace = true
templates.workspace = true
tokio.workspace = true
tokio-util = "0.7.18"
tower-cookies.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
validator.workspace = true
axum-test = { workspace = true }

[dev-dependencies]
auth = { workspace = true, features = ["test-helpers"] }
axum-test.workspace = true
diesel.workspace = true
diesel-async.workspace = true
image = "0.25.10"
jsonwebtoken.workspace = true
pretty_assertions.workspace = true
test-utils.workspace = true
time.workspace = true
tokio.workspace = true
tower = "0.5.3"
tracing-test.workspace = true
test-db = { path = "../test-db" }
test-fixtures = { path = "../test-fixtures" }
test-models = { path = "../test-models" }
