[workspace]
members = [
    "crates/app",
    "crates/auth",
    "crates/config",
    "crates/email",
    "crates/integrations",
    "crates/math",
    "crates/models",
    "crates/recipya-cli",
    "crates/recipya-scraper",
    "crates/repository",
    "crates/router",
    "crates/schema-org",
    "crates/support",
    "crates/templates",
    "crates/testing",
]
resolver = "3"

[workspace.package]
authors = ["reaper47"]
categories = ["web-programming"]
description = "A clean, simple and powerful recipe manager your whole family will enjoy."
edition = "2024"
homepage = "https://recipya.musicavis.ca"
keywords = ["food", "recipes", "recipe-manager"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/reaper47/recipya-rs"
rust-version = "1.90.0"

[workspace.dependencies]
app = { path = "./crates/app" }
async-stream = "0.3.6"
async-trait = "0.1.89"
auth = { path = "./crates/auth" }
axum = { version = "0.8.6", features = ["multipart", "ws"] }
axum-test = { version = "18.1.0", features = ["ws"] }
base64 = "0.22.1"
chrono = "0.4.42"
config = { path = "./crates/config" }
derive_more = { version = "2.0.1", features = ["from", "display"] }
diesel = { version = "2.3.2", features = ["postgres", "chrono", "serde_json", "uuid"] }
diesel-async = { version = "0.7.3", features = ["postgres", "bb8", "async-connection-wrapper"] }
diesel_full_text_search = "2.3.0"
email = { path = "./crates/email" }
futures-core = "0.3.31"
futures-util = "0.3.31"
humantime = "2.3.0"
infer = "0.19.0"
integrations = { path = "./crates/integrations" }
iso8601 = { version = "0.6.3", features = ["serde"] }
itertools = "0.14.0"
lru = "0.16.2"
math = { path = "./crates/math" }
models = { path = "./crates/models" }
nom = "8.0.0"
pretty_assertions = "1.4.1"
recipya-scraper = { path = "crates/recipya-scraper" }
regex = "1.12.2"
repository = { path = "./crates/repository" }
reqwest = { version = "0.12.24", default-features = false, features = ["blocking", "charset", "http2", "macos-system-configuration", "rustls-tls"] }
router = { path = "./crates/router" }
rustls = { version = "0.23.32", default-features = false, features = ["ring"] }
schema-org = { path = "./crates/schema-org", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
strum = { version = "0.27.2", features = ["derive"] }
strum_macros = "0.27.2"
support = { path = "./crates/support" }
templates = { path = "./crates/templates" }
time = "0.3.44"
tokio = { version = "1.48.0", features = ["full"] }
tower-cookies = "0.11.0"
tower-http = { version = "0.6.6", features = ["fs"] }
tracing = "0.1.41"
url = { version = "2.5.7", features = ["serde"] }
uuid = { version = "1.18.1", features = ["fast-rng", "serde", "v4"] }
validator = { version = "0.20.0", features = ["derive"] }
whatlang = "0.16.4"

[workspace.metadata.tasks]
web-install-deps = "npm --prefix ./web/app install"
web-build = "npm --prefix ./web/app run build"

[profile.release]
lto = true
codegen-units = 1
