[package]
name = "recipya"
version = "0.1.0"
edition = "2021"
description = "A clean, simple and powerful recipe manager your whole family will enjoy."
readme = "README.md"
homepage = "https://recipes.musicavis.ca"
repository = "https://github.com/reaper47/recipya"
license = "AGPL-3.0-or-later"
keywords = ["food", "recipes", "recipe-manager"]
categories = ["web-programming"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
axum = {  version = "0.7.5" }
clap = { version = "4.5.9", features = ["derive"] }
dirs = "5.0.1"
reqwest = "0.12.5" 
serde = {  version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
spinach = "2.1.0"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "signal"] }
zip = "2.1.3"
