[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["reaper47"]
categories = ["web-programming"]
description = "A clean, simple and powerful recipe manager your whole family will enjoy."
edition = "2024"
homepage = "https://recipya.musicavis.ca"
keywords = ["food", "recipes", "recipe-manager"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/reaper47/recipya-rs"
rust-version = "1.88.0"

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]
# local crates
app = { path = "./crates/app" }
auth = { path = "./crates/auth" }
config = { path = "./crates/config" }
email = { path = "./crates/email" }
integrations = { path = "./crates/integrations" }
math = { path = "./crates/math" }
models = { path = "./crates/models" }
recipe-schema = { path = "crates/recipe-schema" }
recipya-scraper = { path = "crates/recipya-scraper" }
repository = { path = "./crates/repository" }
router = { path = "./crates/router" }
support = { path = "./crates/support" }
templates = { path = "./crates/templates" }

# in-tree crates that are published separately and follow semver.

# non-local crates
async-trait = "0.1.88"
axum = { version = "0.8.4", features = ["multipart", "ws"] }
axum-test = { version = "17.2.0", features = ["ws"] }
base64 = "0.22.1"
chrono = "0.4.41"
derive_more = { version = "2.0.1", features = ["from", "display"] }
diesel = { version = "2.2.11", features = ["postgres", "chrono", "serde_json", "uuid"] }
diesel-async = { version = "0.5.2", features = ["postgres", "bb8", "async-connection-wrapper"] }
futures-util = "0.3.31"
humantime = "2.2.0"
iso8601 = { version = "0.6.3", features = ["serde"] }
lru = "0.15.0"
nom = "8.0.0"
pretty_assertions = "1.4.1"
reqwest = { version = "0.12.20", default-features = false, features = ["blocking", "charset", "http2", "macos-system-configuration", "rustls-tls"] }
rustls = { version = "0.23.28", default-features = false, features = ["ring"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum_macros = "0.27.1"
time = "0.3.41"
tokio = { version = "1.45.1", features = ["full"] }
tower-cookies = "0.11.0"
tower-http = { version = "0.6.6", features = ["fs"] }
tracing = "0.1.41"
url = { version = "2.5.4", features = ["serde"] }
uuid = { version = "1.17.0", features = ["fast-rng", "serde", "v4"] }
validator = { version = "0.20.0", features = ["derive"] }

[workspace.metadata.tasks]
web-install-deps = "npm --prefix ./web/app install"
web-build = "npm --prefix ./web/app run build"
