version: '3'
tasks:
  build-docs:
    cmd: hugo -s ./web/docs --gc --minify

  build-web:
    cmds:
      - cmd: npm --prefix ./web/app install ./web/app
      - cmd: npm --prefix ./web/app run build

  new-migration:
    requires:
      vars: [ name ]
    cmd: diesel migration generate {{.name}}

  release:
    deps:
      - test
    requires:
      vars: [ tag ]
    cmds:
      - go run ./releases/main.go -package github.com/reaper47/recipya -tag {{.tag}}
      - gh release create {{.tag}} ./releases/{{.tag}}/*

  sponsors:
    cmds:
      - cmd: cd ./web/sponsors && npm i && npx sponsorkit -o ../static/img/
