CREATE FUNCTION get_tsv_config (lang char(3)) RETURNS regconfig AS $$
BEGIN
    RETURN CASE lang
    WHEN 'ara' THEN
        'arabic'
    WHEN 'cat' THEN
        'catalan'
    WHEN 'dan' THEN
        'danish'
    WHEN 'deu' THEN
        'german'
    WHEN 'eng' THEN
        'english'
    WHEN 'ell' THEN
        'greek'
    WHEN 'fin' THEN
        'finnish'
    WHEN 'fra' THEN
        'french'
    WHEN 'hin' THEN
        'hindi'
    WHEN 'hun' THEN
        'hungarian'
    WHEN 'hye' THEN
        'armenian'
    WHEN 'ind' THEN
        'indonesian'
    WHEN 'ita' THEN
        'italian'
    WHEN 'lit' THEN
        'lithuanian'
    WHEN 'nep' THEN
        'nepali'
    WHEN 'nld' THEN
        'dutch'
    WHEN 'por' THEN
        'portuguese'
    WHEN 'ron' THEN
        'romanian'
    WHEN 'rus' THEN
        'russian'
    WHEN 'spa' THEN
        'spanish'
    WHEN 'srp' THEN
        'serbian'
    WHEN 'swe' THEN
        'swedish'
    WHEN 'tam' THEN
        'tamil'
    WHEN 'tur' THEN
        'turkish'
    WHEN 'yid' THEN
        'yiddish'
    ELSE
        'simple'
    END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

---
--- Main tables
---
CREATE TABLE measurement_systems (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  image uuid,
  yield int2 NOT NULL DEFAULT 1,
  language char(3) NOT NULL,
  measurement_system_id int2 NOT NULL REFERENCES measurement_systems (id) ON DELETE CASCADE DEFAULT 2,
  notes text,
  source text NOT NULL DEFAULT '',
  is_favourite bool NOT NULL DEFAULT FALSE,
  rating int2 CHECK (rating BETWEEN 1 AND 5),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  fts_combined tsvector NOT NULL GENERATED ALWAYS AS (
    setweight(
      to_tsvector(get_tsv_config (LANGUAGE), coalesce(name, '')),
      'A'
    ) || setweight(
      to_tsvector(get_tsv_config (LANGUAGE), coalesce(source, '')),
      'B'
    ) || setweight(
      to_tsvector(
        get_tsv_config (LANGUAGE),
        coalesce(description, '')
      ),
      'C'
    )
  ) STORED,
  fts_category tsvector NOT NULL DEFAULT ''::tsvector,
  fts_cuisine tsvector NOT NULL DEFAULT ''::tsvector,
  fts_ingredients tsvector NOT NULL DEFAULT ''::tsvector,
  fts_instructions tsvector NOT NULL DEFAULT ''::tsvector,
  fts_keywords tsvector NOT NULL DEFAULT ''::tsvector,
  fts_name tsvector NOT NULL GENERATED ALWAYS AS (
    to_tsvector(get_tsv_config (LANGUAGE), coalesce(name, ''))
  ) STORED,
  fts_tools tsvector NOT NULL DEFAULT ''::tsvector,
  UNIQUE (name, source, yield, user_id)
);

CREATE TABLE categories (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE cuisines (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE ingredients (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE instructions (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  duration_seconds integer
);

CREATE TABLE keywords (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE nutrition_per_100g (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  nutrition_id int8 NOT NULL REFERENCES nutrition (id) ON DELETE CASCADE
);

CREATE TABLE nutrition_per_serving (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  nutrition_id int8 NOT NULL REFERENCES nutrition (id) ON DELETE CASCADE,
  serving_size text NOT NULL
);

CREATE TABLE additional_images_recipe (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  image uuid NOT NULL,
  UNIQUE (recipe_id, image)
);

CREATE TABLE times (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  prep_seconds integer NOT NULL DEFAULT 0,
  cook_seconds integer NOT NULL DEFAULT 0,
  total_seconds integer NOT NULL GENERATED ALWAYS AS (prep_seconds + cook_seconds) STORED
);

CREATE TABLE tools (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE sections (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE user_settings (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  measurement_system_id int2 NOT NULL REFERENCES measurement_systems (id) ON DELETE CASCADE DEFAULT 1,
  nutrition_source_id int2 NOT NULL REFERENCES nutrition_sources (id) ON DELETE CASCADE DEFAULT 1,
  convert_automatically bool NOT NULL DEFAULT FALSE,
  cookbooks_view int NOT NULL DEFAULT 0,
  default_theme int NOT NULL DEFAULT 2,
  selected_theme int NOT NULL REFERENCES themes (id) ON DELETE SET DEFAULT DEFAULT 1
);

---
--- Association tables
---
CREATE TABLE categories_recipes (
  category_id int8 DEFAULT 1 REFERENCES categories (id) ON DELETE SET DEFAULT,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (category_id, recipe_id)
);

CREATE TABLE cuisines_recipes (
  cuisine_id int8 DEFAULT 1 REFERENCES cuisines (id) ON DELETE SET DEFAULT,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (cuisine_id, recipe_id)
);

CREATE TABLE ingredients_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id int8 NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  section_id int8 NOT NULL DEFAULT 1 REFERENCES sections (id) ON DELETE SET DEFAULT,
  item_order int2 NOT NULL
);

CREATE TABLE instructions_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instruction_id int8 NOT NULL REFERENCES instructions (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  section_id int8 NOT NULL DEFAULT 1 REFERENCES sections (id) ON DELETE SET DEFAULT,
  item_order int2 NOT NULL
);

CREATE TABLE keywords_recipes (
  keyword_id int8 NOT NULL REFERENCES keywords (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (keyword_id, recipe_id)
);

CREATE TABLE recipe_timelines (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title text NOT NULL,
  comment text,
  rating int2 CHECK (rating BETWEEN 1 AND 5),
  image uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shares_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP + interval '7 days'),
  last_accessed timestamptz NOT NULL DEFAULT now(),
  click_count int NOT NULL DEFAULT 0,
  UNIQUE (user_id, recipe_id)
);

CREATE TABLE tools_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id int8 NOT NULL REFERENCES tools (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  quantity int2 NOT NULL DEFAULT 1,
  tool_order int2 NOT NULL,
  UNIQUE (recipe_id, tool_id)
);

CREATE TABLE users_categories (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_id int8 NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, category_id)
);

CREATE TABLE users_keywords (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  keyword_id int8 NOT NULL REFERENCES keywords (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, keyword_id)
);

CREATE TABLE users_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  UNIQUE (user_id, recipe_id)
);

CREATE TABLE videos_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video uuid NOT NULL,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  duration interval,
  content_url text,
  embed_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (video, content_url, embed_url, recipe_id)
);

---
--- Indexes
---
CREATE INDEX idx_recipes_user_id ON recipes (user_id);

CREATE INDEX idx_recipes_fts_combined ON recipes USING gin (fts_combined);

CREATE INDEX idx_recipes_fts_category ON recipes USING gin (fts_category);

CREATE INDEX idx_recipes_fts_cuisine ON recipes USING gin (fts_cuisine);

CREATE INDEX idx_recipes_fts_ingredients ON recipes USING gin (fts_ingredients);

CREATE INDEX idx_recipes_fts_instructions ON recipes USING gin (fts_instructions);

CREATE INDEX idx_recipes_fts_keywords ON recipes USING gin (fts_keywords);

CREATE INDEX idx_recipes_fts_name ON recipes USING gin (fts_name);

CREATE INDEX idx_recipes_fts_tools ON recipes USING gin (fts_tools);

CREATE INDEX idx_recipes_name_trgm ON recipes USING gin (name gin_trgm_ops);

CREATE INDEX idx_recipes_source_trgm ON recipes USING gin (source gin_trgm_ops);

CREATE INDEX idx_categories_name_trgm ON categories USING gin (name gin_trgm_ops);

CREATE INDEX idx_cuisines_name_trgm ON cuisines USING gin (name gin_trgm_ops);

CREATE INDEX idx_keywords_name_trgm ON keywords USING gin (name gin_trgm_ops);

CREATE INDEX idx_categories_recipes_recipe_id ON categories_recipes (recipe_id);

CREATE INDEX idx_cuisines_recipes_recipe_id ON cuisines_recipes (recipe_id);

CREATE INDEX idx_ingredients_recipes_recipe_id ON ingredients_recipes (recipe_id);

CREATE INDEX idx_instructions_recipes_recipe_id ON instructions_recipes (recipe_id);

CREATE INDEX idx_keywords_recipes_recipe_id ON keywords_recipes (recipe_id);

CREATE INDEX idx_tools_recipes_recipe_id ON tools_recipes (recipe_id);

CREATE INDEX idx_times_recipe_id ON times (recipe_id);

CREATE INDEX idx_users_recipes_user_id ON users_recipes (user_id);

CREATE INDEX idx_users_recipes_recipe_id ON users_recipes (recipe_id);

CREATE INDEX idx_recipes_user_favourite ON recipes (user_id, is_favourite)
WHERE
  is_favourite = true;

CREATE INDEX idx_recipes_user_rating ON recipes (user_id, rating)
WHERE
  rating IS NOT NULL;

---
--- Function
---
CREATE FUNCTION init_user_data_columns () RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO counts (user_id)
        VALUES (NEW.id);
    INSERT INTO users_categories (user_id, category_id)
    SELECT
        NEW.id,
        id
    FROM
        categories
    WHERE
        name IN ('uncategorized', 'appetizers', 'bread', 'breakfasts', 'condiments', 'dessert', 'lunch', 'main dish', 'salad', 'side dish', 'snacks', 'soups', 'stews');
    INSERT INTO user_settings (user_id)
        VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION update_recipe_count () RETURNS TRIGGER AS $$
BEGIN
    UPDATE
        counts
    SET
        recipes = recipes + 1
    WHERE
        user_id = NEW.user_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION decrement_recipe_count () RETURNS TRIGGER AS $$
BEGIN
    UPDATE
        counts
    SET
        recipes = recipes - 1
    WHERE
        user_id = OLD.user_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_category_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_category = COALESCE(
        (SELECT to_tsvector(get_tsv_config (
        LANGUAGE), string_agg(name, ' '))
         FROM categories c
         JOIN categories_recipes cr ON cr.category_id = c.id
         WHERE cr.recipe_id = recipe_id_to_update),
        ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_cuisine_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_cuisine = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(name, ' ' ORDER BY name))
            FROM cuisines c
                    JOIN cuisines_recipes cr ON cr.cuisine_id = c.id
            WHERE cr.recipe_id = recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_ingredients_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_ingredients = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(i.name, ' '))
            FROM ingredients i
                    JOIN ingredients_recipes ir ON ir.ingredient_id = i.id
            WHERE ir.recipe_id = recipe_id_to_update
            GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_instructions_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_instructions = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(i.name, ' '))
            FROM instructions i
                    JOIN instructions_recipes ir ON ir.instruction_id = i.id
            WHERE ir.recipe_id = recipe_id_to_update
            GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_keywords_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_keywords = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(k.name, ' '))
            FROM keywords k
                    JOIN keywords_recipes kr ON kr.keyword_id = k.id
            WHERE kr.recipe_id = recipe_id_to_update
            GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_tools_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_tools = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(t.name, ' '))
             FROM tools t
                      JOIN tools_recipes tr ON tr.tool_id = t.id
             WHERE tr.recipe_id = recipe_id_to_update
             GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION delete_orphaned_nutrition () RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM nutrition
    WHERE id = OLD.nutrition_id
        AND NOT EXISTS (
            SELECT
                1
            FROM
                nutrition_per_100g
            WHERE
                nutrition_id = OLD.nutrition_id)
        AND NOT EXISTS (
            SELECT
                1
            FROM
                nutrition_per_serving
            WHERE
                nutrition_id = OLD.nutrition_id);
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER insert_user_init_data
AFTER INSERT ON users FOR EACH ROW
EXECUTE FUNCTION init_user_data_columns ();

CREATE TRIGGER update_recipes_modified BEFORE
UPDATE ON recipes FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_users_recipes_recipe_count
AFTER INSERT ON users_recipes FOR EACH ROW
EXECUTE FUNCTION update_recipe_count ();

CREATE TRIGGER decrement_recipes_count_after_delete
AFTER DELETE ON users_recipes FOR EACH ROW
EXECUTE FUNCTION decrement_recipe_count ();

CREATE TRIGGER update_category_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON categories_recipes FOR EACH ROW
EXECUTE FUNCTION update_category_fts_column ();

CREATE TRIGGER update_cuisine_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON cuisines_recipes FOR EACH ROW
EXECUTE FUNCTION update_cuisine_fts_column ();

CREATE TRIGGER update_ingredients_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON ingredients_recipes FOR EACH ROW
EXECUTE FUNCTION update_ingredients_fts_column ();

CREATE TRIGGER update_instructions_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON instructions_recipes FOR EACH ROW
EXECUTE FUNCTION update_instructions_fts_column ();

CREATE TRIGGER update_keywords_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON keywords_recipes FOR EACH ROW
EXECUTE FUNCTION update_keywords_fts_column ();

CREATE TRIGGER update_tools_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON tools_recipes FOR EACH ROW
EXECUTE FUNCTION update_tools_fts_column ();

CREATE TRIGGER cleanup_nutrition_per_100g
AFTER DELETE ON nutrition_per_100g FOR EACH ROW
EXECUTE FUNCTION delete_orphaned_nutrition ();

CREATE TRIGGER cleanup_nutrition_per_serving
AFTER DELETE ON nutrition_per_serving FOR EACH ROW
EXECUTE FUNCTION delete_orphaned_nutrition ();

---
--- Cron Jobs
---
DO $$
BEGIN
    IF current_database() = 'recipya' THEN
        EXECUTE format('SELECT cron.schedule(%L, %L, %L)', 'delete_expired_links', '0 0 * * *', 'DELETE FROM shares_recipes WHERE expires_at < NOW()');
    END IF;
END
$$;

---
--- Inserts
---
INSERT INTO
  measurement_systems (name)
VALUES
  ('Imperial (UK)'),
  ('Metric'),
  ('Metric (Australia)'),
  ('US Customary');

INSERT INTO
  categories (name)
VALUES
  ('uncategorized'),
  ('appetizers'),
  ('bread'),
  ('breakfasts'),
  ('condiments'),
  ('dessert'),
  ('lunch'),
  ('main dish'),
  ('salad'),
  ('side dish'),
  ('snacks'),
  ('soups'),
  ('stews');

INSERT INTO
  cuisines (name)
VALUES
  ('hungarian'),
  ('lebanese'),
  ('korean'),
  ('vegetarian');

INSERT INTO
  sections (name)
VALUES
  ('');
