CREATE FUNCTION get_tsv_config (lang char(3)) RETURNS regconfig AS $$
BEGIN
    RETURN CASE lang
    WHEN 'ara' THEN
        'arabic'
    WHEN 'cat' THEN
        'catalan'
    WHEN 'dan' THEN
        'danish'
    WHEN 'deu' THEN
        'german'
    WHEN 'eng' THEN
        'english'
    WHEN 'ell' THEN
        'greek'
    WHEN 'fin' THEN
        'finnish'
    WHEN 'fra' THEN
        'french'
    WHEN 'hin' THEN
        'hindi'
    WHEN 'hun' THEN
        'hungarian'
    WHEN 'hye' THEN
        'armenian'
    WHEN 'ind' THEN
        'indonesian'
    WHEN 'ita' THEN
        'italian'
    WHEN 'lit' THEN
        'lithuanian'
    WHEN 'nep' THEN
        'nepali'
    WHEN 'nld' THEN
        'dutch'
    WHEN 'por' THEN
        'portuguese'
    WHEN 'ron' THEN
        'romanian'
    WHEN 'rus' THEN
        'russian'
    WHEN 'spa' THEN
        'spanish'
    WHEN 'srp' THEN
        'serbian'
    WHEN 'swe' THEN
        'swedish'
    WHEN 'tam' THEN
        'tamil'
    WHEN 'tur' THEN
        'turkish'
    WHEN 'yid' THEN
        'yiddish'
    ELSE
        'simple'
    END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

---
--- Main tables
---

-- safety-assured:start
CREATE TABLE IF NOT EXISTS measurement_systems (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);
-- safety-assured:end

CREATE TABLE IF NOT EXISTS recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  image uuid,
  yield int2 NOT NULL DEFAULT 1,
  language varchar(3) NOT NULL,
  measurement_system_id int2 NOT NULL REFERENCES measurement_systems (id) ON DELETE CASCADE DEFAULT 2,
  notes text,
  source text NOT NULL DEFAULT '',
  is_favourite bool NOT NULL DEFAULT FALSE,
  rating int2 CHECK (
    rating IS NULL
    OR rating BETWEEN 1 AND 5
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  fts_combined tsvector NOT NULL GENERATED ALWAYS AS (
    setweight(
      to_tsvector(get_tsv_config (LANGUAGE), coalesce(name, '')),
      'A'
    ) || setweight(
      to_tsvector(get_tsv_config (LANGUAGE), coalesce(source, '')),
      'B'
    ) || setweight(
      to_tsvector(
        get_tsv_config (LANGUAGE),
        coalesce(description, '')
      ),
      'C'
    )
  ) STORED,
  fts_category tsvector NOT NULL DEFAULT ''::tsvector,
  fts_cuisine tsvector NOT NULL DEFAULT ''::tsvector,
  fts_ingredients tsvector NOT NULL DEFAULT ''::tsvector,
  fts_instructions tsvector NOT NULL DEFAULT ''::tsvector,
  fts_keywords tsvector NOT NULL DEFAULT ''::tsvector,
  fts_name tsvector NOT NULL GENERATED ALWAYS AS (
    to_tsvector(get_tsv_config (LANGUAGE), coalesce(name, ''))
  ) STORED,
  fts_tools tsvector NOT NULL DEFAULT ''::tsvector,
  UNIQUE (name, source, yield, user_id)
);

CREATE TABLE IF NOT EXISTS categories (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE IF NOT EXISTS cuisines (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE IF NOT EXISTS ingredients (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS instructions (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  duration_seconds integer
);

CREATE TABLE IF NOT EXISTS keywords (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE IF NOT EXISTS nutrition_per_100g (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  nutrition_id int8 NOT NULL REFERENCES nutrition (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS nutrition_per_serving (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  nutrition_id int8 NOT NULL REFERENCES nutrition (id) ON DELETE CASCADE,
  serving_size text NOT NULL
);

CREATE TABLE IF NOT EXISTS additional_images_recipe (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  image uuid NOT NULL,
  UNIQUE (recipe_id, image)
);

CREATE TABLE IF NOT EXISTS times (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  prep_seconds integer NOT NULL DEFAULT 0,
  cook_seconds integer NOT NULL DEFAULT 0,
  total_seconds integer NOT NULL GENERATED ALWAYS AS (prep_seconds + cook_seconds) STORED
);

CREATE TABLE IF NOT EXISTS tools (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL CHECK (lower(name) = name)
);

CREATE TABLE IF NOT EXISTS sections (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_settings (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  measurement_system_id int2 NOT NULL REFERENCES measurement_systems (id) ON DELETE CASCADE DEFAULT 1,
  nutrition_source_id int2 NOT NULL REFERENCES nutrition_sources (id) ON DELETE CASCADE DEFAULT 1,
  convert_automatically bool NOT NULL DEFAULT FALSE,
  cookbooks_view int NOT NULL DEFAULT 0,
  default_theme int4 NOT NULL DEFAULT 2,
  selected_theme int4 NOT NULL REFERENCES themes (id) ON DELETE SET DEFAULT DEFAULT 1,
  bold_ingredients bool NOT NULL DEFAULT false,
  timezone text NOT NULL DEFAULT 'UTC'
);

CREATE TABLE IF NOT EXISTS bold_indices_ingredients (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    instruction_id int8 NOT NULL REFERENCES instructions (id) ON DELETE CASCADE,
    start_index int4 NOT NULL,
    end_index int4 NOT NULL,
    CHECK (end_index > start_index),
    UNIQUE (recipe_id, instruction_id, start_index, end_index)
);

---
--- Association tables
---
CREATE TABLE IF NOT EXISTS categories_recipes (
  category_id int8 DEFAULT 1 REFERENCES categories (id) ON DELETE SET DEFAULT,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (category_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS cuisines_recipes (
  cuisine_id int8 DEFAULT 1 REFERENCES cuisines (id) ON DELETE SET DEFAULT,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (cuisine_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS ingredients_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id int8 NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  section_id int8 NOT NULL DEFAULT 1 REFERENCES sections (id) ON DELETE SET DEFAULT,
  section_order int2 NOT NULL DEFAULT 0,
  item_order int2 NOT NULL
);

CREATE TABLE IF NOT EXISTS instructions_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instruction_id int8 NOT NULL REFERENCES instructions (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  section_id int8 NOT NULL DEFAULT 1 REFERENCES sections (id) ON DELETE SET DEFAULT,
  section_order int2 NOT NULL DEFAULT 0,
  item_order int2 NOT NULL
);

CREATE TABLE IF NOT EXISTS keywords_recipes (
  keyword_id int8 NOT NULL REFERENCES keywords (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (keyword_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS recipe_timelines (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title text NOT NULL,
  comment text,
  rating int2 CHECK (
    rating IS NULL
    OR rating BETWEEN 1 AND 5
  ),
  image uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shares_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP + interval '7 days'),
  last_accessed timestamptz NOT NULL DEFAULT now(),
  click_count int NOT NULL DEFAULT 0,
  UNIQUE (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS tools_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id int8 NOT NULL REFERENCES tools (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  quantity int2 NOT NULL DEFAULT 1,
  tool_order int2 NOT NULL,
  UNIQUE (recipe_id, tool_id)
);

CREATE TABLE IF NOT EXISTS users_categories (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_id int8 NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, category_id)
);

CREATE TABLE IF NOT EXISTS users_keywords (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  keyword_id int8 NOT NULL REFERENCES keywords (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, keyword_id)
);

CREATE TABLE IF NOT EXISTS users_recipes (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS videos_recipes (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video uuid NOT NULL,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  duration interval,
  content_url text,
  embed_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (video, content_url, embed_url, recipe_id)
);

---
--- Function
---
CREATE FUNCTION init_user_data_columns () RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO users_categories (user_id, category_id)
    SELECT
        NEW.id,
        id
    FROM
        categories
    WHERE
        name IN ('uncategorized', 'appetizers', 'bread', 'breakfasts', 'condiments', 'dessert', 'lunch', 'main dish', 'salad', 'side dish', 'snacks', 'soups', 'stews');
    INSERT INTO user_settings (user_id)
        VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_category_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_category = COALESCE(
        (SELECT to_tsvector(get_tsv_config (
        LANGUAGE), string_agg(name, ' '))
         FROM categories c
         JOIN categories_recipes cr ON cr.category_id = c.id
         WHERE cr.recipe_id = recipe_id_to_update),
        ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_cuisine_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_cuisine = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(name, ' ' ORDER BY name))
            FROM cuisines c
                    JOIN cuisines_recipes cr ON cr.cuisine_id = c.id
            WHERE cr.recipe_id = recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_ingredients_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_ingredients = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(i.name, ' '))
            FROM ingredients i
                    JOIN ingredients_recipes ir ON ir.ingredient_id = i.id
            WHERE ir.recipe_id = recipe_id_to_update
            GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_instructions_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_instructions = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(i.name, ' '))
            FROM instructions i
                    JOIN instructions_recipes ir ON ir.instruction_id = i.id
            WHERE ir.recipe_id = recipe_id_to_update
            GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_keywords_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_keywords = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(k.name, ' '))
            FROM keywords k
                    JOIN keywords_recipes kr ON kr.keyword_id = k.id
            WHERE kr.recipe_id = recipe_id_to_update
            GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_tools_fts_column () RETURNS TRIGGER AS $$
DECLARE
    recipe_id_to_update int8;
BEGIN
    IF TG_OP = 'DELETE' THEN
        recipe_id_to_update := OLD.recipe_id;
    ELSE
        recipe_id_to_update := NEW.recipe_id;
    END IF;

    UPDATE recipes
    SET fts_tools = COALESCE(
            (SELECT to_tsvector(get_tsv_config (
            LANGUAGE), string_agg(t.name, ' '))
             FROM tools t
                      JOIN tools_recipes tr ON tr.tool_id = t.id
             WHERE tr.recipe_id = recipe_id_to_update
             GROUP BY recipe_id_to_update),
            ''::tsvector)
    WHERE id = recipe_id_to_update;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION delete_orphaned_nutrition () RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM nutrition
    WHERE id = OLD.nutrition_id
        AND NOT EXISTS (
            SELECT
                1
            FROM
                nutrition_per_100g
            WHERE
                nutrition_id = OLD.nutrition_id)
        AND NOT EXISTS (
            SELECT
                1
            FROM
                nutrition_per_serving
            WHERE
                nutrition_id = OLD.nutrition_id);
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER insert_user_init_data
AFTER INSERT ON users FOR EACH ROW
EXECUTE FUNCTION init_user_data_columns ();

CREATE TRIGGER update_recipes_modified BEFORE
UPDATE ON recipes FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_category_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON categories_recipes FOR EACH ROW
EXECUTE FUNCTION update_category_fts_column ();

CREATE TRIGGER update_cuisine_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON cuisines_recipes FOR EACH ROW
EXECUTE FUNCTION update_cuisine_fts_column ();

CREATE TRIGGER update_ingredients_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON ingredients_recipes FOR EACH ROW
EXECUTE FUNCTION update_ingredients_fts_column ();

CREATE TRIGGER update_instructions_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON instructions_recipes FOR EACH ROW
EXECUTE FUNCTION update_instructions_fts_column ();

CREATE TRIGGER update_keywords_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON keywords_recipes FOR EACH ROW
EXECUTE FUNCTION update_keywords_fts_column ();

CREATE TRIGGER update_tools_fts
AFTER INSERT
OR DELETE
OR
UPDATE ON tools_recipes FOR EACH ROW
EXECUTE FUNCTION update_tools_fts_column ();

CREATE TRIGGER cleanup_nutrition_per_100g
AFTER DELETE ON nutrition_per_100g FOR EACH ROW
EXECUTE FUNCTION delete_orphaned_nutrition ();

CREATE TRIGGER cleanup_nutrition_per_serving
AFTER DELETE ON nutrition_per_serving FOR EACH ROW
EXECUTE FUNCTION delete_orphaned_nutrition ();

---
--- Cron Jobs
---
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        PERFORM cron.schedule(
            'delete_expired_links',
            '0 0 * * *',
            'DELETE FROM shares_recipes WHERE expires_at < NOW()'
        );
    END IF;
END;
$$;

---
--- Inserts
---
INSERT INTO
  measurement_systems (name)
VALUES
  ('Imperial (UK)'),
  ('Metric'),
  ('Metric (Australia)'),
  ('US Customary');

INSERT INTO
  categories (name)
VALUES
  ('uncategorized'),
  ('appetizers'),
  ('bread'),
  ('breakfasts'),
  ('condiments'),
  ('dessert'),
  ('lunch'),
  ('main dish'),
  ('salad'),
  ('side dish'),
  ('snacks'),
  ('soups'),
  ('stews');

INSERT INTO
  cuisines (name)
VALUES
  ('afghan'),
  ('african'),
  ('albanian'),
  ('algerian'),
  ('andean'),
  ('argentinian'),
  ('armenian'),
  ('australian'),
  ('austrian'),
  ('azerbaijani'),
  ('bahamian'),
  ('bangladeshi'),
  ('barbadian'),
  ('basque'),
  ('belarusian'),
  ('belizean'),
  ('bolivian'),
  ('brazilian'),
  ('burmese'),
  ('cambodian'),
  ('cameroonian'),
  ('canadian'),
  ('cape verdean'),
  ('caribbean'),
  ('chilean'),
  ('chinese'),
  ('colombian'),
  ('costa rican'),
  ('croatian'),
  ('cuban'),
  ('cypriot'),
  ('czech'),
  ('danish'),
  ('dominican'),
  ('ecuadorian'),
  ('egyptian'),
  ('el salvadoran'),
  ('estonian'),
  ('ethiopian'),
  ('fijian'),
  ('finnish'),
  ('french'),
  ('georgian'),
  ('german'),
  ('ghanaian'),
  ('greek'),
  ('guatemalan'),
  ('guamanian'),
  ('guyanese'),
  ('haitian'),
  ('hmong'),
  ('honduran'),
  ('hong kong'),
  ('hungarian'),
  ('icelandic'),
  ('indian'),
  ('indonesian'),
  ('iranian'),
  ('iraqi'),
  ('irish'),
  ('israeli'),
  ('italian'),
  ('jamaican'),
  ('japanese'),
  ('jordanian'),
  ('kazakh'),
  ('kenyan'),
  ('korean'),
  ('laotian'),
  ('latin american'),
  ('latvian'),
  ('lebanese'),
  ('liberian'),
  ('libyan'),
  ('lithuanian'),
  ('macedonian'),
  ('malaysian'),
  ('maldivian'),
  ('maltese'),
  ('martinican'),
  ('mauritiuan'),
  ('mediterranean'),
  ('mexican'),
  ('middle eastern'),
  ('moldovan'),
  ('moroccan'),
  ('myanmar'),
  ('nicaraguan'),
  ('nigerian'),
  ('nordic'),
  ('norwegian'),
  ('dutch'),
  ('pakistani'),
  ('palestinian'),
  ('paraguayan'),
  ('peruvian'),
  ('philippine'),
  ('polish'),
  ('portuguese'),
  ('puerto rican'),
  ('romanian'),
  ('russian'),
  ('serbian'),
  ('singaporean'),
  ('slavic'),
  ('somali'),
  ('south african'),
  ('south sudanese'),
  ('spanish'),
  ('sri lankan'),
  ('sudanese'),
  ('swedish'),
  ('swiss'),
  ('syrian'),
  ('taiwanese'),
  ('thai'),
  ('tibetan'),
  ('trinidadian'),
  ('tunisian'),
  ('turkish'),
  ('ugandan'),
  ('ukrainian'),
  ('emirati'),
  ('british'),
  ('american'),
  ('uruguayan'),
  ('uzbek'),
  ('venezuelan'),
  ('vietnamese'),
  ('yemeni'),
  ('zimbabwean'),
  ('vegetarian');

INSERT INTO
  sections (name)
VALUES
  ('');
