---
--- Main tables
---
CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    email text NOT NULL UNIQUE CHECK (lower(email) = email),
    password_hash varchar(255) NOT NULL,
    password_salt uuid NOT NULL DEFAULT gen_random_uuid (),
    token_salt uuid NOT NULL DEFAULT gen_random_uuid (),
    is_remember_me bool NOT NULL DEFAULT FALSE,
    is_email_verified bool NOT NULL DEFAULT FALSE,
    is_admin bool NOT NULL DEFAULT FALSE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- safety-assured:start
CREATE TABLE IF NOT EXISTS themes (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
-- safety-assured:end

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_remember_me boolean NOT NULL DEFAULT FALSE,
    token text UNIQUE NOT NULL,
    expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
    is_used bool NOT NULL DEFAULT FALSE,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS downloads (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token uuid NOT NULL,
  file_path text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

---
--- Functions
---
CREATE FUNCTION update_updated_at_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column ();

---
--- Inserts
---
INSERT INTO themes (name)
VALUES
    ('default'),
    ('system'),
    ('light'),
    ('dark'),
    ('abyss'),
    ('acid'),
    ('aqua'),
    ('autumn'),
    ('black'),
    ('bumblebee'),
    ('business'),
    ('caramellatte'),
    ('coffee'),
    ('corporate'),
    ('cmyk'),
    ('cupcake'),
    ('cyberpunk'),
    ('dim'),
    ('dracula'),
    ('emerald'),
    ('fantasy'),
    ('forest'),
    ('garden'),
    ('halloween'),
    ('lemonade'),
    ('lofi'),
    ('luxury'),
    ('night'),
    ('nord'),
    ('pastel'),
    ('retro'),
    ('silk'),
    ('sunset'),
    ('synthwave'),
    ('valentine'),
    ('wireframe'),
    ('winter');
