[package]
name = "app"
version = "0.0.0"
publish = false

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
config.workspace = true
derive_more.workspace = true
diesel.workspace = true
diesel-async.workspace = true
email.workspace = true
models.workspace = true
schema-org.workspace = true
recipya-scraper.workspace = true
repository.workspace = true
support.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
