mod financial_product;

pub use financial_product::*;

use crate::Thing;
use crate::permutations::administrative_area::AdministrativeAreaOrGeoShapeOrPlaceOrText;
use crate::permutations::brand::BrandOrOrganization;
use crate::permutations::person::OrganizationOrPerson;
use crate::permutations::text::TextOrURL;
use crate::thing::intangible::Audience;
use crate::thing::intangible::structured_value::OpeningHoursSpecification;
use schemars::JsonSchema;
use serde::Deserialize;

/// A service provided by an organization, e.g. delivery service, print services, etc.
#[derive(Debug, Default, Deserialize, PartialEq, JsonSchema)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct Service {
    /// The overall rating, based on a collection of reviews or ratings, of the item.
    pub aggregate_rating: AggregateRating,
    /// The geographic area where a service or offered item is provided. Supersedes serviceArea.
    pub area_served: AdministrativeAreaOrGeoShapeOrPlaceOrText,
    /// An intended audience, i.e. a group for whom something was created. Supersedes serviceAudience.
    pub audience: Audience,
    /// A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
    pub available_channel: ServiceChannel,
    /// An award won by or for this item. Supersedes awards.
    pub award: String,
    /// The brand(s) associated with a product or service, or the brand(s) maintained by an
    /// organization or business person.
    pub brand: BrandOrOrganization,
    /// An entity that arranges for an exchange between a buyer and a seller. In most cases a broker
    /// never acquires or releases ownership of a product or service involved in an exchange. If it
    /// is not clear whether an entity is a broker, seller, or buyer, the latter two terms are
    /// preferred. Supersedes bookingAgent.
    pub broker: OrganizationOrPerson,
    /// A category for the item. Greater signs or slashes can be used to informally indicate a
    /// category hierarchy.
    pub category: CategoryCodeOrPhysicalActivityCategoryOrTextOrThingOrURL,
    /// Certification information about a product, organization, service, place, or person.
    pub has_certification: Certification,
    /// Indicates an OfferCatalog listing for this Organization, Person, or Service.
    pub has_offer_catalog: OfferCatalog,
    /// The hours during which this service or contact is available.
    pub hours_available: OpeningHoursSpecification,
    /// A pointer to another, somehow related product (or multiple products).
    pub is_related_to: ProductOrService,
    /// A pointer to another, functionally similar product (or multiple products).
    pub is_similar_to: ProductOrService,
    /// An associated logo.
    pub logo: ImageObjectOrURL,
    /// An offer to provide this item—for example, an offer to sell a product, rent the DVD of a
    /// movie, perform a service, or give away tickets to an event. Use businessFunction to indicate
    /// the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to
    /// describe a Demand. While this property is listed as expected on a number of common types, it
    /// can be used in others. In that case, using a second type, such as Product or a subtype of
    /// Product, can clarify the nature of the offer.
    ///
    /// Inverse property: itemOffered
    pub offers: DemandOrOffer,
    /// The service provider, service operator, or service performer; the goods producer. Another
    /// party (a seller) may offer those services or goods on behalf of the provider. A provider may
    /// also serve as the seller. Supersedes carrier.
    pub provider: OrganizationOrPerson,
    /// Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
    pub provider_mobility: String,
    /// A review of the item. Supersedes reviews.
    pub review: Review,
    /// The tangible thing generated by the service, e.g. a passport, permit, etc.
    /// Supersedes produces.
    pub service_output: Thing,
    /// The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
    pub service_type: GovernmentBenefitsTypeOrText,
    /// A slogan or motto associated with the item.
    pub slogan: String,
    /// Human-readable terms of service documentation.
    pub terms_of_service: TextOrURL,
    #[serde(flatten)]
    pub thing: Thing,
}
