use std::{collections::HashMap, fmt::Formatter, sync::OnceLock};

use reqwest::Url;

use super::{Error, Result};

/// Enumeration of all websites that can be scraped.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {
    O101cookbooksDotCom,
    O15gramsDotCom,
    O24kitchenDotNl,
    O750gDotCom,
    AbuelasCounterDotCom,
    ACoupleCooksDotCom,
    AddAPinchDotCom,
    AfghanKitchenRecipesDotCom,
    AFlavorJournalDotCom,
    AhDotNl,
    AkispetretzikisDotCom,
    AlexandraCooksDotCom,
    ALittleBitYummyDotCom,
    AllCladDotCom,
    AldiDotComDotAu,
    AllTheHealthyThingsDotCom,
    AllRecipesDotCom,
    AltonBrownDotCom,
    AmazingRibsDotCom,
    AmbitiousKitchenDotCom,
    AmericasTestKitchenDotCom,
    AngielaEatsDotCom,
    AniagotujeDotPl,
    AntilliaansEtenDotNl,
    ArchanasKitchenDotCom,
    ArgiroDotGr,
    ArlaDotSe,
    AtelierDesChefsDotFr,
    AverieCooksDotCom,
    AvocadoSkilletDotCom,
    BakingMischiefDotCom,
    BakelsDotComDotAu,
    BakingSenseDotCom,
    BarefootContessaDotCom,
    BareFeetInTheKitchenDotCom,
    BbcDotCoDotUk,
    BbcGoodFoodDotCom,
    BettyBossiDotCh,
    BettyCrockerDotCom,
    BeyondKimcheeDotCom,
    BiancazaPatkaDotCom,
    BigOvenDotCom,
    BlogDotGialloZafferanoDotIt,
    BlueApronDotCom,
    BlueJeanChefDotCom,
    BreadtopiaDotCom,
    BrianLagerstromDotCom,
    BriceletBaklavaDotCh,
    BritishBakelsDotCoDotUk,
    BodybuildingDotCom,
    BonAppetitDotCom,
    BongEatsDotCom,
    BottomlessGreensDotCom,
    BowlOfDeliciousDotCom,
    BudgetBytesDotCom,
    CafeDelitesDotCom,
    CanadaDotCa,
    CastironKetoDotCom,
    CdKitchenDotCom,
    CestMaFourneeDotCom,
    ChatelaineDotCom,
    ChefKochDotDe,
    ChefNiniDotCom,
    ChefSavvyDotCom,
    CheJorgeDotCom,
    ChetnamakanDotCoDotUk,
    ChineseCookingDemystifiedDotSubstackDotCom,
    ClaudiaAbrilComBr,
    ClosetCookingDotCom,
    ColruytDotBe,
    ComidinhasdoChefDotCom,
    CookEatShareDotCom,
    CookieAndKateDotCom,
    CookpadDotCom,
    CookTalkDotCom,
    CoopDotSe,
    CopykatDotCom,
    CostcoDotCom,
    CountryLivingDotCom,
    CreativeCanningDotCom,
    CucchiaioDotIt,
    CulyDotNl,
    CuisineAndTravelDotCom,
    CuisineazDotCom,
    CyberCookDotComDotBr,
    DamnDeliciousDotNet,
    DaringGourmetDotCom,
    DavidLebovitzDotCom,
    DelishDotCom,
    DherbsDotCom,
    DinnerAtTheZooDotCom,
    DinnerThenDessertDotCom,
    DishDotCoDotNz,
    DitchTheCarbsDotCom,
    DomesticateMeDotCom,
    DonnaHayDotComDotAu,
    DownshiftologyDotCom,
    DrDotdk,
    DreenaburtonDotCom,
    DrinkoteketDotSe,
    EatingBirdFoodDotCom,
    EatingWellDotCom,
    EatLiveRunDotCom,
    EatSmarterDotCom,
    EatWell101DotCom,
    EatWhatTonightDotCom,
    ElaveganDotCom,
    ElephantasticVeganDotCom,
    EmmikochteinfachDotDe,
    EntertainingWithBethDotCom,
    EpicuriousDotCom,
    ErrensKitchenDotCom,
    EtenvaneefkeDotNl,
    ExpressenDotSe,
    EvolvingTableDotCom,
    FamilyFoodOnTheTableDotCom,
    FarmhouseDeliveryDotCom,
    FarmhouseOnBooneDotCom,
    FattoInCasaDaBenedettaDotIt,
    FeastingAtHomeDotCom,
    FelixDotKitchen,
    FifteenSpatulasDotCom,
    FineDiningLoversDotCom,
    FindingTimeForCookingDotCom,
    FitMenCookDotCom,
    FitsLowCookerQueenDotCom,
    FoodDotCom,
    Food52DotCom,
    FoodalDotCom,
    FoodAndWineDotCom,
    FoodByMariaDotCom,
    FoodieCrushDotCom,
    FoodNetworkDotCoDotUk,
    FoodRepublicDotCom,
    FoolProofLivingDotCom,
    ForksOverKnivesDotCom,
    ForkToSpoonDotCom,
    FrancescaKooktDotNl,
    FranzoesischKochenDotDe,
    FredriksfikaDotAllasDotSe,
    GastroPlantDotCom,
    GazoakleyChefDotCom,
    GesundAktivDotCom,
    GialloZafferanoDotCom,
    GimmeSomeOvenDotCom,
    GloboDotCom,
    GlutenFreeTablesDotCom,
    GodtDotNo,
    GonnaWantSecondsDotCom,
    GoodEatingsDotCom,
    GoodFoodDiscoveriesDotCom,
    GoodHouseKeepingDotCom,
    GoodToDotCom,
    GourmetTravellerDotComDotAu,
    GurkiDotNo,
    GrandFraisDotCom,
    GreatBritishChefsDotCom,
    GreeneviDotCom,
    GrimGrainsDotCom,
    GroupRecipesDotCom,
    HalfBakedHarvestDotCom,
    HandleTheHeatDotCom,
    HassanChefDotCom,
    HeadbangersKitchenDotCom,
    HealthyLittleFoodiesDotCom,
    HeatherChristoDotCom,
    HelloFreshDotCom,
    HomebrewAnswersDotCom,
    HomeChefDotCom,
    HostTheToastDotCom,
    IcaDotSe,
    ImWorthyDotCom,
    InBloomBakeryDotCom,
    IndianHealthyRecipesDotCom,
    InnitDotCom,
    InsanelyGoodRecipesDotCom,
    InspiralizedDotCom,
    InstantPotDotCom,
    JamieOliverDotCom,
    JaimysKitchenDotNl,
    JarofLemonsDotCom,
    JimCooksFoodGoodDotCom,
    JoCooksDotCom,
    JoyFoodSunshineDotCom,
    JoyTheBakerDotCom,
    JulieGoodwinDotComDotAu,
    JumboDotCom,
    JustATasteDotCom,
    JustBentoDotCom,
    JustOneCookBookDotCom,
    KeepinItKindDotCom,
    KennyMcGovernDotCom,
    KingArthurBakingDotCom,
    KitchenAidDotComDotAu,
    KitchenSanctuaryDotCom,
    KitchenStoriesDotCom,
    KochbarDotDe,
    KochbucherDotCom,
    KoketDotSe,
    KookjijDotNl,
    KptnCookDotCom,
    KristinesKitchenBlogDotCom,
    KuchniaDomowaDotPl,
    KuchynalidlaDotSk,
    KwestiasmakuDotCom,
    LahbcoDotCom,
    LatelierDeRoxaneDotCom,
    LeanAndGreenRecipesDotNet,
    LeckerDotDe,
    LeCremeDeLaCrumbDotCom,
    LekkerenSimpelDotCom,
    LeukeReceptenDotNl,
    LifestyleOfAFoodieDotCom,
    LidlDotNl,
    LidlKochenDotDe,
    LithuanianInTheUsaDotCom,
    LittleSpiceJarDotCom,
    LivelyTableDotCom,
    LivingTheGreenLifeDotCom,
    LoveAndLemonsDotCom,
    LovingItVeganDotCom,
    MaangchiDotCom,
    MadensVerdenDotdk,
    MadsvinDotCom,
    MarmitonDotOrg,
    MarthaStewartDotCom,
    MatpratDotNo,
    McCormickDotCom,
    MeljoulwanDotCom,
    MelsKitchenCafeDotCom,
    MexicanMadeMeatlessDotCom,
    MindmegetteDotHu,
    MinimalistBakerDotCom,
    MinistryOfCurryDotCom,
    MisyaDotInfo,
    ModernHoneyDotCom,
    MomonTimeoutDotCom,
    MomsDishDotCom,
    MomsWithCrockpotsDotCom,
    MotherThymeDotCom,
    MoulinexDotFr,
    MundoDeReceitasBimbyDotComDotPt,
    MyBakingAddictionDotCom,
    MyJewishLearningDotCom,
    MyKitchen101DotCom,
    MyKoreanKitchenDotCom,
    MyGingerGarlicKitchenDotCom,
    MyKitchen101enDotCom,
    MyPlateDotGov,
    MyRecipesDotCom,
    NatashasKitchenDotCom,
    NigellaDotCom,
    NinjaTestKitchenDotEu,
    NourishedByNutritionDotCom,
    NosaltyDotHu,
    NotEnoughCinnamonDotCom,
    NrkDotNo,
    Number2PencilDotCom,
    NutritionFactsDotOrg,
    NyTimesDotCom,
    OhSheGlowsDotCom,
    OkokoReceptenDotNl,
    OmnivoresCookbookDotCom,
    OnceUponAChefDotCom,
    OhMyVeggiesDotCom,
    OneSweetAppetiteDotCom,
    OwenHanDotCom,
    PaleoRunningMommaDotCom,
    PanelinhaDotComDotBr,
    PaniniHappyDotCom,
    ParsleyAndParmDotCom,
    PersnicketyPlatesDotCom,
    PickupLimesDotCom,
    PinchOfYumDotCom,
    PinkOwlKitchenDotCom,
    PingoDoceDotPt,
    PlatingPixelsDotCom,
    PlentyVeganDotCom,
    PloetzBlogDotDe,
    PlowingThroughLifeDotCom,
    PopSugarDotCoDotUk,
    PotatoRollsDotGom,
    PracticalSelfRelianceDotCom,
    PressureLuckCookingDotCom,
    PrimalEdgeHealthDotCom,
    ProjectGezondDotNl,
    PrzepisyDotPl,
    PurelyPopeDotCom,
    PureWowDotCom,
    PurpleCarrotDotCom,
    PuurgezondDotNl,
    QuitoqueDotFr,
    RachlmansFieldDotCom,
    RadioFranceDotFr,
    RainbowPlantLifeDotCom,
    RealSimpleDotCom,
    ReceitasNestleDotComDotBr,
    RecettesDotQcDotCa,
    RecipeGirlDotCom,
    RecipeRunnerDotCom,
    RecipeTinEatsDotCom,
    RedditDotCom,
    RedhouseSpiceDotCom,
    ReisHungerDotDe,
    RezeptWeltDotDe,
    RicettaDotIt,
    RicettePerBimbyDotIt,
    RobinasBellDotCom,
    RosannaPansinoDotCom,
    RutgerbaktDotNl,
    RecipeCommunityDotComDotAu,
    SaboresaJinomotoDotComDotBr,
    SallysBakingAddictionDotCom,
    SallysBlogDotDe,
    SaltAndLavenderDotCom,
    SaltPepperSkilletDotCom,
    SarahsVeganGuideDotCom,
    SaveurDotCom,
    SavoryNothingsDotCom,
    SeriousEatsDotCom,
    SimpleVeganistaDotCom,
    SimplyCookitDotCom,
    SimplyQuinoaDotCom,
    SimplyRecipesDotCom,
    SimplyWhiskedDotCom,
    SkinnyTasteDotCom,
    SmittenKitchenDotCom,
    SoborsDotHu,
    SouthernCastIronDotCom,
    SouthernLivingDotCom,
    SpendWithPenniesDotCom,
    SpiceboxTravelsDotCom,
    StaySnatchedDotCom,
    SteamyKitchenDotCom,
    StreetKitchenDotCo,
    StrongrFastrDotCom,
    SunBasketDotCom,
    SundPaabudgetDotdk,
    SunsetDotCom,
    SweetcsDesignsDotCom,
    SweetPeasAndSaffronDotCom,
    TasteAtlasDotCom,
    TasteOfHomeDotCom,
    TastesBetterFromScratchDotCom,
    TastesOfLizzyTDotCom,
    TastyDotCo,
    TastyKitchenDotCom,
    TescoDotCom,
    ThatVeganDadDotNet,
    TheCleverCarrotDotCom,
    TheCookieRookieDotCom,
    TheCookingGuyDotCom,
    TheExpertGuidesDotCom,
    TheFoodFlamingoDotCom,
    TheGucchaDotCom,
    TheHappyFoodieDotCoDotUk,
    TheHeartySoulDotCom,
    TheKitchenCommunityDotOrg,
    TheKitchenMagPieDotCom,
    TheKitchnDotCom,
    TheMagicalSlowCookerDotCom,
    TheNutritiousKitchenDotCo,
    TheModernProperDotCom,
    ThePalatableLifeDotCom,
    ThePioneerWomanDotCom,
    TheRecipeCriticDotCom,
    TheSaltyMarshmallowDotCom,
    TheSpruceEatsDotCom,
    TheVintageMixerDotCom,
    TheWoksOfLifeDotCom,
    ThinliciousDotCom,
    TidyMomDotNet,
    TimesOfIndiaDotCom,
    TineDotNo,
    TudogostosoDotComDotBr,
    TwoPeasAndTheirPodDotCom,
    TwoSleeversDotCom,
    UitPaulinesKeukenDotNl,
    UnsophistiCookDotCom,
    UsaPearsDotOrg,
    ValdemarsroDotdk,
    VanillaAndBeanDotCom,
    VeganPratiqueDotFr,
    VegetarBloggenDotNo,
    VegolosiDotIt,
    VegRecipesOfIndiaDotCom,
    WaitRoseDotCom,
    WatchWhatUEatDotCom,
    WeAreNotMarthaDotCom,
    WeightWatchersDotCom,
    WellPlatedDotCom,
    WhatsGabyCookingDotCom,
    WholeFoodsMarketDotCoDotUk,
    WikibooksDotOrg,
    WikibooksDotOrgMobile,
    WomensWeeklyFoodDotComDotAu,
    WoopDotCoDotNz,
    YeMekDotNet,
    YumeliseDotFr,
    ZeitDotDe,
    ZenbellyDotCom,
}

impl Website {
    /// Creates a `Website` instance from a given URL.
    pub fn from(url: &str) -> Result<Self> {
        let url = Url::parse(url).map_err(|err| Error::Parse(err.to_string()))?;
        let domain = url.domain().ok_or(Error::UnknownWebsite)?;

        websites_map_to_website()
            .get(domain)
            .copied()
            .ok_or(Error::UnknownWebsite)
    }
}

impl std::fmt::Display for Website {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match websites_map_to_domain().get_key_value(self) {
            Some((_, url)) => write!(f, "{url}"),
            None => write!(f, "URL not found"),
        }
    }
}

fn websites_map_to_domain() -> &'static HashMap<Website, String> {
    static INSTANCE: OnceLock<HashMap<Website, String>> = OnceLock::new();

    INSTANCE.get_or_init(|| {
        HashMap::from([
            (Website::O101cookbooksDotCom, "www.101cookbooks.com".into()),
            (Website::O15gramsDotCom, "15gram.be".into()),
            (Website::O24kitchenDotNl, "www.24kitchen.nl".into()),
            (Website::O750gDotCom, "www.750g.com".into()),
            (Website::AbuelasCounterDotCom, "abuelascounter.com".into()),
            (Website::ACoupleCooksDotCom, "www.acouplecooks.com".into()),
            (Website::AddAPinchDotCom, "addapinch.com".into()),
            (
                Website::AfghanKitchenRecipesDotCom,
                "www.afghankitchenrecipes.com".into(),
            ),
            (Website::AFlavorJournalDotCom, "aflavorjournal.com".into()),
            (Website::AhDotNl, "www.ah.nl".into()),
            (Website::AkispetretzikisDotCom, "akispetretzikis.com".into()),
            (Website::AlexandraCooksDotCom, "alexandracooks.com".into()),
            (Website::ALittleBitYummyDotCom, "alittlebityummy.com".into()),
            (Website::AllCladDotCom, "www.all-clad.com".into()),
            (Website::AldiDotComDotAu, "www.aldi.com.au".into()),
            (
                Website::AllTheHealthyThingsDotCom,
                "allthehealthythings.com".into(),
            ),
            (Website::AllRecipesDotCom, "www.allrecipes.com".into()),
            (Website::AltonBrownDotCom, "altonbrown.com".into()),
            (Website::AmazingRibsDotCom, "amazingribs.com".into()),
            (
                Website::AmbitiousKitchenDotCom,
                "www.ambitiouskitchen.com".into(),
            ),
            (
                Website::AmericasTestKitchenDotCom,
                "www.americastestkitchen.com".into(),
            ),
            (Website::AngielaEatsDotCom, "www.angielaeats.com".into()),
            (Website::AniagotujeDotPl, "aniagotuje.pl".into()),
            (
                Website::AntilliaansEtenDotNl,
                "www.antilliaans-eten.nl".into(),
            ),
            (
                Website::ArchanasKitchenDotCom,
                "www.archanaskitchen.com".into(),
            ),
            (Website::ArgiroDotGr, "www.argiro.gr".into()),
            (Website::ArlaDotSe, "www.arla.se".into()),
            (
                Website::AtelierDesChefsDotFr,
                "www.atelierdeschefs.fr".into(),
            ),
            (Website::AverieCooksDotCom, "www.averiecooks.com".into()),
            (Website::AvocadoSkilletDotCom, "avocadoskillet.com".into()),
            (Website::BakingMischiefDotCom, "bakingmischief.com".into()),
            (Website::BakelsDotComDotAu, "www.bakels.com.au".into()),
            (Website::BakingSenseDotCom, "www.baking-sense.com".into()),
            (
                Website::BarefootContessaDotCom,
                "barefootcontessa.com".into(),
            ),
            (
                Website::BareFeetInTheKitchenDotCom,
                "barefeetinthekitchen.com".into(),
            ),
            (Website::BbcDotCoDotUk, "www.bbc.co.uk".into()),
            (Website::BbcGoodFoodDotCom, "www.bbcgoodfood.com".into()),
            (Website::BettyBossiDotCh, "www.bettybossi.ch".into()),
            (Website::BettyCrockerDotCom, "www.bettycrocker.com".into()),
            (Website::BeyondKimcheeDotCom, "www.beyondkimchee.com".into()),
            (Website::BiancazaPatkaDotCom, "biancazapatka.com".into()),
            (Website::BigOvenDotCom, "www.bigoven.com".into()),
            (
                Website::BlogDotGialloZafferanoDotIt,
                "blog.giallozafferano.it".into(),
            ),
            (Website::BlueApronDotCom, "www.blueapron.com".into()),
            (Website::BlueJeanChefDotCom, "bluejeanchef.com".into()),
            (Website::BreadtopiaDotCom, "breadtopia.com".into()),
            (
                Website::BrianLagerstromDotCom,
                "www.brianlagerstrom.com".into(),
            ),
            (Website::BriceletBaklavaDotCh, "briceletbaklava.ch".into()),
            (
                Website::BritishBakelsDotCoDotUk,
                "www.britishbakels.co.uk".into(),
            ),
            (Website::BodybuildingDotCom, "www.bodybuilding.com".into()),
            (Website::BonAppetitDotCom, "www.bonappetit.com".into()),
            (Website::BongEatsDotCom, "www.bongeats.com".into()),
            (
                Website::BottomlessGreensDotCom,
                "bottomlessgreens.com".into(),
            ),
            (
                Website::BowlOfDeliciousDotCom,
                "www.bowlofdelicious.com".into(),
            ),
            (Website::BudgetBytesDotCom, "www.budgetbytes.com".into()),
            (Website::CafeDelitesDotCom, "cafedelites.com".into()),
            (Website::CanadaDotCa, "food-guide.canada.ca".into()),
            (Website::CastironKetoDotCom, "www.castironketo.net".into()),
            (Website::CdKitchenDotCom, "www.cdkitchen.com".into()),
            (Website::CestMaFourneeDotCom, "www.cestmafournee.com".into()),
            (Website::ChatelaineDotCom, "chatelaine.com".into()),
            (Website::ChefKochDotDe, "www.chefkoch.de".into()),
            (Website::ChefNiniDotCom, "www.chefnini.com".into()),
            (Website::ChefSavvyDotCom, "chefsavvy.com".into()),
            (Website::CheJorgeDotCom, "chejorge.com".into()),
            (Website::ChetnamakanDotCoDotUk, "chetnamakan.co.uk".into()),
            (
                Website::ChineseCookingDemystifiedDotSubstackDotCom,
                "chinesecookingdemystified.substack.com".into(),
            ),
            (Website::ClaudiaAbrilComBr, "claudia.abril.com.br".into()),
            (Website::ClosetCookingDotCom, "www.closetcooking.com".into()),
            (Website::ColruytDotBe, "www.colruyt.be".into()),
            (
                Website::ComidinhasdoChefDotCom,
                "comidinhasdochef.com".into(),
            ),
            (Website::CookEatShareDotCom, "cookeatshare.com".into()),
            (Website::CookieAndKateDotCom, "cookieandkate.com".into()),
            (Website::CookpadDotCom, "cookpad.com".into()),
            (Website::CookTalkDotCom, "cook-talk.com".into()),
            (Website::CoopDotSe, "www.coop.se".into()),
            (Website::CopykatDotCom, "copykat.com".into()),
            (Website::CostcoDotCom, "www.costco.com".into()),
            (Website::CountryLivingDotCom, "www.countryliving.com".into()),
            (Website::CreativeCanningDotCom, "creativecanning.com".into()),
            (Website::CucchiaioDotIt, "www.cucchiaio.it".into()),
            (Website::CulyDotNl, "www.culy.nl".into()),
            (
                Website::CuisineAndTravelDotCom,
                "www.cuisineandtravel.com".into(),
            ),
            (Website::CuisineazDotCom, "www.cuisineaz.com".into()),
            (Website::CyberCookDotComDotBr, "cybercook.com.br".into()),
            (Website::DamnDeliciousDotNet, "damndelicious.net".into()),
            (Website::DaringGourmetDotCom, "www.daringgourmet.com".into()),
            (Website::DavidLebovitzDotCom, "www.davidlebovitz.com".into()),
            (Website::DelishDotCom, "www.delish.com".into()),
            (Website::DherbsDotCom, "www.dherbs.com".into()),
            (
                Website::DinnerAtTheZooDotCom,
                "www.dinneratthezoo.com".into(),
            ),
            (
                Website::DinnerThenDessertDotCom,
                "dinnerthendessert.com".into(),
            ),
            (Website::DishDotCoDotNz, "dish.co.nz".into()),
            (Website::DitchTheCarbsDotCom, "www.ditchthecarbs.com".into()),
            (Website::DomesticateMeDotCom, "domesticate-me.com".into()),
            (Website::DonnaHayDotComDotAu, "www.donnahay.com.au".into()),
            (Website::DownshiftologyDotCom, "downshiftology.com".into()),
            (Website::DrDotdk, "www.dr.dk".into()),
            (Website::DreenaburtonDotCom, "dreenaburton.com".into()),
            (Website::DrinkoteketDotSe, "drinkoteket.se".into()),
            (
                Website::EatingBirdFoodDotCom,
                "www.eatingbirdfood.com".into(),
            ),
            (Website::EatingWellDotCom, "www.eatingwell.com".into()),
            (Website::EatLiveRunDotCom, "www.eatliverun.com".into()),
            (Website::EatSmarterDotCom, "eatsmarter.com".into()),
            (Website::EatWell101DotCom, "www.eatwell101.com".into()),
            (Website::EatWhatTonightDotCom, "eatwhattonight.com".into()),
            (Website::ElaveganDotCom, "elavegan.com".into()),
            (
                Website::ElephantasticVeganDotCom,
                "www.elephantasticvegan.com".into(),
            ),
            (Website::EmmikochteinfachDotDe, "emmikochteinfach.de".into()),
            (
                Website::EntertainingWithBethDotCom,
                "entertainingwithbeth.com".into(),
            ),
            (Website::EpicuriousDotCom, "www.epicurious.com".into()),
            (Website::ErrensKitchenDotCom, "www.errenskitchen.com".into()),
            (Website::EtenvaneefkeDotNl, "www.etenvaneefke.nl".into()),
            (Website::ExpressenDotSe, "alltommat.expressen.se".into()),
            (Website::EvolvingTableDotCom, "www.evolvingtable.com".into()),
            (
                Website::FamilyFoodOnTheTableDotCom,
                "www.familyfoodonthetable.com".into(),
            ),
            (
                Website::FarmhouseDeliveryDotCom,
                "recipes.farmhousedelivery.com".into(),
            ),
            (
                Website::FarmhouseOnBooneDotCom,
                "www.farmhouseonboone.com".into(),
            ),
            (
                Website::FattoInCasaDaBenedettaDotIt,
                "www.fattoincasadabenedetta.it".into(),
            ),
            (
                Website::FeastingAtHomeDotCom,
                "www.feastingathome.com".into(),
            ),
            (Website::FelixDotKitchen, "felix.kitchen".into()),
            (
                Website::FifteenSpatulasDotCom,
                "www.fifteenspatulas.com".into(),
            ),
            (
                Website::FineDiningLoversDotCom,
                "www.finedininglovers.com".into(),
            ),
            (
                Website::FindingTimeForCookingDotCom,
                "findingtimeforcooking.com".into(),
            ),
            (Website::FitMenCookDotCom, "fitmencook.com".into()),
            (
                Website::FitsLowCookerQueenDotCom,
                "fitslowcookerqueen.com".into(),
            ),
            (Website::FoodDotCom, "www.food.com".into()),
            (Website::Food52DotCom, "food52.com".into()),
            (Website::FoodalDotCom, "foodal.com".into()),
            (Website::FoodAndWineDotCom, "www.foodandwine.com".into()),
            (Website::FoodByMariaDotCom, "www.foodbymaria.com".into()),
            (Website::FoodieCrushDotCom, "www.foodiecrush.com".into()),
            (Website::FoodNetworkDotCoDotUk, "foodnetwork.co.uk".into()),
            (Website::FoodRepublicDotCom, "www.foodrepublic.com".into()),
            (Website::FoolProofLivingDotCom, "foolproofliving.com".into()),
            (
                Website::ForksOverKnivesDotCom,
                "www.forksoverknives.com".into(),
            ),
            (Website::ForkToSpoonDotCom, "forktospoon.com".into()),
            (Website::FrancescaKooktDotNl, "www.francescakookt.nl".into()),
            (
                Website::FranzoesischKochenDotDe,
                "www.franzoesischkochen.de".into(),
            ),
            (
                Website::FredriksfikaDotAllasDotSe,
                "fredriksfika.allas.se".into(),
            ),
            (Website::GastroPlantDotCom, "gastroplant.com".into()),
            (Website::GazoakleyChefDotCom, "www.gazoakleychef.com".into()),
            (Website::GesundAktivDotCom, "www.gesund-aktiv.com".into()),
            (
                Website::GialloZafferanoDotCom,
                "www.giallozafferano.com".into(),
            ),
            (Website::GimmeSomeOvenDotCom, "www.gimmesomeoven.com".into()),
            (Website::GloboDotCom, "receitas.globo.com".into()),
            (
                Website::GlutenFreeTablesDotCom,
                "glutenfreetables.com".into(),
            ),
            (Website::GodtDotNo, "www.godt.no".into()),
            (
                Website::GonnaWantSecondsDotCom,
                "www.gonnawantseconds.com".into(),
            ),
            (Website::GoodEatingsDotCom, "goodeatings.com".into()),
            (
                Website::GoodFoodDiscoveriesDotCom,
                "goodfooddiscoveries.com".into(),
            ),
            (
                Website::GoodHouseKeepingDotCom,
                "www.goodhousekeeping.com".into(),
            ),
            (Website::GoodToDotCom, "www.goodto.com".into()),
            (
                Website::GourmetTravellerDotComDotAu,
                "www.gourmettraveller.com.au".into(),
            ),
            (Website::GurkiDotNo, "gurki.no".into()),
            (Website::GrandFraisDotCom, "www.grandfrais.com".into()),
            (
                Website::GreatBritishChefsDotCom,
                "www.greatbritishchefs.com".into(),
            ),
            (Website::GreeneviDotCom, "greenevi.com".into()),
            (Website::GrimGrainsDotCom, "grimgrains.com".into()),
            (Website::GroupRecipesDotCom, "www.grouprecipes.com".into()),
            (
                Website::HalfBakedHarvestDotCom,
                "www.halfbakedharvest.com".into(),
            ),
            (Website::HandleTheHeatDotCom, "handletheheat.com".into()),
            (Website::HassanChefDotCom, "www.hassanchef.com".into()),
            (
                Website::HeadbangersKitchenDotCom,
                "headbangerskitchen.com".into(),
            ),
            (
                Website::HealthyLittleFoodiesDotCom,
                "www.healthylittlefoodies.com".into(),
            ),
            (Website::HeatherChristoDotCom, "heatherchristo.com".into()),
            (Website::HelloFreshDotCom, "www.hellofresh.com".into()),
            (Website::HomebrewAnswersDotCom, "homebrewanswers.com".into()),
            (Website::HomeChefDotCom, "www.homechef.com".into()),
            (Website::HostTheToastDotCom, "hostthetoast.com".into()),
            (Website::IcaDotSe, "www.ica.se".into()),
            (Website::ImWorthyDotCom, "im-worthy.com".into()),
            (Website::InBloomBakeryDotCom, "inbloombakery.com".into()),
            (
                Website::IndianHealthyRecipesDotCom,
                "www.indianhealthyrecipes.com".into(),
            ),
            (Website::InnitDotCom, "www.innit.com".into()),
            (
                Website::InsanelyGoodRecipesDotCom,
                "insanelygoodrecipes.com".into(),
            ),
            (Website::InspiralizedDotCom, "inspiralized.com".into()),
            (Website::InstantPotDotCom, "instantpot.com".into()),
            (Website::JamieOliverDotCom, "www.jamieoliver.com".into()),
            (Website::JaimysKitchenDotNl, "jaimyskitchen.nl".into()),
            (Website::JarofLemonsDotCom, "www.jaroflemons.com".into()),
            (
                Website::JimCooksFoodGoodDotCom,
                "jimcooksfoodgood.com".into(),
            ),
            (Website::JoCooksDotCom, "www.jocooks.com".into()),
            (Website::JoyFoodSunshineDotCom, "joyfoodsunshine.com".into()),
            (Website::JoyTheBakerDotCom, "joythebaker.com".into()),
            (
                Website::JulieGoodwinDotComDotAu,
                "juliegoodwin.com.au".into(),
            ),
            (Website::JumboDotCom, "www.jumbo.com".into()),
            (Website::JustATasteDotCom, "www.justataste.com".into()),
            (Website::JustBentoDotCom, "justbento.com".into()),
            (
                Website::JustOneCookBookDotCom,
                "www.justonecookbook.com".into(),
            ),
            (Website::KeepinItKindDotCom, "keepinitkind.com".into()),
            (Website::KennyMcGovernDotCom, "kennymcgovern.com".into()),
            (
                Website::KingArthurBakingDotCom,
                "www.kingarthurbaking.com".into(),
            ),
            (Website::KitchenAidDotComDotAu, "kitchenaid.com.au".into()),
            (
                Website::KitchenSanctuaryDotCom,
                "www.kitchensanctuary.com".into(),
            ),
            (
                Website::KitchenStoriesDotCom,
                "www.kitchenstories.com".into(),
            ),
            (Website::KochbarDotDe, "www.kochbar.de".into()),
            (Website::KochbucherDotCom, "kochbucher.com".into()),
            (Website::KoketDotSe, "www.koket.se".into()),
            (Website::KookjijDotNl, "www.kookjij.nl".into()),
            (Website::KptnCookDotCom, "mobile.kptncook.com".into()),
            (
                Website::KristinesKitchenBlogDotCom,
                "kristineskitchenblog.com".into(),
            ),
            (Website::KuchniaDomowaDotPl, "www.kuchnia-domowa.pl".into()),
            (Website::KuchynalidlaDotSk, "kuchynalidla.sk".into()),
            (Website::KwestiasmakuDotCom, "www.kwestiasmaku.com".into()),
            (Website::LahbcoDotCom, "www.lahbco.com".into()),
            (
                Website::LatelierDeRoxaneDotCom,
                "www.latelierderoxane.com".into(),
            ),
            (
                Website::LeanAndGreenRecipesDotNet,
                "leanandgreenrecipes.net".into(),
            ),
            (Website::LeckerDotDe, "www.lecker.de".into()),
            (
                Website::LeCremeDeLaCrumbDotCom,
                "www.lecremedelacrumb.com".into(),
            ),
            (
                Website::LekkerenSimpelDotCom,
                "www.lekkerensimpel.com".into(),
            ),
            (Website::LeukeReceptenDotNl, "www.leukerecepten.nl".into()),
            (
                Website::LifestyleOfAFoodieDotCom,
                "lifestyleofafoodie.com".into(),
            ),
            (Website::LidlDotNl, "recepten.lidl.nl".into()),
            (Website::LidlKochenDotDe, "www.lidl-kochen.de".into()),
            (
                Website::LithuanianInTheUsaDotCom,
                "lithuanianintheusa.com".into(),
            ),
            (Website::LittleSpiceJarDotCom, "littlespicejar.com".into()),
            (Website::LivelyTableDotCom, "livelytable.com".into()),
            (
                Website::LivingTheGreenLifeDotCom,
                "livingthegreenlife.com".into(),
            ),
            (Website::LoveAndLemonsDotCom, "www.loveandlemons.com".into()),
            (Website::LovingItVeganDotCom, "lovingitvegan.com".into()),
            (Website::MaangchiDotCom, "www.maangchi.com".into()),
            (Website::MadensVerdenDotdk, "madensverden.dk".into()),
            (Website::MadsvinDotCom, "madsvin.com".into()),
            (Website::MarmitonDotOrg, "www.marmiton.org".into()),
            (Website::MarthaStewartDotCom, "www.marthastewart.com".into()),
            (Website::MatpratDotNo, "www.matprat.no".into()),
            (Website::McCormickDotCom, "www.mccormick.com".into()),
            (Website::MeljoulwanDotCom, "meljoulwan.com".into()),
            (
                Website::MelsKitchenCafeDotCom,
                "www.melskitchencafe.com".into(),
            ),
            (
                Website::MexicanMadeMeatlessDotCom,
                "mexicanmademeatless.com".into(),
            ),
            (Website::MindmegetteDotHu, "www.mindmegette.hu".into()),
            (Website::MinimalistBakerDotCom, "minimalistbaker.com".into()),
            (Website::MinistryOfCurryDotCom, "ministryofcurry.com".into()),
            (Website::MisyaDotInfo, "www.misya.info".into()),
            (Website::ModernHoneyDotCom, "www.modernhoney.com".into()),
            (Website::MomonTimeoutDotCom, "www.momontimeout.com".into()),
            (Website::MomsDishDotCom, "momsdish.com".into()),
            (
                Website::MomsWithCrockpotsDotCom,
                "momswithcrockpots.com".into(),
            ),
            (Website::MotherThymeDotCom, "www.motherthyme.com".into()),
            (
                Website::MundoDeReceitasBimbyDotComDotPt,
                "www.mundodereceitasbimby.com.pt".into(),
            ),
            (
                Website::MyBakingAddictionDotCom,
                "www.mybakingaddiction.com".into(),
            ),
            (
                Website::MyJewishLearningDotCom,
                "www.myjewishlearning.com".into(),
            ),
            (Website::MyKitchen101DotCom, "mykitchen101.com".into()),
            (Website::MyKoreanKitchenDotCom, "mykoreankitchen.com".into()),
            (
                Website::MyGingerGarlicKitchenDotCom,
                "www.mygingergarlickitchen.com".into(),
            ),
            (Website::MyKitchen101enDotCom, "mykitchen101en.com".into()),
            (Website::MyPlateDotGov, "www.myplate.gov".into()),
            (Website::MyRecipesDotCom, "www.myrecipes.com".into()),
            (Website::NatashasKitchenDotCom, "natashaskitchen.com".into()),
            (Website::NigellaDotCom, "www.nigella.com".into()),
            (Website::NinjaTestKitchenDotEu, "ninjatestkitchen.eu".into()),
            (
                Website::NourishedByNutritionDotCom,
                "nourishedbynutrition.com".into(),
            ),
            (Website::NosaltyDotHu, "www.nosalty.hu".into()),
            (
                Website::NotEnoughCinnamonDotCom,
                "www.notenoughcinnamon.com".into(),
            ),
            (Website::NrkDotNo, "www.nrk.no".into()),
            (
                Website::Number2PencilDotCom,
                "www.number-2-pencil.com".into(),
            ),
            (Website::NutritionFactsDotOrg, "nutritionfacts.org".into()),
            (Website::NyTimesDotCom, "cooking.nytimes.com".into()),
            (Website::OhSheGlowsDotCom, "ohsheglows.com".into()),
            (Website::OkokoReceptenDotNl, "www.okokorecepten.nl".into()),
            (
                Website::OmnivoresCookbookDotCom,
                "omnivorescookbook.com".into(),
            ),
            (Website::OnceUponAChefDotCom, "www.onceuponachef.com".into()),
            (Website::OhMyVeggiesDotCom, "ohmyveggies.com".into()),
            (
                Website::OneSweetAppetiteDotCom,
                "onesweetappetite.com".into(),
            ),
            (Website::OwenHanDotCom, "www.owen-han.com".into()),
            (
                Website::PaleoRunningMommaDotCom,
                "www.paleorunningmomma.com".into(),
            ),
            (Website::PanelinhaDotComDotBr, "www.panelinha.com.br".into()),
            (Website::PaniniHappyDotCom, "paninihappy.com".into()),
            (Website::ParsleyAndParmDotCom, "parsleyandparm.com".into()),
            (
                Website::PersnicketyPlatesDotCom,
                "www.persnicketyplates.com".into(),
            ),
            (Website::PickupLimesDotCom, "www.pickuplimes.com".into()),
            (Website::PinchOfYumDotCom, "pinchofyum.com".into()),
            (Website::PinkOwlKitchenDotCom, "pinkowlkitchen.com".into()),
            (Website::PingoDoceDotPt, "www.pingodoce.pt".into()),
            (Website::PlatingPixelsDotCom, "www.platingpixels.com".into()),
            (Website::PlentyVeganDotCom, "plentyvegan.com".into()),
            (Website::PloetzBlogDotDe, "www.ploetzblog.de".into()),
            (
                Website::PlowingThroughLifeDotCom,
                "plowingthroughlife.com".into(),
            ),
            (Website::PopSugarDotCoDotUk, "www.popsugar.co.uk".into()),
            (Website::PotatoRollsDotGom, "potatorolls.com".into()),
            (
                Website::PracticalSelfRelianceDotCom,
                "practicalselfreliance.com".into(),
            ),
            (
                Website::PressureLuckCookingDotCom,
                "pressureluckcooking.com".into(),
            ),
            (
                Website::PrimalEdgeHealthDotCom,
                "www.primaledgehealth.com".into(),
            ),
            (Website::ProjectGezondDotNl, "www.projectgezond.nl".into()),
            (Website::PrzepisyDotPl, "www.przepisy.pl".into()),
            (Website::PurelyPopeDotCom, "purelypope.com".into()),
            (Website::PureWowDotCom, "www.purewow.com".into()),
            (Website::PurpleCarrotDotCom, "www.purplecarrot.com".into()),
            (Website::PuurgezondDotNl, "www.puurgezond.nl".into()),
            (Website::QuitoqueDotFr, "www.quitoque.fr".into()),
            (Website::RachlmansFieldDotCom, "rachlmansfield.com".into()),
            (Website::RadioFranceDotFr, "www.radiofrance.fr".into()),
            (
                Website::RainbowPlantLifeDotCom,
                "rainbowplantlife.com".into(),
            ),
            (Website::RealSimpleDotCom, "www.realsimple.com".into()),
            (
                Website::ReceitasNestleDotComDotBr,
                "www.receitasnestle.com.br".into(),
            ),
            (Website::RecettesDotQcDotCa, "www.recettes.qc.ca".into()),
            (Website::RecipeGirlDotCom, "www.recipegirl.com".into()),
            (Website::RecipeRunnerDotCom, "reciperunner.com".into()),
            (Website::RecipeTinEatsDotCom, "www.recipetineats.com".into()),
            (Website::RedditDotCom, "old.reddit.com".into()),
            (Website::RedhouseSpiceDotCom, "redhousespice.com".into()),
            (Website::ReisHungerDotDe, "www.reishunger.de".into()),
            (Website::RezeptWeltDotDe, "www.rezeptwelt.de".into()),
            (Website::RicettaDotIt, "ricetta.it".into()),
            (
                Website::RicettePerBimbyDotIt,
                "www.ricetteperbimby.it".into(),
            ),
            (Website::RobinasBellDotCom, "robinasbell.com".into()),
            (Website::RosannaPansinoDotCom, "rosannapansino.com".into()),
            (Website::RutgerbaktDotNl, "rutgerbakt.nl".into()),
            (
                Website::RecipeCommunityDotComDotAu,
                "www.recipecommunity.com.au".into(),
            ),
            (
                Website::SaboresaJinomotoDotComDotBr,
                "www.saboresajinomoto.com.br".into(),
            ),
            (
                Website::SallysBakingAddictionDotCom,
                "sallysbakingaddiction.com".into(),
            ),
            (Website::SallysBlogDotDe, "sallys-blog.de".into()),
            (
                Website::SaltAndLavenderDotCom,
                "www.saltandlavender.com".into(),
            ),
            (
                Website::SaltPepperSkilletDotCom,
                "saltpepperskillet.com".into(),
            ),
            (
                Website::SarahsVeganGuideDotCom,
                "sarahsveganguide.com".into(),
            ),
            (Website::SaveurDotCom, "www.saveur.com".into()),
            (
                Website::SavoryNothingsDotCom,
                "www.savorynothings.com".into(),
            ),
            (Website::SeriousEatsDotCom, "www.seriouseats.com".into()),
            (
                Website::SimpleVeganistaDotCom,
                "simple-veganista.com".into(),
            ),
            (Website::SimplyCookitDotCom, "www.simply-cookit.com".into()),
            (Website::SimplyQuinoaDotCom, "www.simplyquinoa.com".into()),
            (Website::SimplyRecipesDotCom, "www.simplyrecipes.com".into()),
            (Website::SimplyWhiskedDotCom, "www.simplywhisked.com".into()),
            (Website::SkinnyTasteDotCom, "www.skinnytaste.com".into()),
            (Website::SmittenKitchenDotCom, "smittenkitchen.com".into()),
            (Website::SoborsDotHu, "sobors.hu".into()),
            (
                Website::SouthernCastIronDotCom,
                "southerncastiron.com".into(),
            ),
            (
                Website::SouthernLivingDotCom,
                "www.southernliving.com".into(),
            ),
            (
                Website::SpendWithPenniesDotCom,
                "www.spendwithpennies.com".into(),
            ),
            (Website::SpiceboxTravelsDotCom, "spiceboxtravels.com".into()),
            (Website::StaySnatchedDotCom, "www.staysnatched.com".into()),
            (Website::SteamyKitchenDotCom, "steamykitchen.com".into()),
            (Website::StreetKitchenDotCo, "streetkitchen.co".into()),
            (Website::StrongrFastrDotCom, "www.strongrfastr.com".into()),
            (Website::SunBasketDotCom, "sunbasket.com".into()),
            (Website::SundPaabudgetDotdk, "sundpaabudget.dk".into()),
            (Website::SunsetDotCom, "www.sunset.com".into()),
            (Website::SweetcsDesignsDotCom, "sweetcsdesigns.com".into()),
            (
                Website::SweetPeasAndSaffronDotCom,
                "sweetpeasandsaffron.com".into(),
            ),
            (Website::TasteAtlasDotCom, "www.tasteatlas.com".into()),
            (Website::TasteOfHomeDotCom, "www.tasteofhome.com".into()),
            (
                Website::TastesBetterFromScratchDotCom,
                "tastesbetterfromscratch.com".into(),
            ),
            (
                Website::TastesOfLizzyTDotCom,
                "www.tastesoflizzyt.com".into(),
            ),
            (Website::TastyDotCo, "tasty.co".into()),
            (Website::TastyKitchenDotCom, "tastykitchen.com".into()),
            (Website::TescoDotCom, "realfood.tesco.com".into()),
            (Website::ThatVeganDadDotNet, "www.thatvegandad.net".into()),
            (
                Website::TheCleverCarrotDotCom,
                "www.theclevercarrot.com".into(),
            ),
            (
                Website::TheCookieRookieDotCom,
                "www.thecookierookie.com".into(),
            ),
            (Website::TheCookingGuyDotCom, "www.thecookingguy.com".into()),
            (Website::TheExpertGuidesDotCom, "theexpertguides.com".into()),
            (Website::TheFoodFlamingoDotCom, "thefoodflamingo.com".into()),
            (Website::TheGucchaDotCom, "www.theguccha.com".into()),
            (
                Website::TheHappyFoodieDotCoDotUk,
                "thehappyfoodie.co.uk".into(),
            ),
            (Website::TheHeartySoulDotCom, "theheartysoul.com".into()),
            (
                Website::TheKitchenCommunityDotOrg,
                "thekitchencommunity.org".into(),
            ),
            (
                Website::TheKitchenMagPieDotCom,
                "www.thekitchenmagpie.com".into(),
            ),
            (Website::TheKitchnDotCom, "www.thekitchn.com".into()),
            (
                Website::TheMagicalSlowCookerDotCom,
                "www.themagicalslowcooker.com".into(),
            ),
            (
                Website::TheNutritiousKitchenDotCo,
                "thenutritiouskitchen.co".into(),
            ),
            (Website::TheModernProperDotCom, "themodernproper.com".into()),
            (
                Website::ThePalatableLifeDotCom,
                "www.thepalatablelife.com".into(),
            ),
            (
                Website::ThePioneerWomanDotCom,
                "www.thepioneerwoman.com".into(),
            ),
            (Website::TheRecipeCriticDotCom, "therecipecritic.com".into()),
            (
                Website::TheSaltyMarshmallowDotCom,
                "thesaltymarshmallow.com".into(),
            ),
            (Website::TheSpruceEatsDotCom, "www.thespruceeats.com".into()),
            (
                Website::TheVintageMixerDotCom,
                "www.thevintagemixer.com".into(),
            ),
            (Website::TheWoksOfLifeDotCom, "thewoksoflife.com".into()),
            (Website::ThinliciousDotCom, "thinlicious.com".into()),
            (Website::TidyMomDotNet, "tidymom.net".into()),
            (
                Website::TimesOfIndiaDotCom,
                "recipes.timesofindia.com".into(),
            ),
            (Website::TineDotNo, "www.tine.no".into()),
            (
                Website::TudogostosoDotComDotBr,
                "www.tudogostoso.com.br".into(),
            ),
            (
                Website::TwoPeasAndTheirPodDotCom,
                "www.twopeasandtheirpod.com".into(),
            ),
            (Website::TwoSleeversDotCom, "twosleevers.com".into()),
            (
                Website::UitPaulinesKeukenDotNl,
                "uitpaulineskeuken.nl".into(),
            ),
            (Website::UnsophistiCookDotCom, "unsophisticook.com".into()),
            (Website::UsaPearsDotOrg, "usapears.org".into()),
            (Website::ValdemarsroDotdk, "www.valdemarsro.dk".into()),
            (Website::VanillaAndBeanDotCom, "vanillaandbean.com".into()),
            (Website::VeganPratiqueDotFr, "vegan-pratique.fr".into()),
            (Website::VegetarBloggenDotNo, "www.vegetarbloggen.no".into()),
            (Website::VegolosiDotIt, "www.vegolosi.it".into()),
            (
                Website::VegRecipesOfIndiaDotCom,
                "www.vegrecipesofindia.com".into(),
            ),
            (Website::WaitRoseDotCom, "www.waitrose.com".into()),
            (Website::WatchWhatUEatDotCom, "www.watchwhatueat.com".into()),
            (Website::WeAreNotMarthaDotCom, "wearenotmartha.com".into()),
            (
                Website::WeightWatchersDotCom,
                "www.weightwatchers.com".into(),
            ),
            (Website::WellPlatedDotCom, "www.wellplated.com".into()),
            (
                Website::WhatsGabyCookingDotCom,
                "whatsgabycooking.com".into(),
            ),
            (
                Website::WholeFoodsMarketDotCoDotUk,
                "www.wholefoodsmarket.co.uk".into(),
            ),
            (Website::WikibooksDotOrg, "en.wikibooks.org".into()),
            (Website::WikibooksDotOrgMobile, "en.m.wikibooks.org".into()),
            (
                Website::WomensWeeklyFoodDotComDotAu,
                "www.womensweeklyfood.com.au".into(),
            ),
            (Website::WoopDotCoDotNz, "woop.co.nz".into()),
            (Website::YeMekDotNet, "ye-mek.net".into()),
            (Website::YumeliseDotFr, "www.yumelise.fr".into()),
            (Website::ZeitDotDe, "www.zeit.de".into()),
            (Website::ZenbellyDotCom, "www.zenbelly.com".into()),
        ])
    })
}

fn websites_map_to_website() -> &'static HashMap<String, Website> {
    static INSTANCE: OnceLock<HashMap<String, Website>> = OnceLock::new();

    INSTANCE.get_or_init(|| {
        let mut map: HashMap<String, Website> = HashMap::new();
        websites_map_to_domain()
            .iter()
            .for_each(|(&website, domain)| {
                let _ = map.insert(domain.clone(), website);
            });
        map
    })
}
