use std::{collections::HashMap, fmt::Formatter, sync::OnceLock};

use reqwest::Url;

use super::{Error, Result};

/// Enumeration of all websites that can be scraped.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {
    O101cookbooksDotCom,
    O15gramsDotCom,
    O24kitchenDotNl,
    O750gDotCom,
    AbuelasCounterDotCom,
    ACoupleCooksDotCom,
    AddAPinchDotCom,
    AfghanKitchenRecipesDotCom,
    AFlavorJournalDotCom,
    AhDotNl,
    AkispetretzikisDotCom,
    AlexandraCooksDotCom,
    ALittleBitYummyDotCom,
    AllCladDotCom,
    AldiDotComDotAu,
    AllTheHealthyThingsDotCom,
    AllRecipesDotCom,
    AltonBrownDotCom,
    AmazingRibsDotCom,
    AmbitiousKitchenDotCom,
    AmericasTestKitchenDotCom,
    AngielaEatsDotCom,
    AniagotujeDotPl,
    AntilliaansEtenDotNl,
    ArchanasKitchenDotCom,
    ArgiroDotGr,
    ArlaDotSe,
    AtelierDesChefsDotFr,
    AverieCooksDotCom,
    AvocadoSkilletDotCom,
    BakingMischiefDotCom,
    BakelsDotComDotAu,
    BakingSenseDotCom,
    BarefootContessaDotCom,
    BareFeetInTheKitchenDotCom,
    BbcDotCoDotUk,
    BbcGoodFoodDotCom,
    BettyBossiDotCh,
    BettyCrockerDotCom,
    BeyondKimcheeDotCom,
    BiancazaPatkaDotCom,
    BigOvenDotCom,
    BlogDotGialloZafferanoDotIt,
    BlueApronDotCom,
    BlueJeanChefDotCom,
    BreadtopiaDotCom,
    BrianLagerstromDotCom,
    BriceletBaklavaDotCh,
    BritishBakelsDotCoDotUk,
    BodybuildingDotCom,
    BonAppetitDotCom,
    BongEatsDotCom,
    BottomlessGreensDotCom,
    BowlOfDeliciousDotCom,
    BudgetBytesDotCom,
    CafeDelitesDotCom,
    CanadaDotCa,
    CastironKetoDotCom,
    CdKitchenDotCom,
    CestMaFourneeDotCom,
    ChatelaineDotCom,
    ChefKochDotDe,
    ChefNiniDotCom,
    ChefSavvyDotCom,
    CheJorgeDotCom,
    ChetnamakanDotCoDotUk,
    ChineseCookingDemystifiedDotSubstackDotCom,
    ClaudiaAbrilComBr,
    ClosetCookingDotCom,
    ColruytDotBe,
    ComidinhasdoChefDotCom,
    CookEatShareDotCom,
    CookieAndKateDotCom,
    CookpadDotCom,
    CookTalkDotCom,
    CoopDotSe,
    CopykatDotCom,
    CostcoDotCom,
    CountryLivingDotCom,
    CreativeCanningDotCom,
    CucchiaioDotIt,
    CulyDotNl,
    CuisineAndTravelDotCom,
    CuisineazDotCom,
    CyberCookDotComDotBr,
    DamnDeliciousDotNet,
    DaringGourmetDotCom,
    DavidLebovitzDotCom,
    DelishDotCom,
    DherbsDotCom,
    DinnerAtTheZooDotCom,
    DinnerThenDessertDotCom,
    DishDotCoDotNz,
    DitchTheCarbsDotCom,
    DomesticateMeDotCom,
    DonnaHayDotComDotAu,
    DownshiftologyDotCom,
    DrDotdk,
    DreenaburtonDotCom,
    DrinkoteketDotSe,
    EatingBirdFoodDotCom,
    EatingWellDotCom,
    EatLiveRunDotCom,
    EatSmarterDotCom,
    EatWell101DotCom,
    EatWhatTonightDotCom,
    ElaveganDotCom,
    ElephantasticVeganDotCom,
    EmmikochteinfachDotDe,
    EntertainingWithBethDotCom,
    EpicuriousDotCom,
    ErrensKitchenDotCom,
    EtenvaneefkeDotNl,
    ExpressenDotSe,
    EvolvingTableDotCom,
    FamilyFoodOnTheTableDotCom,
    FarmhouseDeliveryDotCom,
    FarmhouseOnBooneDotCom,
    FattoInCasaDaBenedettaDotIt,
    FeastingAtHomeDotCom,
    FelixDotKitchen,
    FifteenSpatulasDotCom,
    FineDiningLoversDotCom,
    FindingTimeForCookingDotCom,
    FitMenCookDotCom,
    FitsLowCookerQueenDotCom,
    FoodDotCom,
    Food52DotCom,
    FoodalDotCom,
    FoodAndWineDotCom,
    FoodByMariaDotCom,
    FoodieCrushDotCom,
    FoodNetworkDotCoDotUk,
    FoodRepublicDotCom,
    FoolProofLivingDotCom,
    ForksOverKnivesDotCom,
    ForkToSpoonDotCom,
    FrancescaKooktDotNl,
    FranzoesischKochenDotDe,
    FredriksfikaDotAllasDotSe,
    GastroPlantDotCom,
    GazoakleyChefDotCom,
    GesundAktivDotCom,
    GialloZafferanoDotCom,
    GimmeSomeOvenDotCom,
    GloboDotCom,
    GlutenFreeTablesDotCom,
    GodtDotNo,
    GonnaWantSecondsDotCom,
    GoodEatingsDotCom,
    GoodFoodDiscoveriesDotCom,
    GoodHouseKeepingDotCom,
    GoodToDotCom,
    GourmetTravellerDotComDotAu,
    GurkiDotNo,
    GrandFraisDotCom,
    GreatBritishChefsDotCom,
    GreeneviDotCom,
    GrimGrainsDotCom,
    GroupRecipesDotCom,
    HalfBakedHarvestDotCom,
    HandleTheHeatDotCom,
    HassanChefDotCom,
    HeadbangersKitchenDotCom,
    HealthyLittleFoodiesDotCom,
    HeatherChristoDotCom,
    HelloFreshDotCom,
    HomebrewAnswersDotCom,
    HomeChefDotCom,
    HostTheToastDotCom,
    IcaDotSe,
    ImWorthyDotCom,
    InBloomBakeryDotCom,
    IndianHealthyRecipesDotCom,
    InnitDotCom,
    InsanelyGoodRecipesDotCom,
    InspiralizedDotCom,
    InstantPotDotCom,
    JamieOliverDotCom,
    JaimysKitchenDotNl,
    JarofLemonsDotCom,
    JimCooksFoodGoodDotCom,
    JoCooksDotCom,
    JoyFoodSunshineDotCom,
    JoyTheBakerDotCom,
    JulieGoodwinDotComDotAu,
    JumboDotCom,
    JustATasteDotCom,
    JustBentoDotCom,
    JustOneCookBookDotCom,
    KeepinItKindDotCom,
    KennyMcGovernDotCom,
    KingArthurBakingDotCom,
    KitchenAidDotComDotAu,
    KitchenSanctuaryDotCom,
    KitchenStoriesDotCom,
    KochbarDotDe,
    KochbucherDotCom,
    KoketDotSe,
    KookjijDotNl,
    KptnCookDotCom,
    KristinesKitchenBlogDotCom,
    KuchniaDomowaDotPl,
    KuchynalidlaDotSk,
    KwestiasmakuDotCom,
    LahbcoDotCom,
    LatelierDeRoxaneDotCom,
    LeanAndGreenRecipesDotNet,
    LeckerDotDe,
    LeCremeDeLaCrumbDotCom,
    LekkerenSimpelDotCom,
    LeukeReceptenDotNl,
    LifestyleOfAFoodieDotCom,
    LidlDotNl,
    LidlKochenDotDe,
    LithuanianInTheUsaDotCom,
    LittleSpiceJarDotCom,
    LivelyTableDotCom,
    LivingTheGreenLifeDotCom,
    LoveAndLemonsDotCom,
    LovingItVeganDotCom,
    MaangchiDotCom,
    MadensVerdenDotdk,
    MadsvinDotCom,
    MarmitonDotOrg,
    MarthaStewartDotCom,
    MatpratDotNo,
    McCormickDotCom,
    MeljoulwanDotCom,
    MelsKitchenCafeDotCom,
    MexicanMadeMeatlessDotCom,
    MindmegetteDotHu,
    MinimalistBakerDotCom,
    MinistryOfCurryDotCom,
    MisyaDotInfo,
    ModernHoneyDotCom,
    MomonTimeoutDotCom,
    MomsDishDotCom,
    MomsWithCrockpotsDotCom,
    MotherThymeDotCom,
    MoulinexDotFr,
    MundoDeReceitasBimbyDotComDotPt,
    MyBakingAddictionDotCom,
    MyJewishLearningDotCom,
    MyKitchen101DotCom,
    MyKoreanKitchenDotCom,
    MyGingerGarlicKitchenDotCom,
    MyKitchen101enDotCom,
    MyPlateDotGov,
    MyRecipesDotCom,
    NatashasKitchenDotCom,
    NigellaDotCom,
    NinjaTestKitchenDotEu,
    NourishedByNutritionDotCom,
    NosaltyDotHu,
    NotEnoughCinnamonDotCom,
    NrkDotNo,
    Number2PencilDotCom,
    NutritionFactsDotOrg,
    NyTimesDotCom,
    OhSheGlowsDotCom,
    OkokoReceptenDotNl,
    OmnivoresCookbookDotCom,
    OnceUponAChefDotCom,
    OhMyVeggiesDotCom,
    OneSweetAppetiteDotCom,
    OwenHanDotCom,
    PaleoRunningMommaDotCom,
    PanelinhaDotComDotBr,
    PaniniHappyDotCom,
    ParsleyAndParmDotCom,
    PersnicketyPlatesDotCom,
    PickupLimesDotCom,
    PinchOfYumDotCom,
    PinkOwlKitchenDotCom,
    PingoDoceDotPt,
    PlatingPixelsDotCom,
    PlentyVeganDotCom,
    PloetzBlogDotDe,
    PlowingThroughLifeDotCom,
    PopSugarDotCoDotUk,
    PotatoRollsDotGom,
    PracticalSelfRelianceDotCom,
    PressureLuckCookingDotCom,
    PrimalEdgeHealthDotCom,
    ProjectGezondDotNl,
    PrzepisyDotPl,
    PurelyPopeDotCom,
    PureWowDotCom,
    PurpleCarrotDotCom,
    PuurgezondDotNl,
    QuitoqueDotFr,
    RachlmansFieldDotCom,
    RadioFranceDotFr,
    RainbowPlantLifeDotCom,
    RealSimpleDotCom,
    ReceitasNestleDotComDotBr,
    RecettesDotQcDotCa,
    RecipeGirlDotCom,
    RecipeRunnerDotCom,
    RecipeTinEatsDotCom,
    RedditDotCom,
    RedhouseSpiceDotCom,
    ReisHungerDotDe,
    RezeptWeltDotDe,
    RicettaDotIt,
    RicettePerBimbyDotIt,
    RobinasBellDotCom,
    RosannaPansinoDotCom,
    RutgerbaktDotNl,
    RecipeCommunityDotComDotAu,
    SaboresaJinomotoDotComDotBr,
    SallysBakingAddictionDotCom,
    SallysBlogDotDe,
    SaltAndLavenderDotCom,
    SaltPepperSkilletDotCom,
    SarahsVeganGuideDotCom,
    SaveurDotCom,
    SavoryNothingsDotCom,
    SeriousEatsDotCom,
    SimpleVeganistaDotCom,
    SimplyCookitDotCom,
    SimplyQuinoaDotCom,
    SimplyRecipesDotCom,
    SimplyWhiskedDotCom,
    SkinnyTasteDotCom,
    SmittenKitchenDotCom,
    SoborsDotHu,
    SouthernCastIronDotCom,
    SouthernLivingDotCom,
    SpendWithPenniesDotCom,
    SpiceboxTravelsDotCom,
    StaySnatchedDotCom,
    SteamyKitchenDotCom,
    StreetKitchenDotCo,
    StrongrFastrDotCom,
    SunBasketDotCom,
    SundPaabudgetDotdk,
    SunsetDotCom,
    SweetcsDesignsDotCom,
    SweetPeasAndSaffronDotCom,
    TasteAtlasDotCom,
    TasteOfHomeDotCom,
    TastesBetterFromScratchDotCom,
    TastesOfLizzyTDotCom,
    TastyDotCo,
    TastyKitchenDotCom,
    TescoDotCom,
    ThatVeganDadDotNet,
    TheCleverCarrotDotCom,
    TheCookieRookieDotCom,
    TheCookingGuyDotCom,
    TheExpertGuidesDotCom,
    TheFoodFlamingoDotCom,
    TheGucchaDotCom,
    TheHappyFoodieDotCoDotUk,
    TheHeartySoulDotCom,
    TheKitchenCommunityDotOrg,
    TheKitchenMagPieDotCom,
    TheKitchnDotCom,
    TheMagicalSlowCookerDotCom,
    TheNutritiousKitchenDotCo,
    TheModernProperDotCom,
    ThePalatableLifeDotCom,
    ThePioneerWomanDotCom,
    TheRecipeCriticDotCom,
    TheSaltyMarshmallowDotCom,
    TheSpruceEatsDotCom,
    TheVintageMixerDotCom,
    TheWoksOfLifeDotCom,
    ThinliciousDotCom,
    TidyMomDotNet,
    TimesOfIndiaDotCom,
    TineDotNo,
    TudogostosoDotComDotBr,
    TwoPeasAndTheirPodDotCom,
    TwoSleeversDotCom,
    UitPaulinesKeukenDotNl,
    UnsophistiCookDotCom,
    UsaPearsDotOrg,
    ValdemarsroDotdk,
    VanillaAndBeanDotCom,
    VeganPratiqueDotFr,
    VegetarBloggenDotNo,
    VegolosiDotIt,
    VegRecipesOfIndiaDotCom,
    WaitRoseDotCom,
    WatchWhatUEatDotCom,
    WeAreNotMarthaDotCom,
    WeightWatchersDotCom,
    WellPlatedDotCom,
    WhatsGabyCookingDotCom,
    WholeFoodsMarketDotCoDotUk,
    WikibooksDotOrg,
    WikibooksDotOrgMobile,
    WomensWeeklyFoodDotComDotAu,
    WoopDotCoDotNz,
    YeMekDotNet,
    YumeliseDotFr,
    ZeitDotDe,
    ZenbellyDotCom,
}

impl Website {
    /// Creates a `Website` instance from a given URL.
    pub fn from(url: &str) -> Result<Self> {
        let url = Url::parse(url).map_err(|err| Error::Parse(err.to_string()))?;
        let domain = url.domain().ok_or(Error::UnknownWebsite)?;

        websites_map_to_website()
            .get(domain)
            .copied()
            .ok_or(Error::UnknownWebsite)
    }
}

impl std::fmt::Display for Website {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match websites_map_to_domain().get_key_value(self) {
            Some((_, url)) => write!(f, "{url}"),
            None => write!(f, "URL not found"),
        }
    }
}

fn websites_map_to_domain() -> &'static HashMap<Website, String> {
    static INSTANCE: OnceLock<HashMap<Website, String>> = OnceLock::new();

    INSTANCE.get_or_init(|| {
        HashMap::from([
            (
                Website::O101cookbooksDotCom,
                String::from("www.101cookbooks.com"),
            ),
            (Website::O15gramsDotCom, String::from("15gram.be")),
            (Website::O24kitchenDotNl, String::from("www.24kitchen.nl")),
            (Website::O750gDotCom, String::from("www.750g.com")),
            (
                Website::AbuelasCounterDotCom,
                String::from("abuelascounter.com"),
            ),
            (
                Website::ACoupleCooksDotCom,
                String::from("www.acouplecooks.com"),
            ),
            (Website::AddAPinchDotCom, String::from("addapinch.com")),
            (
                Website::AfghanKitchenRecipesDotCom,
                String::from("www.afghankitchenrecipes.com"),
            ),
            (
                Website::AFlavorJournalDotCom,
                String::from("aflavorjournal.com"),
            ),
            (Website::AhDotNl, String::from("www.ah.nl")),
            (
                Website::AkispetretzikisDotCom,
                String::from("akispetretzikis.com"),
            ),
            (
                Website::AlexandraCooksDotCom,
                String::from("alexandracooks.com"),
            ),
            (
                Website::ALittleBitYummyDotCom,
                String::from("alittlebityummy.com"),
            ),
            (Website::AllCladDotCom, String::from("www.all-clad.com")),
            (Website::AldiDotComDotAu, String::from("www.aldi.com.au")),
            (
                Website::AllTheHealthyThingsDotCom,
                String::from("allthehealthythings.com"),
            ),
            (
                Website::AllRecipesDotCom,
                String::from("www.allrecipes.com"),
            ),
            (Website::AltonBrownDotCom, String::from("altonbrown.com")),
            (Website::AmazingRibsDotCom, String::from("amazingribs.com")),
            (
                Website::AmbitiousKitchenDotCom,
                String::from("www.ambitiouskitchen.com"),
            ),
            (
                Website::AmericasTestKitchenDotCom,
                String::from("www.americastestkitchen.com"),
            ),
            (
                Website::AngielaEatsDotCom,
                String::from("www.angielaeats.com"),
            ),
            (Website::AniagotujeDotPl, String::from("aniagotuje.pl")),
            (
                Website::AntilliaansEtenDotNl,
                String::from("www.antilliaans-eten.nl"),
            ),
            (
                Website::ArchanasKitchenDotCom,
                String::from("www.archanaskitchen.com"),
            ),
            (Website::ArgiroDotGr, String::from("www.argiro.gr")),
            (Website::ArlaDotSe, String::from("www.arla.se")),
            (
                Website::AtelierDesChefsDotFr,
                String::from("www.atelierdeschefs.fr"),
            ),
            (
                Website::AverieCooksDotCom,
                String::from("www.averiecooks.com"),
            ),
            (
                Website::AvocadoSkilletDotCom,
                String::from("avocadoskillet.com"),
            ),
            (
                Website::BakingMischiefDotCom,
                String::from("bakingmischief.com"),
            ),
            (
                Website::BakelsDotComDotAu,
                String::from("www.bakels.com.au"),
            ),
            (
                Website::BakingSenseDotCom,
                String::from("www.baking-sense.com"),
            ),
            (
                Website::BarefootContessaDotCom,
                String::from("barefootcontessa.com"),
            ),
            (
                Website::BareFeetInTheKitchenDotCom,
                String::from("barefeetinthekitchen.com"),
            ),
            (Website::BbcDotCoDotUk, String::from("www.bbc.co.uk")),
            (
                Website::BbcGoodFoodDotCom,
                String::from("www.bbcgoodfood.com"),
            ),
            (Website::BettyBossiDotCh, String::from("www.bettybossi.ch")),
            (
                Website::BettyCrockerDotCom,
                String::from("www.bettycrocker.com"),
            ),
            (
                Website::BeyondKimcheeDotCom,
                String::from("www.beyondkimchee.com"),
            ),
            (
                Website::BiancazaPatkaDotCom,
                String::from("biancazapatka.com"),
            ),
            (Website::BigOvenDotCom, String::from("www.bigoven.com")),
            (
                Website::BlogDotGialloZafferanoDotIt,
                String::from("blog.giallozafferano.it"),
            ),
            (Website::BlueApronDotCom, String::from("www.blueapron.com")),
            (
                Website::BlueJeanChefDotCom,
                String::from("bluejeanchef.com"),
            ),
            (Website::BreadtopiaDotCom, String::from("breadtopia.com")),
            (
                Website::BrianLagerstromDotCom,
                String::from("www.brianlagerstrom.com"),
            ),
            (
                Website::BriceletBaklavaDotCh,
                String::from("briceletbaklava.ch"),
            ),
            (
                Website::BritishBakelsDotCoDotUk,
                String::from("www.britishbakels.co.uk"),
            ),
            (
                Website::BodybuildingDotCom,
                String::from("www.bodybuilding.com"),
            ),
            (
                Website::BonAppetitDotCom,
                String::from("www.bonappetit.com"),
            ),
            (Website::BongEatsDotCom, String::from("www.bongeats.com")),
            (
                Website::BottomlessGreensDotCom,
                String::from("bottomlessgreens.com"),
            ),
            (
                Website::BowlOfDeliciousDotCom,
                String::from("www.bowlofdelicious.com"),
            ),
            (
                Website::BudgetBytesDotCom,
                String::from("www.budgetbytes.com"),
            ),
            (Website::CafeDelitesDotCom, String::from("cafedelites.com")),
            (Website::CanadaDotCa, String::from("food-guide.canada.ca")),
            (
                Website::CastironKetoDotCom,
                String::from("www.castironketo.net"),
            ),
            (Website::CdKitchenDotCom, String::from("www.cdkitchen.com")),
            (
                Website::CestMaFourneeDotCom,
                String::from("www.cestmafournee.com"),
            ),
            (Website::ChatelaineDotCom, String::from("chatelaine.com")),
            (Website::ChefKochDotDe, String::from("www.chefkoch.de")),
            (Website::ChefNiniDotCom, String::from("www.chefnini.com")),
            (Website::ChefSavvyDotCom, String::from("chefsavvy.com")),
            (Website::CheJorgeDotCom, String::from("chejorge.com")),
            (
                Website::ChetnamakanDotCoDotUk,
                String::from("chetnamakan.co.uk"),
            ),
            (
                Website::ChineseCookingDemystifiedDotSubstackDotCom,
                String::from("chinesecookingdemystified.substack.com"),
            ),
            (
                Website::ClaudiaAbrilComBr,
                String::from("claudia.abril.com.br"),
            ),
            (
                Website::ClosetCookingDotCom,
                String::from("www.closetcooking.com"),
            ),
            (Website::ColruytDotBe, String::from("www.colruyt.be")),
            (
                Website::ComidinhasdoChefDotCom,
                String::from("comidinhasdochef.com"),
            ),
            (
                Website::CookEatShareDotCom,
                String::from("cookeatshare.com"),
            ),
            (
                Website::CookieAndKateDotCom,
                String::from("cookieandkate.com"),
            ),
            (Website::CookpadDotCom, String::from("cookpad.com")),
            (Website::CookTalkDotCom, String::from("cook-talk.com")),
            (Website::CoopDotSe, String::from("www.coop.se")),
            (Website::CopykatDotCom, String::from("copykat.com")),
            (Website::CostcoDotCom, String::from("www.costco.com")),
            (
                Website::CountryLivingDotCom,
                String::from("www.countryliving.com"),
            ),
            (
                Website::CreativeCanningDotCom,
                String::from("creativecanning.com"),
            ),
            (Website::CucchiaioDotIt, String::from("www.cucchiaio.it")),
            (Website::CulyDotNl, String::from("www.culy.nl")),
            (
                Website::CuisineAndTravelDotCom,
                String::from("www.cuisineandtravel.com"),
            ),
            (Website::CuisineazDotCom, String::from("www.cuisineaz.com")),
            (
                Website::CyberCookDotComDotBr,
                String::from("cybercook.com.br"),
            ),
            (
                Website::DamnDeliciousDotNet,
                String::from("damndelicious.net"),
            ),
            (
                Website::DaringGourmetDotCom,
                String::from("www.daringgourmet.com"),
            ),
            (
                Website::DavidLebovitzDotCom,
                String::from("www.davidlebovitz.com"),
            ),
            (Website::DelishDotCom, String::from("www.delish.com")),
            (Website::DherbsDotCom, String::from("www.dherbs.com")),
            (
                Website::DinnerAtTheZooDotCom,
                String::from("www.dinneratthezoo.com"),
            ),
            (
                Website::DinnerThenDessertDotCom,
                String::from("dinnerthendessert.com"),
            ),
            (Website::DishDotCoDotNz, String::from("dish.co.nz")),
            (
                Website::DitchTheCarbsDotCom,
                String::from("www.ditchthecarbs.com"),
            ),
            (
                Website::DomesticateMeDotCom,
                String::from("domesticate-me.com"),
            ),
            (
                Website::DonnaHayDotComDotAu,
                String::from("www.donnahay.com.au"),
            ),
            (
                Website::DownshiftologyDotCom,
                String::from("downshiftology.com"),
            ),
            (Website::DrDotdk, String::from("www.dr.dk")),
            (
                Website::DreenaburtonDotCom,
                String::from("dreenaburton.com"),
            ),
            (Website::DrinkoteketDotSe, String::from("drinkoteket.se")),
            (
                Website::EatingBirdFoodDotCom,
                String::from("www.eatingbirdfood.com"),
            ),
            (
                Website::EatingWellDotCom,
                String::from("www.eatingwell.com"),
            ),
            (
                Website::EatLiveRunDotCom,
                String::from("www.eatliverun.com"),
            ),
            (Website::EatSmarterDotCom, String::from("eatsmarter.com")),
            (
                Website::EatWell101DotCom,
                String::from("www.eatwell101.com"),
            ),
            (
                Website::EatWhatTonightDotCom,
                String::from("eatwhattonight.com"),
            ),
            (Website::ElaveganDotCom, String::from("elavegan.com")),
            (
                Website::ElephantasticVeganDotCom,
                String::from("www.elephantasticvegan.com"),
            ),
            (
                Website::EmmikochteinfachDotDe,
                String::from("emmikochteinfach.de"),
            ),
            (
                Website::EntertainingWithBethDotCom,
                String::from("entertainingwithbeth.com"),
            ),
            (
                Website::EpicuriousDotCom,
                String::from("www.epicurious.com"),
            ),
            (
                Website::ErrensKitchenDotCom,
                String::from("www.errenskitchen.com"),
            ),
            (
                Website::EtenvaneefkeDotNl,
                String::from("www.etenvaneefke.nl"),
            ),
            (
                Website::ExpressenDotSe,
                String::from("alltommat.expressen.se"),
            ),
            (
                Website::EvolvingTableDotCom,
                String::from("www.evolvingtable.com"),
            ),
            (
                Website::FamilyFoodOnTheTableDotCom,
                String::from("www.familyfoodonthetable.com"),
            ),
            (
                Website::FarmhouseDeliveryDotCom,
                String::from("recipes.farmhousedelivery.com"),
            ),
            (
                Website::FarmhouseOnBooneDotCom,
                String::from("www.farmhouseonboone.com"),
            ),
            (
                Website::FattoInCasaDaBenedettaDotIt,
                String::from("www.fattoincasadabenedetta.it"),
            ),
            (
                Website::FeastingAtHomeDotCom,
                String::from("www.feastingathome.com"),
            ),
            (Website::FelixDotKitchen, String::from("felix.kitchen")),
            (
                Website::FifteenSpatulasDotCom,
                String::from("www.fifteenspatulas.com"),
            ),
            (
                Website::FineDiningLoversDotCom,
                String::from("www.finedininglovers.com"),
            ),
            (
                Website::FindingTimeForCookingDotCom,
                String::from("findingtimeforcooking.com"),
            ),
            (Website::FitMenCookDotCom, String::from("fitmencook.com")),
            (
                Website::FitsLowCookerQueenDotCom,
                String::from("fitslowcookerqueen.com"),
            ),
            (Website::FoodDotCom, String::from("www.food.com")),
            (Website::Food52DotCom, String::from("food52.com")),
            (Website::FoodalDotCom, String::from("foodal.com")),
            (
                Website::FoodAndWineDotCom,
                String::from("www.foodandwine.com"),
            ),
            (
                Website::FoodByMariaDotCom,
                String::from("www.foodbymaria.com"),
            ),
            (
                Website::FoodieCrushDotCom,
                String::from("www.foodiecrush.com"),
            ),
            (
                Website::FoodNetworkDotCoDotUk,
                String::from("foodnetwork.co.uk"),
            ),
            (
                Website::FoodRepublicDotCom,
                String::from("www.foodrepublic.com"),
            ),
            (
                Website::FoolProofLivingDotCom,
                String::from("foolproofliving.com"),
            ),
            (
                Website::ForksOverKnivesDotCom,
                String::from("www.forksoverknives.com"),
            ),
            (Website::ForkToSpoonDotCom, String::from("forktospoon.com")),
            (
                Website::FrancescaKooktDotNl,
                String::from("www.francescakookt.nl"),
            ),
            (
                Website::FranzoesischKochenDotDe,
                String::from("www.franzoesischkochen.de"),
            ),
            (
                Website::FredriksfikaDotAllasDotSe,
                String::from("fredriksfika.allas.se"),
            ),
            (Website::GastroPlantDotCom, String::from("gastroplant.com")),
            (
                Website::GazoakleyChefDotCom,
                String::from("www.gazoakleychef.com"),
            ),
            (
                Website::GesundAktivDotCom,
                String::from("www.gesund-aktiv.com"),
            ),
            (
                Website::GialloZafferanoDotCom,
                String::from("www.giallozafferano.com"),
            ),
            (
                Website::GimmeSomeOvenDotCom,
                String::from("www.gimmesomeoven.com"),
            ),
            (Website::GloboDotCom, String::from("receitas.globo.com")),
            (
                Website::GlutenFreeTablesDotCom,
                String::from("glutenfreetables.com"),
            ),
            (Website::GodtDotNo, String::from("www.godt.no")),
            (
                Website::GonnaWantSecondsDotCom,
                String::from("www.gonnawantseconds.com"),
            ),
            (Website::GoodEatingsDotCom, String::from("goodeatings.com")),
            (
                Website::GoodFoodDiscoveriesDotCom,
                String::from("goodfooddiscoveries.com"),
            ),
            (
                Website::GoodHouseKeepingDotCom,
                String::from("www.goodhousekeeping.com"),
            ),
            (Website::GoodToDotCom, String::from("www.goodto.com")),
            (
                Website::GourmetTravellerDotComDotAu,
                String::from("www.gourmettraveller.com.au"),
            ),
            (Website::GurkiDotNo, String::from("gurki.no")),
            (
                Website::GrandFraisDotCom,
                String::from("www.grandfrais.com"),
            ),
            (
                Website::GreatBritishChefsDotCom,
                String::from("www.greatbritishchefs.com"),
            ),
            (Website::GreeneviDotCom, String::from("greenevi.com")),
            (Website::GrimGrainsDotCom, String::from("grimgrains.com")),
            (
                Website::GroupRecipesDotCom,
                String::from("www.grouprecipes.com"),
            ),
            (
                Website::HalfBakedHarvestDotCom,
                String::from("www.halfbakedharvest.com"),
            ),
            (
                Website::HandleTheHeatDotCom,
                String::from("handletheheat.com"),
            ),
            (
                Website::HassanChefDotCom,
                String::from("www.hassanchef.com"),
            ),
            (
                Website::HeadbangersKitchenDotCom,
                String::from("headbangerskitchen.com"),
            ),
            (
                Website::HealthyLittleFoodiesDotCom,
                String::from("www.healthylittlefoodies.com"),
            ),
            (
                Website::HeatherChristoDotCom,
                String::from("heatherchristo.com"),
            ),
            (
                Website::HelloFreshDotCom,
                String::from("www.hellofresh.com"),
            ),
            (
                Website::HomebrewAnswersDotCom,
                String::from("homebrewanswers.com"),
            ),
            (Website::HomeChefDotCom, String::from("www.homechef.com")),
            (
                Website::HostTheToastDotCom,
                String::from("hostthetoast.com"),
            ),
            (Website::IcaDotSe, String::from("www.ica.se")),
            (Website::ImWorthyDotCom, String::from("im-worthy.com")),
            (
                Website::InBloomBakeryDotCom,
                String::from("inbloombakery.com"),
            ),
            (
                Website::IndianHealthyRecipesDotCom,
                String::from("www.indianhealthyrecipes.com"),
            ),
            (Website::InnitDotCom, String::from("www.innit.com")),
            (
                Website::InsanelyGoodRecipesDotCom,
                String::from("insanelygoodrecipes.com"),
            ),
            (
                Website::InspiralizedDotCom,
                String::from("inspiralized.com"),
            ),
            (Website::InstantPotDotCom, String::from("instantpot.com")),
            (
                Website::JamieOliverDotCom,
                String::from("www.jamieoliver.com"),
            ),
            (
                Website::JaimysKitchenDotNl,
                String::from("jaimyskitchen.nl"),
            ),
            (
                Website::JarofLemonsDotCom,
                String::from("www.jaroflemons.com"),
            ),
            (
                Website::JimCooksFoodGoodDotCom,
                String::from("jimcooksfoodgood.com"),
            ),
            (Website::JoCooksDotCom, String::from("www.jocooks.com")),
            (
                Website::JoyFoodSunshineDotCom,
                String::from("joyfoodsunshine.com"),
            ),
            (Website::JoyTheBakerDotCom, String::from("joythebaker.com")),
            (
                Website::JulieGoodwinDotComDotAu,
                String::from("juliegoodwin.com.au"),
            ),
            (Website::JumboDotCom, String::from("www.jumbo.com")),
            (
                Website::JustATasteDotCom,
                String::from("www.justataste.com"),
            ),
            (Website::JustBentoDotCom, String::from("justbento.com")),
            (
                Website::JustOneCookBookDotCom,
                String::from("www.justonecookbook.com"),
            ),
            (
                Website::KeepinItKindDotCom,
                String::from("keepinitkind.com"),
            ),
            (
                Website::KennyMcGovernDotCom,
                String::from("kennymcgovern.com"),
            ),
            (
                Website::KingArthurBakingDotCom,
                String::from("www.kingarthurbaking.com"),
            ),
            (
                Website::KitchenAidDotComDotAu,
                String::from("kitchenaid.com.au"),
            ),
            (
                Website::KitchenSanctuaryDotCom,
                String::from("www.kitchensanctuary.com"),
            ),
            (
                Website::KitchenStoriesDotCom,
                String::from("www.kitchenstories.com"),
            ),
            (Website::KochbarDotDe, String::from("www.kochbar.de")),
            (Website::KochbucherDotCom, String::from("kochbucher.com")),
            (Website::KoketDotSe, String::from("www.koket.se")),
            (Website::KookjijDotNl, String::from("www.kookjij.nl")),
            (Website::KptnCookDotCom, String::from("mobile.kptncook.com")),
            (
                Website::KristinesKitchenBlogDotCom,
                String::from("kristineskitchenblog.com"),
            ),
            (
                Website::KuchniaDomowaDotPl,
                String::from("www.kuchnia-domowa.pl"),
            ),
            (Website::KuchynalidlaDotSk, String::from("kuchynalidla.sk")),
            (
                Website::KwestiasmakuDotCom,
                String::from("www.kwestiasmaku.com"),
            ),
            (Website::LahbcoDotCom, String::from("www.lahbco.com")),
            (
                Website::LatelierDeRoxaneDotCom,
                String::from("www.latelierderoxane.com"),
            ),
            (
                Website::LeanAndGreenRecipesDotNet,
                String::from("leanandgreenrecipes.net"),
            ),
            (Website::LeckerDotDe, String::from("www.lecker.de")),
            (
                Website::LeCremeDeLaCrumbDotCom,
                String::from("www.lecremedelacrumb.com"),
            ),
            (
                Website::LekkerenSimpelDotCom,
                String::from("www.lekkerensimpel.com"),
            ),
            (
                Website::LeukeReceptenDotNl,
                String::from("www.leukerecepten.nl"),
            ),
            (
                Website::LifestyleOfAFoodieDotCom,
                String::from("lifestyleofafoodie.com"),
            ),
            (Website::LidlDotNl, String::from("recepten.lidl.nl")),
            (Website::LidlKochenDotDe, String::from("www.lidl-kochen.de")),
            (
                Website::LithuanianInTheUsaDotCom,
                String::from("lithuanianintheusa.com"),
            ),
            (
                Website::LittleSpiceJarDotCom,
                String::from("littlespicejar.com"),
            ),
            (Website::LivelyTableDotCom, String::from("livelytable.com")),
            (
                Website::LivingTheGreenLifeDotCom,
                String::from("livingthegreenlife.com"),
            ),
            (
                Website::LoveAndLemonsDotCom,
                String::from("www.loveandlemons.com"),
            ),
            (
                Website::LovingItVeganDotCom,
                String::from("lovingitvegan.com"),
            ),
            (Website::MaangchiDotCom, String::from("www.maangchi.com")),
            (Website::MadensVerdenDotdk, String::from("madensverden.dk")),
            (Website::MadsvinDotCom, String::from("madsvin.com")),
            (Website::MarmitonDotOrg, String::from("www.marmiton.org")),
            (
                Website::MarthaStewartDotCom,
                String::from("www.marthastewart.com"),
            ),
            (Website::MatpratDotNo, String::from("www.matprat.no")),
            (Website::McCormickDotCom, String::from("www.mccormick.com")),
            (Website::MeljoulwanDotCom, String::from("meljoulwan.com")),
            (
                Website::MelsKitchenCafeDotCom,
                String::from("www.melskitchencafe.com"),
            ),
            (
                Website::MexicanMadeMeatlessDotCom,
                String::from("mexicanmademeatless.com"),
            ),
            (
                Website::MindmegetteDotHu,
                String::from("www.mindmegette.hu"),
            ),
            (
                Website::MinimalistBakerDotCom,
                String::from("minimalistbaker.com"),
            ),
            (
                Website::MinistryOfCurryDotCom,
                String::from("ministryofcurry.com"),
            ),
            (Website::MisyaDotInfo, String::from("www.misya.info")),
            (
                Website::ModernHoneyDotCom,
                String::from("www.modernhoney.com"),
            ),
            (
                Website::MomonTimeoutDotCom,
                String::from("www.momontimeout.com"),
            ),
            (Website::MomsDishDotCom, String::from("momsdish.com")),
            (
                Website::MomsWithCrockpotsDotCom,
                String::from("momswithcrockpots.com"),
            ),
            (
                Website::MotherThymeDotCom,
                String::from("www.motherthyme.com"),
            ),
            (
                Website::MundoDeReceitasBimbyDotComDotPt,
                String::from("www.mundodereceitasbimby.com.pt"),
            ),
            (
                Website::MyBakingAddictionDotCom,
                String::from("www.mybakingaddiction.com"),
            ),
            (
                Website::MyJewishLearningDotCom,
                String::from("www.myjewishlearning.com"),
            ),
            (
                Website::MyKitchen101DotCom,
                String::from("mykitchen101.com"),
            ),
            (
                Website::MyKoreanKitchenDotCom,
                String::from("mykoreankitchen.com"),
            ),
            (
                Website::MyGingerGarlicKitchenDotCom,
                String::from("www.mygingergarlickitchen.com"),
            ),
            (
                Website::MyKitchen101enDotCom,
                String::from("mykitchen101en.com"),
            ),
            (Website::MyPlateDotGov, String::from("www.myplate.gov")),
            (Website::MyRecipesDotCom, String::from("www.myrecipes.com")),
            (
                Website::NatashasKitchenDotCom,
                String::from("natashaskitchen.com"),
            ),
            (Website::NigellaDotCom, String::from("www.nigella.com")),
            (
                Website::NinjaTestKitchenDotEu,
                String::from("ninjatestkitchen.eu"),
            ),
            (
                Website::NourishedByNutritionDotCom,
                String::from("nourishedbynutrition.com"),
            ),
            (Website::NosaltyDotHu, String::from("www.nosalty.hu")),
            (
                Website::NotEnoughCinnamonDotCom,
                String::from("www.notenoughcinnamon.com"),
            ),
            (Website::NrkDotNo, String::from("www.nrk.no")),
            (
                Website::Number2PencilDotCom,
                String::from("www.number-2-pencil.com"),
            ),
            (
                Website::NutritionFactsDotOrg,
                String::from("nutritionfacts.org"),
            ),
            (Website::NyTimesDotCom, String::from("cooking.nytimes.com")),
            (Website::OhSheGlowsDotCom, String::from("ohsheglows.com")),
            (
                Website::OkokoReceptenDotNl,
                String::from("www.okokorecepten.nl"),
            ),
            (
                Website::OmnivoresCookbookDotCom,
                String::from("omnivorescookbook.com"),
            ),
            (
                Website::OnceUponAChefDotCom,
                String::from("www.onceuponachef.com"),
            ),
            (Website::OhMyVeggiesDotCom, String::from("ohmyveggies.com")),
            (
                Website::OneSweetAppetiteDotCom,
                String::from("onesweetappetite.com"),
            ),
            (Website::OwenHanDotCom, String::from("www.owen-han.com")),
            (
                Website::PaleoRunningMommaDotCom,
                String::from("www.paleorunningmomma.com"),
            ),
            (
                Website::PanelinhaDotComDotBr,
                String::from("www.panelinha.com.br"),
            ),
            (Website::PaniniHappyDotCom, String::from("paninihappy.com")),
            (
                Website::ParsleyAndParmDotCom,
                String::from("parsleyandparm.com"),
            ),
            (
                Website::PersnicketyPlatesDotCom,
                String::from("www.persnicketyplates.com"),
            ),
            (
                Website::PickupLimesDotCom,
                String::from("www.pickuplimes.com"),
            ),
            (Website::PinchOfYumDotCom, String::from("pinchofyum.com")),
            (
                Website::PinkOwlKitchenDotCom,
                String::from("pinkowlkitchen.com"),
            ),
            (Website::PingoDoceDotPt, String::from("www.pingodoce.pt")),
            (
                Website::PlatingPixelsDotCom,
                String::from("www.platingpixels.com"),
            ),
            (Website::PlentyVeganDotCom, String::from("plentyvegan.com")),
            (Website::PloetzBlogDotDe, String::from("www.ploetzblog.de")),
            (
                Website::PlowingThroughLifeDotCom,
                String::from("plowingthroughlife.com"),
            ),
            (
                Website::PopSugarDotCoDotUk,
                String::from("www.popsugar.co.uk"),
            ),
            (Website::PotatoRollsDotGom, String::from("potatorolls.com")),
            (
                Website::PracticalSelfRelianceDotCom,
                String::from("practicalselfreliance.com"),
            ),
            (
                Website::PressureLuckCookingDotCom,
                String::from("pressureluckcooking.com"),
            ),
            (
                Website::PrimalEdgeHealthDotCom,
                String::from("www.primaledgehealth.com"),
            ),
            (
                Website::ProjectGezondDotNl,
                String::from("www.projectgezond.nl"),
            ),
            (Website::PrzepisyDotPl, String::from("www.przepisy.pl")),
            (Website::PurelyPopeDotCom, String::from("purelypope.com")),
            (Website::PureWowDotCom, String::from("www.purewow.com")),
            (
                Website::PurpleCarrotDotCom,
                String::from("www.purplecarrot.com"),
            ),
            (Website::PuurgezondDotNl, String::from("www.puurgezond.nl")),
            (Website::QuitoqueDotFr, String::from("www.quitoque.fr")),
            (
                Website::RachlmansFieldDotCom,
                String::from("rachlmansfield.com"),
            ),
            (
                Website::RadioFranceDotFr,
                String::from("www.radiofrance.fr"),
            ),
            (
                Website::RainbowPlantLifeDotCom,
                String::from("rainbowplantlife.com"),
            ),
            (
                Website::RealSimpleDotCom,
                String::from("www.realsimple.com"),
            ),
            (
                Website::ReceitasNestleDotComDotBr,
                String::from("www.receitasnestle.com.br"),
            ),
            (
                Website::RecettesDotQcDotCa,
                String::from("www.recettes.qc.ca"),
            ),
            (
                Website::RecipeGirlDotCom,
                String::from("www.recipegirl.com"),
            ),
            (
                Website::RecipeRunnerDotCom,
                String::from("reciperunner.com"),
            ),
            (
                Website::RecipeTinEatsDotCom,
                String::from("www.recipetineats.com"),
            ),
            (Website::RedditDotCom, String::from("old.reddit.com")),
            (
                Website::RedhouseSpiceDotCom,
                String::from("redhousespice.com"),
            ),
            (Website::ReisHungerDotDe, String::from("www.reishunger.de")),
            (Website::RezeptWeltDotDe, String::from("www.rezeptwelt.de")),
            (Website::RicettaDotIt, String::from("ricetta.it")),
            (
                Website::RicettePerBimbyDotIt,
                String::from("www.ricetteperbimby.it"),
            ),
            (Website::RobinasBellDotCom, String::from("robinasbell.com")),
            (
                Website::RosannaPansinoDotCom,
                String::from("rosannapansino.com"),
            ),
            (Website::RutgerbaktDotNl, String::from("rutgerbakt.nl")),
            (
                Website::RecipeCommunityDotComDotAu,
                String::from("www.recipecommunity.com.au"),
            ),
            (
                Website::SaboresaJinomotoDotComDotBr,
                String::from("www.saboresajinomoto.com.br"),
            ),
            (
                Website::SallysBakingAddictionDotCom,
                String::from("sallysbakingaddiction.com"),
            ),
            (Website::SallysBlogDotDe, String::from("sallys-blog.de")),
            (
                Website::SaltAndLavenderDotCom,
                String::from("www.saltandlavender.com"),
            ),
            (
                Website::SaltPepperSkilletDotCom,
                String::from("saltpepperskillet.com"),
            ),
            (
                Website::SarahsVeganGuideDotCom,
                String::from("sarahsveganguide.com"),
            ),
            (Website::SaveurDotCom, String::from("www.saveur.com")),
            (
                Website::SavoryNothingsDotCom,
                String::from("www.savorynothings.com"),
            ),
            (
                Website::SeriousEatsDotCom,
                String::from("www.seriouseats.com"),
            ),
            (
                Website::SimpleVeganistaDotCom,
                String::from("simple-veganista.com"),
            ),
            (
                Website::SimplyCookitDotCom,
                String::from("www.simply-cookit.com"),
            ),
            (
                Website::SimplyQuinoaDotCom,
                String::from("www.simplyquinoa.com"),
            ),
            (
                Website::SimplyRecipesDotCom,
                String::from("www.simplyrecipes.com"),
            ),
            (
                Website::SimplyWhiskedDotCom,
                String::from("www.simplywhisked.com"),
            ),
            (
                Website::SkinnyTasteDotCom,
                String::from("www.skinnytaste.com"),
            ),
            (
                Website::SmittenKitchenDotCom,
                String::from("smittenkitchen.com"),
            ),
            (Website::SoborsDotHu, String::from("sobors.hu")),
            (
                Website::SouthernCastIronDotCom,
                String::from("southerncastiron.com"),
            ),
            (
                Website::SouthernLivingDotCom,
                String::from("www.southernliving.com"),
            ),
            (
                Website::SpendWithPenniesDotCom,
                String::from("www.spendwithpennies.com"),
            ),
            (
                Website::SpiceboxTravelsDotCom,
                String::from("spiceboxtravels.com"),
            ),
            (
                Website::StaySnatchedDotCom,
                String::from("www.staysnatched.com"),
            ),
            (
                Website::SteamyKitchenDotCom,
                String::from("steamykitchen.com"),
            ),
            (
                Website::StreetKitchenDotCo,
                String::from("streetkitchen.co"),
            ),
            (
                Website::StrongrFastrDotCom,
                String::from("www.strongrfastr.com"),
            ),
            (Website::SunBasketDotCom, String::from("sunbasket.com")),
            (
                Website::SundPaabudgetDotdk,
                String::from("sundpaabudget.dk"),
            ),
            (Website::SunsetDotCom, String::from("www.sunset.com")),
            (
                Website::SweetcsDesignsDotCom,
                String::from("sweetcsdesigns.com"),
            ),
            (
                Website::SweetPeasAndSaffronDotCom,
                String::from("sweetpeasandsaffron.com"),
            ),
            (
                Website::TasteAtlasDotCom,
                String::from("www.tasteatlas.com"),
            ),
            (
                Website::TasteOfHomeDotCom,
                String::from("www.tasteofhome.com"),
            ),
            (
                Website::TastesBetterFromScratchDotCom,
                String::from("tastesbetterfromscratch.com"),
            ),
            (
                Website::TastesOfLizzyTDotCom,
                String::from("www.tastesoflizzyt.com"),
            ),
            (Website::TastyDotCo, String::from("tasty.co")),
            (
                Website::TastyKitchenDotCom,
                String::from("tastykitchen.com"),
            ),
            (Website::TescoDotCom, String::from("realfood.tesco.com")),
            (
                Website::ThatVeganDadDotNet,
                String::from("www.thatvegandad.net"),
            ),
            (
                Website::TheCleverCarrotDotCom,
                String::from("www.theclevercarrot.com"),
            ),
            (
                Website::TheCookieRookieDotCom,
                String::from("www.thecookierookie.com"),
            ),
            (
                Website::TheCookingGuyDotCom,
                String::from("www.thecookingguy.com"),
            ),
            (
                Website::TheExpertGuidesDotCom,
                String::from("theexpertguides.com"),
            ),
            (
                Website::TheFoodFlamingoDotCom,
                String::from("thefoodflamingo.com"),
            ),
            (Website::TheGucchaDotCom, String::from("www.theguccha.com")),
            (
                Website::TheHappyFoodieDotCoDotUk,
                String::from("thehappyfoodie.co.uk"),
            ),
            (
                Website::TheHeartySoulDotCom,
                String::from("theheartysoul.com"),
            ),
            (
                Website::TheKitchenCommunityDotOrg,
                String::from("thekitchencommunity.org"),
            ),
            (
                Website::TheKitchenMagPieDotCom,
                String::from("www.thekitchenmagpie.com"),
            ),
            (Website::TheKitchnDotCom, String::from("www.thekitchn.com")),
            (
                Website::TheMagicalSlowCookerDotCom,
                String::from("www.themagicalslowcooker.com"),
            ),
            (
                Website::TheNutritiousKitchenDotCo,
                String::from("thenutritiouskitchen.co"),
            ),
            (
                Website::TheModernProperDotCom,
                String::from("themodernproper.com"),
            ),
            (
                Website::ThePalatableLifeDotCom,
                String::from("www.thepalatablelife.com"),
            ),
            (
                Website::ThePioneerWomanDotCom,
                String::from("www.thepioneerwoman.com"),
            ),
            (
                Website::TheRecipeCriticDotCom,
                String::from("therecipecritic.com"),
            ),
            (
                Website::TheSaltyMarshmallowDotCom,
                String::from("thesaltymarshmallow.com"),
            ),
            (
                Website::TheSpruceEatsDotCom,
                String::from("www.thespruceeats.com"),
            ),
            (
                Website::TheVintageMixerDotCom,
                String::from("www.thevintagemixer.com"),
            ),
            (
                Website::TheWoksOfLifeDotCom,
                String::from("thewoksoflife.com"),
            ),
            (Website::ThinliciousDotCom, String::from("thinlicious.com")),
            (Website::TidyMomDotNet, String::from("tidymom.net")),
            (
                Website::TimesOfIndiaDotCom,
                String::from("recipes.timesofindia.com"),
            ),
            (Website::TineDotNo, String::from("www.tine.no")),
            (
                Website::TudogostosoDotComDotBr,
                String::from("www.tudogostoso.com.br"),
            ),
            (
                Website::TwoPeasAndTheirPodDotCom,
                String::from("www.twopeasandtheirpod.com"),
            ),
            (Website::TwoSleeversDotCom, String::from("twosleevers.com")),
            (
                Website::UitPaulinesKeukenDotNl,
                String::from("uitpaulineskeuken.nl"),
            ),
            (
                Website::UnsophistiCookDotCom,
                String::from("unsophisticook.com"),
            ),
            (Website::UsaPearsDotOrg, String::from("usapears.org")),
            (
                Website::ValdemarsroDotdk,
                String::from("www.valdemarsro.dk"),
            ),
            (
                Website::VanillaAndBeanDotCom,
                String::from("vanillaandbean.com"),
            ),
            (
                Website::VeganPratiqueDotFr,
                String::from("vegan-pratique.fr"),
            ),
            (
                Website::VegetarBloggenDotNo,
                String::from("www.vegetarbloggen.no"),
            ),
            (Website::VegolosiDotIt, String::from("www.vegolosi.it")),
            (
                Website::VegRecipesOfIndiaDotCom,
                String::from("www.vegrecipesofindia.com"),
            ),
            (Website::WaitRoseDotCom, String::from("www.waitrose.com")),
            (
                Website::WatchWhatUEatDotCom,
                String::from("www.watchwhatueat.com"),
            ),
            (
                Website::WeAreNotMarthaDotCom,
                String::from("wearenotmartha.com"),
            ),
            (
                Website::WeightWatchersDotCom,
                String::from("www.weightwatchers.com"),
            ),
            (
                Website::WellPlatedDotCom,
                String::from("www.wellplated.com"),
            ),
            (
                Website::WhatsGabyCookingDotCom,
                String::from("whatsgabycooking.com"),
            ),
            (
                Website::WholeFoodsMarketDotCoDotUk,
                String::from("www.wholefoodsmarket.co.uk"),
            ),
            (Website::WikibooksDotOrg, String::from("en.wikibooks.org")),
            (
                Website::WikibooksDotOrgMobile,
                String::from("en.m.wikibooks.org"),
            ),
            (
                Website::WomensWeeklyFoodDotComDotAu,
                String::from("www.womensweeklyfood.com.au"),
            ),
            (Website::WoopDotCoDotNz, String::from("woop.co.nz")),
            (Website::YeMekDotNet, String::from("ye-mek.net")),
            (Website::YumeliseDotFr, String::from("www.yumelise.fr")),
            (Website::ZeitDotDe, String::from("www.zeit.de")),
            (Website::ZenbellyDotCom, String::from("www.zenbelly.com")),
        ])
    })
}

fn websites_map_to_website() -> &'static HashMap<String, Website> {
    static INSTANCE: OnceLock<HashMap<String, Website>> = OnceLock::new();

    INSTANCE.get_or_init(|| {
        let mut map: HashMap<String, Website> = HashMap::new();
        websites_map_to_domain()
            .iter()
            .for_each(|(&website, domain)| {
                let _ = map.insert(domain.clone(), website);
            });
        map
    })
}
