DROP TRIGGER IF EXISTS trig_cookbooks_ad ON cookbooks;
DROP TRIGGER IF EXISTS trig_cookbooks_ai ON cookbooks;
DROP TRIGGER IF EXISTS trig_cookbook_recipes_ad ON cookbook_recipes;
DROP TRIGGER IF EXISTS trig_cookbook_recipes_ai ON cookbook_recipes;
DROP TRIGGER IF EXISTS trig_app_update_check_auo ON app;
DROP TRIGGER IF EXISTS trig_user_recipe_ad ON user_recipe;
DROP TRIGGER IF EXISTS trig_user_recipe_ai ON user_recipe;
DROP TRIGGER IF EXISTS trig_times_au ON times;
DROP TRIGGER IF EXISTS trig_recipes_au ON recipes;
DROP TRIGGER IF EXISTS trig_users_ai ON users;

DROP FUNCTION IF EXISTS trig_cookbooks_ad_func;
DROP FUNCTION IF EXISTS trig_cookbooks_ai_func;
DROP FUNCTION IF EXISTS trig_cookbook_recipes_ad_func;
DROP FUNCTION IF EXISTS trig_cookbook_recipes_ai_func;
DROP FUNCTION IF EXISTS trig_app_update_check_auo_func;
DROP FUNCTION IF EXISTS trig_user_recipe_ad_func;
DROP FUNCTION IF EXISTS trig_user_recipe_ai_func;
DROP FUNCTION IF EXISTS trig_times_au_func;
DROP FUNCTION IF EXISTS trig_recipes_au_func;
DROP FUNCTION IF EXISTS trig_users_ai_func;

DROP TABLE IF EXISTS video_recipe;
DROP TABLE IF EXISTS user_recipe;
DROP TABLE IF EXISTS user_category;
DROP TABLE IF EXISTS tool_recipe;
DROP TABLE IF EXISTS time_recipe;
DROP TABLE IF EXISTS share_recipes;
DROP TABLE IF EXISTS share_cookbooks;
DROP TABLE IF EXISTS keyword_recipe;
DROP TABLE IF EXISTS instruction_recipe;
DROP TABLE IF EXISTS ingredient_recipe;
DROP TABLE IF EXISTS cuisine_recipe;
DROP TABLE IF EXISTS cookbook_recipes;
DROP TABLE IF EXISTS category_recipe;
DROP TABLE IF EXISTS cookbooks;
DROP TABLE IF EXISTS report_logs;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS report_types;
DROP TABLE IF EXISTS tools;
DROP TABLE IF EXISTS times;
DROP TABLE IF EXISTS additional_images_recipe;
DROP TABLE IF EXISTS nutrition;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS cuisines;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS instructions;
DROP TABLE IF EXISTS keywords;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS counts;
DROP TABLE IF EXISTS auth_tokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS websites;
DROP TABLE IF EXISTS measurement_systems;
DROP TABLE IF EXISTS app;
