DROP TRIGGER IF EXISTS trig_cookbooks_ad ON cookbooks;
DROP TRIGGER IF EXISTS trig_cookbooks_ai ON cookbooks;
DROP TRIGGER IF EXISTS trig_cookbooks_recipes_ad ON cookbooks_recipes;
DROP TRIGGER IF EXISTS trig_cookbooks_recipes_ai ON cookbooks_recipes;
DROP TRIGGER IF EXISTS trig_app_update_check_auo ON app;
DROP TRIGGER IF EXISTS trig_users_recipes_ad ON users_recipes;
DROP TRIGGER IF EXISTS trig_users_recipes_ai ON users_recipes;
DROP TRIGGER IF EXISTS trig_times_au ON times;
DROP TRIGGER IF EXISTS trig_recipes_au ON recipes;
DROP TRIGGER IF EXISTS trig_users_ai ON users;

DROP FUNCTION IF EXISTS trig_cookbooks_ad_func;
DROP FUNCTION IF EXISTS trig_cookbooks_ai_func;
DROP FUNCTION IF EXISTS trig_cookbooks_recipes_ad_func;
DROP FUNCTION IF EXISTS trig_cookbooks_recipes_ai_func;
DROP FUNCTION IF EXISTS trig_app_update_check_auo_func;
DROP FUNCTION IF EXISTS trig_users_recipes_ad_func;
DROP FUNCTION IF EXISTS trig_users_recipes_ai_func;
DROP FUNCTION IF EXISTS trig_times_au_func;
DROP FUNCTION IF EXISTS trig_recipes_au_func;
DROP FUNCTION IF EXISTS trig_users_ai_func;

DROP TABLE IF EXISTS videos_recipes;
DROP TABLE IF EXISTS users_recipes;
DROP TABLE IF EXISTS users_categories;
DROP TABLE IF EXISTS tools_recipes;
DROP TABLE IF EXISTS times_recipes;
DROP TABLE IF EXISTS shares_recipes;
DROP TABLE IF EXISTS shares_cookbooks;
DROP TABLE IF EXISTS keywords_recipes;
DROP TABLE IF EXISTS instructions_recipes;
DROP TABLE IF EXISTS ingredients_recipes;
DROP TABLE IF EXISTS cuisines_recipes;
DROP TABLE IF EXISTS cookbooks_recipes;
DROP TABLE IF EXISTS categories_recipes;
DROP TABLE IF EXISTS cookbooks;
DROP TABLE IF EXISTS reports_logs;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS report_types;
DROP TABLE IF EXISTS tools;
DROP TABLE IF EXISTS times;
DROP TABLE IF EXISTS additional_images_recipe;
DROP TABLE IF EXISTS nutrition;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS cuisines;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS instructions;
DROP TABLE IF EXISTS keywords;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS counts;
DROP TABLE IF EXISTS auth_tokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS websites;
DROP TABLE IF EXISTS measurement_systems;
DROP TABLE IF EXISTS app;
