services:
  recipya-app:
    container_name: recipya
    restart: unless-stopped
    image: reaper99/recipya-rs:nightly
    env_file: ./.env
    ports:
      - "8078:8078"
    volumes:
      - recipya-data:/home/recipya/.local/share/Recipya
    depends_on:
      recipya-db:
        condition: service_healthy

  recipya-db:
    container_name: recipya-rs-db
    restart: unless-stopped
    image: reaper99/recipya-rs-db:nightly
    environment:
      POSTGRES_DB: recipya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - recipya-rs-db:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  recipya-rs-db:
  recipya-data:
