// This file is auto-generated by build.rs
// Do not edit manually - changes will be overwritten.
// Generated from data/websites.csv (8 websites)

// Holds the details of a website.
pub struct WebsiteMetadata<'a> {
    pub host: &'a str,
    pub url: &'a str,
    pub cuisine: Option<&'a str>,
}

impl<'a> WebsiteMetadata<'a> {
    fn new(host: &'a str, url: &'a str, cuisine: Option<&'a str>) -> Self {
        Self {
            host,
            url,
            cuisine,
        }
    }
}

/// Enumeration of all supported recipe websites.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {
	AllRecipes,
	ZaatarAndZaytoun,
	ZabihaHalal,
	ZagLeft,
	ZardyPlants,
	Zarskitchen,
	Zeezest,
	Zenbelly,
}

impl Website {
    /// Returns the domain name of the website.
    pub fn domain(&self) -> &'static str {
        match self {
            Self::AllRecipes => "allrecipes.com",
            Self::ZaatarAndZaytoun => "zaatarandzaytoun.com",
            Self::ZabihaHalal => "zabihahalal.com",
            Self::ZagLeft => "zagleft.com",
            Self::ZardyPlants => "zardyplants.com",
            Self::Zarskitchen => "zarskitchen.com",
            Self::Zeezest => "zeezest.com",
            Self::Zenbelly => "zenbelly.com",
        }
    }

    /// Creates a `Website` instance from a domain string.
    /// Strips "www." prefix automatically.
    pub fn from_domain(domain: &str) -> Option<Self> {
        match domain.trim_start_matches("www.") {
            "allrecipes.com" => Some(Self::AllRecipes),
            "zaatarandzaytoun.com" => Some(Self::ZaatarAndZaytoun),
            "zabihahalal.com" => Some(Self::ZabihaHalal),
            "zagleft.com" => Some(Self::ZagLeft),
            "zardyplants.com" => Some(Self::ZardyPlants),
            "zarskitchen.com" => Some(Self::Zarskitchen),
            "zeezest.com" => Some(Self::Zeezest),
            "zenbelly.com" => Some(Self::Zenbelly),
            _ => None,
        }
    }

    /// Returns test URLs for this website (used in unit tests).
    pub fn test_urls(&self) -> Vec<&'static str> {
        match self {
            Self::AllRecipes => vec!["https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/"],
            Self::ZaatarAndZaytoun => vec!["https://zaatarandzaytoun.com/sardines/"],
            Self::ZabihaHalal => vec!["https://zabihahalal.com/recipes/bbq-chicken-pizza/"],
            Self::ZagLeft => vec!["https://zagleft.com/banana-oat-pecan-muffins/"],
            Self::ZardyPlants => vec!["https://zardyplants.com/recipes/vegan-tom-kha-soup-thai-inspired/"],
            Self::Zarskitchen => vec!["https://zarskitchen.com/wild-garlic-pesto/"],
            Self::Zeezest => vec!["https://zeezest.com/recipes/watch-multigrain-onion-dosa-with-chutney-recipe-by-zee-zest-1302"],
            Self::Zenbelly => vec!["https://www.zenbelly.com/crispy-chickpeas/"],
        }
    }

    /// Returns an iterator over all website variants.
    pub fn all<'a>() -> Vec<WebsiteMetadata<'a>> {
        vec![
			WebsiteMetadata::new("Allrecipes", "https://https://www.allrecipes.com/", None),
			WebsiteMetadata::new("Zaatar & Zaytoun", "https://https://zaatarandzaytoun.com/recipe-index/", Some("lebanese")),
			WebsiteMetadata::new("Zabiha Halal", "https://https://zabihahalal.com/recipes/", None),
			WebsiteMetadata::new("Zagleft", "https://https://zagleft.com/recipe-list/", None),
			WebsiteMetadata::new("ZardyPlants", "https://https://zardyplants.com", Some("vegetarian")),
			WebsiteMetadata::new("Zars Kitchen", "https://https://zarskitchen.com", None),
			WebsiteMetadata::new("ZZest", "https://https://zeezest.com/recipes/", None),
			WebsiteMetadata::new("Zen Belly", "https://https://www.zenbelly.com/recipes/", None)
        ]
    }
}
    