// This file is auto-generated by build.rs
// Do not edit manually - changes will be overwritten.
// Generated from data/websites.csv (14 websites)

// Holds the details of a website.
pub struct WebsiteMetadata<'a> {
    pub host: &'a str,
    pub url: &'a str,
    pub cuisine: Option<&'a str>,
}

impl<'a> WebsiteMetadata<'a> {
    fn new(host: &'a str, url: &'a str, cuisine: Option<&'a str>) -> Self {
        Self {
            host,
            url,
            cuisine,
        }
    }
}

/// Enumeration of all supported recipe websites.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {
	AllRecipes,
	ZaatarAndZaytoun,
	ZabihaHalal,
	ZagLeft,
	ZardyPlants,
	Zarskitchen,
	Zeezest,
	Zenbelly,
	ZenHealth,
	ZenKimchi,
	ZestfulKitchen,
	ZestSouthIndianKitchen,
	ZhangCatherine,
	ZiaHatchChileCompany,
}

impl Website {
    /// Returns the domain name of the website.
    pub fn domain(&self) -> &'static str {
        match self {
            Self::AllRecipes => "allrecipes.com",
            Self::ZaatarAndZaytoun => "zaatarandzaytoun.com",
            Self::ZabihaHalal => "zabihahalal.com",
            Self::ZagLeft => "zagleft.com",
            Self::ZardyPlants => "zardyplants.com",
            Self::Zarskitchen => "zarskitchen.com",
            Self::Zeezest => "zeezest.com",
            Self::Zenbelly => "zenbelly.com",
            Self::ZenHealth => "zenhealth.net",
            Self::ZenKimchi => "zenkimchi.com",
            Self::ZestfulKitchen => "zestfulkitchen.com",
            Self::ZestSouthIndianKitchen => "zestysouthindiankitchen.com",
            Self::ZhangCatherine => "zhangcatherine.com",
            Self::ZiaHatchChileCompany => "ziahatchchileco.com",
        }
    }

    /// Creates a `Website` instance from a domain string.
    /// Strips "www." prefix automatically.
    pub fn from_domain(domain: &str) -> Option<Self> {
        match domain.trim_start_matches("www.") {
            "allrecipes.com" => Some(Self::AllRecipes),
            "zaatarandzaytoun.com" => Some(Self::ZaatarAndZaytoun),
            "zabihahalal.com" => Some(Self::ZabihaHalal),
            "zagleft.com" => Some(Self::ZagLeft),
            "zardyplants.com" => Some(Self::ZardyPlants),
            "zarskitchen.com" => Some(Self::Zarskitchen),
            "zeezest.com" => Some(Self::Zeezest),
            "zenbelly.com" => Some(Self::Zenbelly),
            "zenhealth.net" => Some(Self::ZenHealth),
            "zenkimchi.com" => Some(Self::ZenKimchi),
            "zestfulkitchen.com" => Some(Self::ZestfulKitchen),
            "zestysouthindiankitchen.com" => Some(Self::ZestSouthIndianKitchen),
            "zhangcatherine.com" => Some(Self::ZhangCatherine),
            "ziahatchchileco.com" => Some(Self::ZiaHatchChileCompany),
            _ => None,
        }
    }

    /// Returns test URLs for this website (used in unit tests).
    pub fn test_urls(&self) -> Vec<&'static str> {
        match self {
            Self::AllRecipes => vec!["https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/"],
            Self::ZaatarAndZaytoun => vec!["https://zaatarandzaytoun.com/sardines/"],
            Self::ZabihaHalal => vec!["https://zabihahalal.com/recipes/bbq-chicken-pizza/"],
            Self::ZagLeft => vec!["https://zagleft.com/banana-oat-pecan-muffins/"],
            Self::ZardyPlants => vec!["https://zardyplants.com/recipes/vegan-tom-kha-soup-thai-inspired/"],
            Self::Zarskitchen => vec!["https://zarskitchen.com/wild-garlic-pesto/"],
            Self::Zeezest => vec!["https://zeezest.com/recipes/watch-multigrain-onion-dosa-with-chutney-recipe-by-zee-zest-1302"],
            Self::Zenbelly => vec!["https://www.zenbelly.com/crispy-chickpeas/"],
            Self::ZenHealth => vec!["https://zenhealth.net/lemongrass-tea-recipe/"],
            Self::ZenKimchi => vec!["https://zenkimchi.com/recipes/modern-korean/korean-style-arrabbiata-sauce/"],
            Self::ZestfulKitchen => vec!["https://zestfulkitchen.com/smash-burger-recipe/"],
            Self::ZestSouthIndianKitchen => vec!["https://zestysouthindiankitchen.com/spicy-baked-zucchini-chips/"],
            Self::ZhangCatherine => vec!["https://zhangcatherine.com/pistachio-macarons/"],
            Self::ZiaHatchChileCompany => vec!["https://ziahatchchileco.com/blogs/recipes/hatch-green-chile-baked-spaghetti"],
        }
    }

    /// Returns an iterator over all website variants.
    pub fn all<'a>() -> Vec<WebsiteMetadata<'a>> {
        vec![
			WebsiteMetadata::new("Allrecipes", "https://https://www.allrecipes.com/", None),
			WebsiteMetadata::new("Zaatar & Zaytoun", "https://https://zaatarandzaytoun.com/recipe-index/", Some("lebanese")),
			WebsiteMetadata::new("Zabiha Halal", "https://https://zabihahalal.com/recipes/", None),
			WebsiteMetadata::new("Zagleft", "https://https://zagleft.com/recipe-list/", None),
			WebsiteMetadata::new("ZardyPlants", "https://https://zardyplants.com", Some("vegetarian")),
			WebsiteMetadata::new("Zars Kitchen", "https://https://zarskitchen.com", None),
			WebsiteMetadata::new("ZZest", "https://https://zeezest.com/recipes/", None),
			WebsiteMetadata::new("Zen Belly", "https://https://www.zenbelly.com/recipes/", None),
			WebsiteMetadata::new("Zenhealth", "https://https://zenhealth.net/recipe-index/", None),
			WebsiteMetadata::new("Zen Kimchi", "https://https://zenkimchi.com", Some("korean")),
			WebsiteMetadata::new("Zestful Kitchen", "https://https://zestfulkitchen.com/category/all-recipes-from-zestful-kitchen/", None),
			WebsiteMetadata::new("Zesty South Indian Kitchen", "https://https://zestysouthindiankitchen.com", Some("indian")),
			WebsiteMetadata::new("Catherine Desserts", "https://https://zhangcatherine.com", None),
			WebsiteMetadata::new("Zia Hatch Chile Company", "https://https://ziahatchchileco.com", None)
        ]
    }
}
    