use std::fmt::Formatter;

use reqwest::Url;
use schema_org::Recipe;
use scraper::Html;

use crate::custom;

use super::{Error, Result};

/// Enumeration of all websites that can be scraped.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {
    O101cookbooksDotCom,
    O15gramsDotCom,
    O24kitchenDotNl,
    O750gDotCom,
    AbuelasCounterDotCom,
    ACoupleCooksDotCom,
    AddAPinchDotCom,
    AfghanKitchenRecipesDotCom,
    AFlavorJournalDotCom,
    AhDotNl,
    AkispetretzikisDotCom,
    AlexandraCooksDotCom,
    ALittleBitYummyDotCom,
    AllCladDotCom,
    AldiDotComDotAu,
    AllTheHealthyThingsDotCom,
    AllRecipesDotCom,
    AltonBrownDotCom,
    AmazingRibsDotCom,
    AmbitiousKitchenDotCom,
    AmericasTestKitchenDotCom,
    AngielaEatsDotCom,
    AniagotujeDotPl,
    AntilliaansEtenDotNl,
    ArchanasKitchenDotCom,
    ArgiroDotGr,
    ArlaDotSe,
    AtelierDesChefsDotFr,
    AverieCooksDotCom,
    AvocadoSkilletDotCom,
    BakingMischiefDotCom,
    BakelsDotComDotAu,
    BakingSenseDotCom,
    BarefootContessaDotCom,
    BareFeetInTheKitchenDotCom,
    BbcDotCoDotUk,
    BbcGoodFoodDotCom,
    BettyBossiDotCh,
    BettyCrockerDotCom,
    BeyondKimcheeDotCom,
    BiancazaPatkaDotCom,
    BigOvenDotCom,
    BlogDotGialloZafferanoDotIt,
    BlueApronDotCom,
    BlueJeanChefDotCom,
    BreadtopiaDotCom,
    BrianLagerstromDotCom,
    BriceletBaklavaDotCh,
    BritishBakelsDotCoDotUk,
    BodybuildingDotCom,
    BonAppetitDotCom,
    BongEatsDotCom,
    BottomlessGreensDotCom,
    BowlOfDeliciousDotCom,
    BudgetBytesDotCom,
    CafeDelitesDotCom,
    CanadaDotCa,
    CastironKetoDotCom,
    CdKitchenDotCom,
    CestMaFourneeDotCom,
    ChatelaineDotCom,
    ChefKochDotDe,
    ChefNiniDotCom,
    ChefSavvyDotCom,
    CheJorgeDotCom,
    ChetnamakanDotCoDotUk,
    ChineseCookingDemystifiedDotSubstackDotCom,
    ClaudiaAbrilComBr,
    ClosetCookingDotCom,
    ColruytDotBe,
    ComidinhasdoChefDotCom,
    CookEatShareDotCom,
    CookieAndKateDotCom,
    CookpadDotCom,
    CookTalkDotCom,
    CoopDotSe,
    CopykatDotCom,
    CostcoDotCom,
    CountryLivingDotCom,
    CreativeCanningDotCom,
    CucchiaioDotIt,
    CulyDotNl,
    CuisineAndTravelDotCom,
    CuisineazDotCom,
    CyberCookDotComDotBr,
    DamnDeliciousDotNet,
    DaringGourmetDotCom,
    DavidLebovitzDotCom,
    DelishDotCom,
    DherbsDotCom,
    DinnerAtTheZooDotCom,
    DinnerThenDessertDotCom,
    DishDotCoDotNz,
    DitchTheCarbsDotCom,
    DomesticateMeDotCom,
    DonnaHayDotComDotAu,
    DownshiftologyDotCom,
    DrDotdk,
    DreenaburtonDotCom,
    DrinkoteketDotSe,
    EatingBirdFoodDotCom,
    EatingWellDotCom,
    EatLiveRunDotCom,
    EatSmarterDotCom,
    EatWell101DotCom,
    EatWhatTonightDotCom,
    ElaveganDotCom,
    ElephantasticVeganDotCom,
    EmmikochteinfachDotDe,
    EntertainingWithBethDotCom,
    EpicuriousDotCom,
    ErrensKitchenDotCom,
    EtenvaneefkeDotNl,
    ExpressenDotSe,
    EvolvingTableDotCom,
    FamilyFoodOnTheTableDotCom,
    FarmhouseDeliveryDotCom,
    FarmhouseOnBooneDotCom,
    FattoInCasaDaBenedettaDotIt,
    FeastingAtHomeDotCom,
    FelixDotKitchen,
    FifteenSpatulasDotCom,
    FineDiningLoversDotCom,
    FindingTimeForCookingDotCom,
    FitMenCookDotCom,
    FitsLowCookerQueenDotCom,
    FoodDotCom,
    Food52DotCom,
    FoodalDotCom,
    FoodAndWineDotCom,
    FoodByMariaDotCom,
    FoodieCrushDotCom,
    FoodNetworkDotCoDotUk,
    FoodRepublicDotCom,
    FoolProofLivingDotCom,
    ForksOverKnivesDotCom,
    ForkToSpoonDotCom,
    FrancescaKooktDotNl,
    FranzoesischKochenDotDe,
    FredriksfikaDotAllasDotSe,
    GastroPlantDotCom,
    GazoakleyChefDotCom,
    GesundAktivDotCom,
    GialloZafferanoDotCom,
    GimmeSomeOvenDotCom,
    GloboDotCom,
    GlutenFreeTablesDotCom,
    GodtDotNo,
    GonnaWantSecondsDotCom,
    GoodEatingsDotCom,
    GoodFoodDiscoveriesDotCom,
    GoodHouseKeepingDotCom,
    GoodToDotCom,
    GourmetTravellerDotComDotAu,
    GurkiDotNo,
    GrandFraisDotCom,
    GreatBritishChefsDotCom,
    GreeneviDotCom,
    GrimGrainsDotCom,
    GroupRecipesDotCom,
    HalfBakedHarvestDotCom,
    HandleTheHeatDotCom,
    HassanChefDotCom,
    HeadbangersKitchenDotCom,
    HealthyLittleFoodiesDotCom,
    HeatherChristoDotCom,
    HelloFreshDotCom,
    HomebrewAnswersDotCom,
    HomeChefDotCom,
    HostTheToastDotCom,
    IcaDotSe,
    ImWorthyDotCom,
    InBloomBakeryDotCom,
    IndianHealthyRecipesDotCom,
    InnitDotCom,
    InsanelyGoodRecipesDotCom,
    InspiralizedDotCom,
    InstantPotDotCom,
    JamieOliverDotCom,
    JaimysKitchenDotNl,
    JarofLemonsDotCom,
    JimCooksFoodGoodDotCom,
    JoCooksDotCom,
    JoyFoodSunshineDotCom,
    JoyTheBakerDotCom,
    JulieGoodwinDotComDotAu,
    JumboDotCom,
    JustATasteDotCom,
    JustBentoDotCom,
    JustOneCookBookDotCom,
    KeepinItKindDotCom,
    KennyMcGovernDotCom,
    KingArthurBakingDotCom,
    KitchenAidDotComDotAu,
    KitchenSanctuaryDotCom,
    KitchenStoriesDotCom,
    KochbarDotDe,
    KochbucherDotCom,
    KoketDotSe,
    KookjijDotNl,
    KptnCookDotCom,
    KristinesKitchenBlogDotCom,
    KuchniaDomowaDotPl,
    KuchynalidlaDotSk,
    KwestiasmakuDotCom,
    LahbcoDotCom,
    LatelierDeRoxaneDotCom,
    LeanAndGreenRecipesDotNet,
    LeckerDotDe,
    LeCremeDeLaCrumbDotCom,
    LekkerenSimpelDotCom,
    LeukeReceptenDotNl,
    LifestyleOfAFoodieDotCom,
    LidlDotNl,
    LidlKochenDotDe,
    LithuanianInTheUsaDotCom,
    LittleSpiceJarDotCom,
    LivelyTableDotCom,
    LivingTheGreenLifeDotCom,
    LoveAndLemonsDotCom,
    LovingItVeganDotCom,
    MaangchiDotCom,
    MadensVerdenDotdk,
    MadsvinDotCom,
    MarmitonDotOrg,
    MarthaStewartDotCom,
    MatpratDotNo,
    McCormickDotCom,
    MeljoulwanDotCom,
    MelsKitchenCafeDotCom,
    MexicanMadeMeatlessDotCom,
    MindmegetteDotHu,
    MinimalistBakerDotCom,
    MinistryOfCurryDotCom,
    MisyaDotInfo,
    ModernHoneyDotCom,
    MomonTimeoutDotCom,
    MomsDishDotCom,
    MomsWithCrockpotsDotCom,
    MotherThymeDotCom,
    MoulinexDotFr,
    MundoDeReceitasBimbyDotComDotPt,
    MyBakingAddictionDotCom,
    MyJewishLearningDotCom,
    MyKitchen101DotCom,
    MyKoreanKitchenDotCom,
    MyGingerGarlicKitchenDotCom,
    MyKitchen101enDotCom,
    MyPlateDotGov,
    MyRecipesDotCom,
    NatashasKitchenDotCom,
    NigellaDotCom,
    NinjaTestKitchenDotEu,
    NourishedByNutritionDotCom,
    NosaltyDotHu,
    NotEnoughCinnamonDotCom,
    NrkDotNo,
    Number2PencilDotCom,
    NutritionFactsDotOrg,
    NyTimesDotCom,
    OhSheGlowsDotCom,
    OkokoReceptenDotNl,
    OmnivoresCookbookDotCom,
    OnceUponAChefDotCom,
    OhMyVeggiesDotCom,
    OneSweetAppetiteDotCom,
    OwenHanDotCom,
    PaleoRunningMommaDotCom,
    PanelinhaDotComDotBr,
    PaniniHappyDotCom,
    ParsleyAndParmDotCom,
    PersnicketyPlatesDotCom,
    PickupLimesDotCom,
    PinchOfYumDotCom,
    PinkOwlKitchenDotCom,
    PingoDoceDotPt,
    PlatingPixelsDotCom,
    PlentyVeganDotCom,
    PloetzBlogDotDe,
    PlowingThroughLifeDotCom,
    PopSugarDotCoDotUk,
    PotatoRollsDotGom,
    PracticalSelfRelianceDotCom,
    PressureLuckCookingDotCom,
    PrimalEdgeHealthDotCom,
    ProjectGezondDotNl,
    PrzepisyDotPl,
    PurelyPopeDotCom,
    PureWowDotCom,
    PurpleCarrotDotCom,
    PuurgezondDotNl,
    QuitoqueDotFr,
    RachlmansFieldDotCom,
    RadioFranceDotFr,
    RainbowPlantLifeDotCom,
    RealSimpleDotCom,
    ReceitasNestleDotComDotBr,
    RecettesDotQcDotCa,
    RecipeGirlDotCom,
    RecipeRunnerDotCom,
    RecipeTinEatsDotCom,
    RedditDotCom,
    RedhouseSpiceDotCom,
    ReisHungerDotDe,
    RezeptWeltDotDe,
    RicettaDotIt,
    RicettePerBimbyDotIt,
    RobinasBellDotCom,
    RosannaPansinoDotCom,
    RutgerbaktDotNl,
    RecipeCommunityDotComDotAu,
    SaboresaJinomotoDotComDotBr,
    SallysBakingAddictionDotCom,
    SallysBlogDotDe,
    SaltAndLavenderDotCom,
    SaltPepperSkilletDotCom,
    SarahsVeganGuideDotCom,
    SaveurDotCom,
    SavoryNothingsDotCom,
    SeriousEatsDotCom,
    SimpleVeganistaDotCom,
    SimplyCookitDotCom,
    SimplyQuinoaDotCom,
    SimplyRecipesDotCom,
    SimplyWhiskedDotCom,
    SkinnyTasteDotCom,
    SmittenKitchenDotCom,
    SoborsDotHu,
    SouthernCastIronDotCom,
    SouthernLivingDotCom,
    SpendWithPenniesDotCom,
    SpiceboxTravelsDotCom,
    StaySnatchedDotCom,
    SteamyKitchenDotCom,
    StreetKitchenDotCo,
    StrongrFastrDotCom,
    SunBasketDotCom,
    SundPaabudgetDotdk,
    SunsetDotCom,
    SweetcsDesignsDotCom,
    SweetPeasAndSaffronDotCom,
    TasteAtlasDotCom,
    TasteOfHomeDotCom,
    TastesBetterFromScratchDotCom,
    TastesOfLizzyTDotCom,
    TastyDotCo,
    TastyKitchenDotCom,
    TescoDotCom,
    ThatVeganDadDotNet,
    TheCleverCarrotDotCom,
    TheCookieRookieDotCom,
    TheCookingGuyDotCom,
    TheExpertGuidesDotCom,
    TheFoodFlamingoDotCom,
    TheGucchaDotCom,
    TheHappyFoodieDotCoDotUk,
    TheHeartySoulDotCom,
    TheKitchenCommunityDotOrg,
    TheKitchenMagPieDotCom,
    TheKitchnDotCom,
    TheMagicalSlowCookerDotCom,
    TheNutritiousKitchenDotCo,
    TheModernProperDotCom,
    ThePalatableLifeDotCom,
    ThePioneerWomanDotCom,
    TheRecipeCriticDotCom,
    TheSaltyMarshmallowDotCom,
    TheSpruceEatsDotCom,
    TheVintageMixerDotCom,
    TheWoksOfLifeDotCom,
    ThinliciousDotCom,
    TidyMomDotNet,
    TimesOfIndiaDotCom,
    TineDotNo,
    TudogostosoDotComDotBr,
    TwoPeasAndTheirPodDotCom,
    TwoSleeversDotCom,
    UitPaulinesKeukenDotNl,
    UnsophistiCookDotCom,
    UsaPearsDotOrg,
    ValdemarsroDotdk,
    VanillaAndBeanDotCom,
    VeganPratiqueDotFr,
    VegetarBloggenDotNo,
    VegolosiDotIt,
    VegRecipesOfIndiaDotCom,
    WaitRoseDotCom,
    WatchWhatUEatDotCom,
    WeAreNotMarthaDotCom,
    WeightWatchersDotCom,
    WellPlatedDotCom,
    WhatsGabyCookingDotCom,
    WholeFoodsMarketDotCoDotUk,
    WikibooksDotOrg,
    WikibooksDotOrgMobile,
    WomensWeeklyFoodDotComDotAu,
    WoopDotCoDotNz,
    YeMekDotNet,
    YumeliseDotFr,
    ZaatarAndZaytounDotCom,
    ZabihaHalal,
    ZeitDotDe,
    ZenbellyDotCom,
}

impl Website {
    /// Returns the domain name of the website.
    pub fn domain(&self) -> &str {
        match self {
            Website::O101cookbooksDotCom => todo!(),
            Website::O15gramsDotCom => todo!(),
            Website::O24kitchenDotNl => todo!(),
            Website::O750gDotCom => todo!(),
            Website::AbuelasCounterDotCom => todo!(),
            Website::ACoupleCooksDotCom => todo!(),
            Website::AddAPinchDotCom => todo!(),
            Website::AfghanKitchenRecipesDotCom => todo!(),
            Website::AFlavorJournalDotCom => todo!(),
            Website::AhDotNl => todo!(),
            Website::AkispetretzikisDotCom => todo!(),
            Website::AlexandraCooksDotCom => todo!(),
            Website::ALittleBitYummyDotCom => todo!(),
            Website::AllCladDotCom => todo!(),
            Website::AldiDotComDotAu => todo!(),
            Website::AllTheHealthyThingsDotCom => todo!(),
            Website::AllRecipesDotCom => todo!(),
            Website::AltonBrownDotCom => todo!(),
            Website::AmazingRibsDotCom => todo!(),
            Website::AmbitiousKitchenDotCom => todo!(),
            Website::AmericasTestKitchenDotCom => todo!(),
            Website::AngielaEatsDotCom => todo!(),
            Website::AniagotujeDotPl => todo!(),
            Website::AntilliaansEtenDotNl => todo!(),
            Website::ArchanasKitchenDotCom => todo!(),
            Website::ArgiroDotGr => todo!(),
            Website::ArlaDotSe => todo!(),
            Website::AtelierDesChefsDotFr => todo!(),
            Website::AverieCooksDotCom => todo!(),
            Website::AvocadoSkilletDotCom => todo!(),
            Website::BakingMischiefDotCom => todo!(),
            Website::BakelsDotComDotAu => todo!(),
            Website::BakingSenseDotCom => todo!(),
            Website::BarefootContessaDotCom => todo!(),
            Website::BareFeetInTheKitchenDotCom => todo!(),
            Website::BbcDotCoDotUk => todo!(),
            Website::BbcGoodFoodDotCom => todo!(),
            Website::BettyBossiDotCh => todo!(),
            Website::BettyCrockerDotCom => todo!(),
            Website::BeyondKimcheeDotCom => todo!(),
            Website::BiancazaPatkaDotCom => todo!(),
            Website::BigOvenDotCom => todo!(),
            Website::BlogDotGialloZafferanoDotIt => todo!(),
            Website::BlueApronDotCom => todo!(),
            Website::BlueJeanChefDotCom => todo!(),
            Website::BreadtopiaDotCom => todo!(),
            Website::BrianLagerstromDotCom => todo!(),
            Website::BriceletBaklavaDotCh => todo!(),
            Website::BritishBakelsDotCoDotUk => todo!(),
            Website::BodybuildingDotCom => todo!(),
            Website::BonAppetitDotCom => todo!(),
            Website::BongEatsDotCom => todo!(),
            Website::BottomlessGreensDotCom => todo!(),
            Website::BowlOfDeliciousDotCom => todo!(),
            Website::BudgetBytesDotCom => todo!(),
            Website::CafeDelitesDotCom => todo!(),
            Website::CanadaDotCa => todo!(),
            Website::CastironKetoDotCom => todo!(),
            Website::CdKitchenDotCom => todo!(),
            Website::CestMaFourneeDotCom => todo!(),
            Website::ChatelaineDotCom => todo!(),
            Website::ChefKochDotDe => todo!(),
            Website::ChefNiniDotCom => todo!(),
            Website::ChefSavvyDotCom => todo!(),
            Website::CheJorgeDotCom => todo!(),
            Website::ChetnamakanDotCoDotUk => todo!(),
            Website::ChineseCookingDemystifiedDotSubstackDotCom => todo!(),
            Website::ClaudiaAbrilComBr => todo!(),
            Website::ClosetCookingDotCom => todo!(),
            Website::ColruytDotBe => todo!(),
            Website::ComidinhasdoChefDotCom => todo!(),
            Website::CookEatShareDotCom => todo!(),
            Website::CookieAndKateDotCom => todo!(),
            Website::CookpadDotCom => todo!(),
            Website::CookTalkDotCom => todo!(),
            Website::CoopDotSe => todo!(),
            Website::CopykatDotCom => todo!(),
            Website::CostcoDotCom => todo!(),
            Website::CountryLivingDotCom => todo!(),
            Website::CreativeCanningDotCom => todo!(),
            Website::CucchiaioDotIt => todo!(),
            Website::CulyDotNl => todo!(),
            Website::CuisineAndTravelDotCom => todo!(),
            Website::CuisineazDotCom => todo!(),
            Website::CyberCookDotComDotBr => todo!(),
            Website::DamnDeliciousDotNet => todo!(),
            Website::DaringGourmetDotCom => todo!(),
            Website::DavidLebovitzDotCom => todo!(),
            Website::DelishDotCom => todo!(),
            Website::DherbsDotCom => todo!(),
            Website::DinnerAtTheZooDotCom => todo!(),
            Website::DinnerThenDessertDotCom => todo!(),
            Website::DishDotCoDotNz => todo!(),
            Website::DitchTheCarbsDotCom => todo!(),
            Website::DomesticateMeDotCom => todo!(),
            Website::DonnaHayDotComDotAu => todo!(),
            Website::DownshiftologyDotCom => todo!(),
            Website::DrDotdk => todo!(),
            Website::DreenaburtonDotCom => todo!(),
            Website::DrinkoteketDotSe => todo!(),
            Website::EatingBirdFoodDotCom => todo!(),
            Website::EatingWellDotCom => todo!(),
            Website::EatLiveRunDotCom => todo!(),
            Website::EatSmarterDotCom => todo!(),
            Website::EatWell101DotCom => todo!(),
            Website::EatWhatTonightDotCom => todo!(),
            Website::ElaveganDotCom => todo!(),
            Website::ElephantasticVeganDotCom => todo!(),
            Website::EmmikochteinfachDotDe => todo!(),
            Website::EntertainingWithBethDotCom => todo!(),
            Website::EpicuriousDotCom => todo!(),
            Website::ErrensKitchenDotCom => todo!(),
            Website::EtenvaneefkeDotNl => todo!(),
            Website::ExpressenDotSe => todo!(),
            Website::EvolvingTableDotCom => todo!(),
            Website::FamilyFoodOnTheTableDotCom => todo!(),
            Website::FarmhouseDeliveryDotCom => todo!(),
            Website::FarmhouseOnBooneDotCom => todo!(),
            Website::FattoInCasaDaBenedettaDotIt => todo!(),
            Website::FeastingAtHomeDotCom => todo!(),
            Website::FelixDotKitchen => todo!(),
            Website::FifteenSpatulasDotCom => todo!(),
            Website::FineDiningLoversDotCom => todo!(),
            Website::FindingTimeForCookingDotCom => todo!(),
            Website::FitMenCookDotCom => todo!(),
            Website::FitsLowCookerQueenDotCom => todo!(),
            Website::FoodDotCom => todo!(),
            Website::Food52DotCom => todo!(),
            Website::FoodalDotCom => todo!(),
            Website::FoodAndWineDotCom => todo!(),
            Website::FoodByMariaDotCom => todo!(),
            Website::FoodieCrushDotCom => todo!(),
            Website::FoodNetworkDotCoDotUk => todo!(),
            Website::FoodRepublicDotCom => todo!(),
            Website::FoolProofLivingDotCom => todo!(),
            Website::ForksOverKnivesDotCom => todo!(),
            Website::ForkToSpoonDotCom => todo!(),
            Website::FrancescaKooktDotNl => todo!(),
            Website::FranzoesischKochenDotDe => todo!(),
            Website::FredriksfikaDotAllasDotSe => todo!(),
            Website::GastroPlantDotCom => todo!(),
            Website::GazoakleyChefDotCom => todo!(),
            Website::GesundAktivDotCom => todo!(),
            Website::GialloZafferanoDotCom => todo!(),
            Website::GimmeSomeOvenDotCom => todo!(),
            Website::GloboDotCom => todo!(),
            Website::GlutenFreeTablesDotCom => todo!(),
            Website::GodtDotNo => todo!(),
            Website::GonnaWantSecondsDotCom => todo!(),
            Website::GoodEatingsDotCom => todo!(),
            Website::GoodFoodDiscoveriesDotCom => todo!(),
            Website::GoodHouseKeepingDotCom => todo!(),
            Website::GoodToDotCom => todo!(),
            Website::GourmetTravellerDotComDotAu => todo!(),
            Website::GurkiDotNo => todo!(),
            Website::GrandFraisDotCom => todo!(),
            Website::GreatBritishChefsDotCom => todo!(),
            Website::GreeneviDotCom => todo!(),
            Website::GrimGrainsDotCom => todo!(),
            Website::GroupRecipesDotCom => todo!(),
            Website::HalfBakedHarvestDotCom => todo!(),
            Website::HandleTheHeatDotCom => todo!(),
            Website::HassanChefDotCom => todo!(),
            Website::HeadbangersKitchenDotCom => todo!(),
            Website::HealthyLittleFoodiesDotCom => todo!(),
            Website::HeatherChristoDotCom => todo!(),
            Website::HelloFreshDotCom => todo!(),
            Website::HomebrewAnswersDotCom => todo!(),
            Website::HomeChefDotCom => todo!(),
            Website::HostTheToastDotCom => todo!(),
            Website::IcaDotSe => todo!(),
            Website::ImWorthyDotCom => todo!(),
            Website::InBloomBakeryDotCom => todo!(),
            Website::IndianHealthyRecipesDotCom => todo!(),
            Website::InnitDotCom => todo!(),
            Website::InsanelyGoodRecipesDotCom => todo!(),
            Website::InspiralizedDotCom => todo!(),
            Website::InstantPotDotCom => todo!(),
            Website::JamieOliverDotCom => todo!(),
            Website::JaimysKitchenDotNl => todo!(),
            Website::JarofLemonsDotCom => todo!(),
            Website::JimCooksFoodGoodDotCom => todo!(),
            Website::JoCooksDotCom => todo!(),
            Website::JoyFoodSunshineDotCom => todo!(),
            Website::JoyTheBakerDotCom => todo!(),
            Website::JulieGoodwinDotComDotAu => todo!(),
            Website::JumboDotCom => todo!(),
            Website::JustATasteDotCom => todo!(),
            Website::JustBentoDotCom => todo!(),
            Website::JustOneCookBookDotCom => todo!(),
            Website::KeepinItKindDotCom => todo!(),
            Website::KennyMcGovernDotCom => todo!(),
            Website::KingArthurBakingDotCom => todo!(),
            Website::KitchenAidDotComDotAu => todo!(),
            Website::KitchenSanctuaryDotCom => todo!(),
            Website::KitchenStoriesDotCom => todo!(),
            Website::KochbarDotDe => todo!(),
            Website::KochbucherDotCom => todo!(),
            Website::KoketDotSe => todo!(),
            Website::KookjijDotNl => todo!(),
            Website::KptnCookDotCom => todo!(),
            Website::KristinesKitchenBlogDotCom => todo!(),
            Website::KuchniaDomowaDotPl => todo!(),
            Website::KuchynalidlaDotSk => todo!(),
            Website::KwestiasmakuDotCom => todo!(),
            Website::LahbcoDotCom => todo!(),
            Website::LatelierDeRoxaneDotCom => todo!(),
            Website::LeanAndGreenRecipesDotNet => todo!(),
            Website::LeckerDotDe => todo!(),
            Website::LeCremeDeLaCrumbDotCom => todo!(),
            Website::LekkerenSimpelDotCom => todo!(),
            Website::LeukeReceptenDotNl => todo!(),
            Website::LifestyleOfAFoodieDotCom => todo!(),
            Website::LidlDotNl => todo!(),
            Website::LidlKochenDotDe => todo!(),
            Website::LithuanianInTheUsaDotCom => todo!(),
            Website::LittleSpiceJarDotCom => todo!(),
            Website::LivelyTableDotCom => todo!(),
            Website::LivingTheGreenLifeDotCom => todo!(),
            Website::LoveAndLemonsDotCom => todo!(),
            Website::LovingItVeganDotCom => todo!(),
            Website::MaangchiDotCom => todo!(),
            Website::MadensVerdenDotdk => todo!(),
            Website::MadsvinDotCom => todo!(),
            Website::MarmitonDotOrg => todo!(),
            Website::MarthaStewartDotCom => todo!(),
            Website::MatpratDotNo => todo!(),
            Website::McCormickDotCom => todo!(),
            Website::MeljoulwanDotCom => todo!(),
            Website::MelsKitchenCafeDotCom => todo!(),
            Website::MexicanMadeMeatlessDotCom => todo!(),
            Website::MindmegetteDotHu => todo!(),
            Website::MinimalistBakerDotCom => todo!(),
            Website::MinistryOfCurryDotCom => todo!(),
            Website::MisyaDotInfo => todo!(),
            Website::ModernHoneyDotCom => todo!(),
            Website::MomonTimeoutDotCom => todo!(),
            Website::MomsDishDotCom => todo!(),
            Website::MomsWithCrockpotsDotCom => todo!(),
            Website::MotherThymeDotCom => todo!(),
            Website::MoulinexDotFr => todo!(),
            Website::MundoDeReceitasBimbyDotComDotPt => todo!(),
            Website::MyBakingAddictionDotCom => todo!(),
            Website::MyJewishLearningDotCom => todo!(),
            Website::MyKitchen101DotCom => todo!(),
            Website::MyKoreanKitchenDotCom => todo!(),
            Website::MyGingerGarlicKitchenDotCom => todo!(),
            Website::MyKitchen101enDotCom => todo!(),
            Website::MyPlateDotGov => todo!(),
            Website::MyRecipesDotCom => todo!(),
            Website::NatashasKitchenDotCom => todo!(),
            Website::NigellaDotCom => todo!(),
            Website::NinjaTestKitchenDotEu => todo!(),
            Website::NourishedByNutritionDotCom => todo!(),
            Website::NosaltyDotHu => todo!(),
            Website::NotEnoughCinnamonDotCom => todo!(),
            Website::NrkDotNo => todo!(),
            Website::Number2PencilDotCom => todo!(),
            Website::NutritionFactsDotOrg => todo!(),
            Website::NyTimesDotCom => todo!(),
            Website::OhSheGlowsDotCom => todo!(),
            Website::OkokoReceptenDotNl => todo!(),
            Website::OmnivoresCookbookDotCom => todo!(),
            Website::OnceUponAChefDotCom => todo!(),
            Website::OhMyVeggiesDotCom => todo!(),
            Website::OneSweetAppetiteDotCom => todo!(),
            Website::OwenHanDotCom => todo!(),
            Website::PaleoRunningMommaDotCom => todo!(),
            Website::PanelinhaDotComDotBr => todo!(),
            Website::PaniniHappyDotCom => todo!(),
            Website::ParsleyAndParmDotCom => todo!(),
            Website::PersnicketyPlatesDotCom => todo!(),
            Website::PickupLimesDotCom => todo!(),
            Website::PinchOfYumDotCom => todo!(),
            Website::PinkOwlKitchenDotCom => todo!(),
            Website::PingoDoceDotPt => todo!(),
            Website::PlatingPixelsDotCom => todo!(),
            Website::PlentyVeganDotCom => todo!(),
            Website::PloetzBlogDotDe => todo!(),
            Website::PlowingThroughLifeDotCom => todo!(),
            Website::PopSugarDotCoDotUk => todo!(),
            Website::PotatoRollsDotGom => todo!(),
            Website::PracticalSelfRelianceDotCom => todo!(),
            Website::PressureLuckCookingDotCom => todo!(),
            Website::PrimalEdgeHealthDotCom => todo!(),
            Website::ProjectGezondDotNl => todo!(),
            Website::PrzepisyDotPl => todo!(),
            Website::PurelyPopeDotCom => todo!(),
            Website::PureWowDotCom => todo!(),
            Website::PurpleCarrotDotCom => todo!(),
            Website::PuurgezondDotNl => todo!(),
            Website::QuitoqueDotFr => todo!(),
            Website::RachlmansFieldDotCom => todo!(),
            Website::RadioFranceDotFr => todo!(),
            Website::RainbowPlantLifeDotCom => todo!(),
            Website::RealSimpleDotCom => todo!(),
            Website::ReceitasNestleDotComDotBr => todo!(),
            Website::RecettesDotQcDotCa => todo!(),
            Website::RecipeGirlDotCom => todo!(),
            Website::RecipeRunnerDotCom => todo!(),
            Website::RecipeTinEatsDotCom => todo!(),
            Website::RedditDotCom => todo!(),
            Website::RedhouseSpiceDotCom => todo!(),
            Website::ReisHungerDotDe => todo!(),
            Website::RezeptWeltDotDe => todo!(),
            Website::RicettaDotIt => todo!(),
            Website::RicettePerBimbyDotIt => todo!(),
            Website::RobinasBellDotCom => todo!(),
            Website::RosannaPansinoDotCom => todo!(),
            Website::RutgerbaktDotNl => todo!(),
            Website::RecipeCommunityDotComDotAu => todo!(),
            Website::SaboresaJinomotoDotComDotBr => todo!(),
            Website::SallysBakingAddictionDotCom => todo!(),
            Website::SallysBlogDotDe => todo!(),
            Website::SaltAndLavenderDotCom => todo!(),
            Website::SaltPepperSkilletDotCom => todo!(),
            Website::SarahsVeganGuideDotCom => todo!(),
            Website::SaveurDotCom => todo!(),
            Website::SavoryNothingsDotCom => todo!(),
            Website::SeriousEatsDotCom => todo!(),
            Website::SimpleVeganistaDotCom => todo!(),
            Website::SimplyCookitDotCom => todo!(),
            Website::SimplyQuinoaDotCom => todo!(),
            Website::SimplyRecipesDotCom => todo!(),
            Website::SimplyWhiskedDotCom => todo!(),
            Website::SkinnyTasteDotCom => todo!(),
            Website::SmittenKitchenDotCom => todo!(),
            Website::SoborsDotHu => todo!(),
            Website::SouthernCastIronDotCom => todo!(),
            Website::SouthernLivingDotCom => todo!(),
            Website::SpendWithPenniesDotCom => todo!(),
            Website::SpiceboxTravelsDotCom => todo!(),
            Website::StaySnatchedDotCom => todo!(),
            Website::SteamyKitchenDotCom => todo!(),
            Website::StreetKitchenDotCo => todo!(),
            Website::StrongrFastrDotCom => todo!(),
            Website::SunBasketDotCom => todo!(),
            Website::SundPaabudgetDotdk => todo!(),
            Website::SunsetDotCom => todo!(),
            Website::SweetcsDesignsDotCom => todo!(),
            Website::SweetPeasAndSaffronDotCom => todo!(),
            Website::TasteAtlasDotCom => todo!(),
            Website::TasteOfHomeDotCom => todo!(),
            Website::TastesBetterFromScratchDotCom => todo!(),
            Website::TastesOfLizzyTDotCom => todo!(),
            Website::TastyDotCo => todo!(),
            Website::TastyKitchenDotCom => todo!(),
            Website::TescoDotCom => todo!(),
            Website::ThatVeganDadDotNet => todo!(),
            Website::TheCleverCarrotDotCom => todo!(),
            Website::TheCookieRookieDotCom => todo!(),
            Website::TheCookingGuyDotCom => todo!(),
            Website::TheExpertGuidesDotCom => todo!(),
            Website::TheFoodFlamingoDotCom => todo!(),
            Website::TheGucchaDotCom => todo!(),
            Website::TheHappyFoodieDotCoDotUk => todo!(),
            Website::TheHeartySoulDotCom => todo!(),
            Website::TheKitchenCommunityDotOrg => todo!(),
            Website::TheKitchenMagPieDotCom => todo!(),
            Website::TheKitchnDotCom => todo!(),
            Website::TheMagicalSlowCookerDotCom => todo!(),
            Website::TheNutritiousKitchenDotCo => todo!(),
            Website::TheModernProperDotCom => todo!(),
            Website::ThePalatableLifeDotCom => todo!(),
            Website::ThePioneerWomanDotCom => todo!(),
            Website::TheRecipeCriticDotCom => todo!(),
            Website::TheSaltyMarshmallowDotCom => todo!(),
            Website::TheSpruceEatsDotCom => todo!(),
            Website::TheVintageMixerDotCom => todo!(),
            Website::TheWoksOfLifeDotCom => todo!(),
            Website::ThinliciousDotCom => todo!(),
            Website::TidyMomDotNet => todo!(),
            Website::TimesOfIndiaDotCom => todo!(),
            Website::TineDotNo => todo!(),
            Website::TudogostosoDotComDotBr => todo!(),
            Website::TwoPeasAndTheirPodDotCom => todo!(),
            Website::TwoSleeversDotCom => todo!(),
            Website::UitPaulinesKeukenDotNl => todo!(),
            Website::UnsophistiCookDotCom => todo!(),
            Website::UsaPearsDotOrg => todo!(),
            Website::ValdemarsroDotdk => todo!(),
            Website::VanillaAndBeanDotCom => todo!(),
            Website::VeganPratiqueDotFr => todo!(),
            Website::VegetarBloggenDotNo => todo!(),
            Website::VegolosiDotIt => todo!(),
            Website::VegRecipesOfIndiaDotCom => todo!(),
            Website::WaitRoseDotCom => todo!(),
            Website::WatchWhatUEatDotCom => todo!(),
            Website::WeAreNotMarthaDotCom => todo!(),
            Website::WeightWatchersDotCom => todo!(),
            Website::WellPlatedDotCom => todo!(),
            Website::WhatsGabyCookingDotCom => todo!(),
            Website::WholeFoodsMarketDotCoDotUk => todo!(),
            Website::WikibooksDotOrg => todo!(),
            Website::WikibooksDotOrgMobile => todo!(),
            Website::WomensWeeklyFoodDotComDotAu => todo!(),
            Website::WoopDotCoDotNz => todo!(),
            Website::YeMekDotNet => todo!(),
            Website::YumeliseDotFr => todo!(),
            Website::ZaatarAndZaytounDotCom => "zaatarandzaytoun.com",
            Website::ZabihaHalal => "zabihahalal.com",
            Website::ZeitDotDe => todo!(),
            Website::ZenbellyDotCom => todo!(),
        }
    }

    /// Creates a `Website` instance from a given URL.
    pub fn from(url: &str) -> Result<Self> {
        let url = Url::parse(url).map_err(|err| Error::Parse(err.to_string()))?;
        let domain = url.domain().ok_or(Error::UnknownWebsite)?;
        Website::from_domain(domain).ok_or(Error::UnknownWebsite)
    }

    fn from_domain(domain: &str) -> Option<Self> {
        match domain {
            "zaatarandzaytoun.com" => Some(Website::ZaatarAndZaytounDotCom),
            "zabihahalal.com" => Some(Website::ZabihaHalal),
            _ => None,
        }
    }

    /// Parses the given HTML document manually.
    pub fn parse_manually(&self, doc: &Html, url: &str) -> Result<Recipe> {
        match self {
            Website::O101cookbooksDotCom => todo!(),
            Website::O15gramsDotCom => todo!(),
            Website::O24kitchenDotNl => todo!(),
            Website::O750gDotCom => todo!(),
            Website::AbuelasCounterDotCom => todo!(),
            Website::ACoupleCooksDotCom => todo!(),
            Website::AddAPinchDotCom => todo!(),
            Website::AfghanKitchenRecipesDotCom => todo!(),
            Website::AFlavorJournalDotCom => todo!(),
            Website::AhDotNl => todo!(),
            Website::AkispetretzikisDotCom => todo!(),
            Website::AlexandraCooksDotCom => todo!(),
            Website::ALittleBitYummyDotCom => todo!(),
            Website::AllCladDotCom => todo!(),
            Website::AldiDotComDotAu => todo!(),
            Website::AllTheHealthyThingsDotCom => todo!(),
            Website::AllRecipesDotCom => todo!(),
            Website::AltonBrownDotCom => todo!(),
            Website::AmazingRibsDotCom => todo!(),
            Website::AmbitiousKitchenDotCom => todo!(),
            Website::AmericasTestKitchenDotCom => todo!(),
            Website::AngielaEatsDotCom => todo!(),
            Website::AniagotujeDotPl => todo!(),
            Website::AntilliaansEtenDotNl => todo!(),
            Website::ArchanasKitchenDotCom => todo!(),
            Website::ArgiroDotGr => todo!(),
            Website::ArlaDotSe => todo!(),
            Website::AtelierDesChefsDotFr => todo!(),
            Website::AverieCooksDotCom => todo!(),
            Website::AvocadoSkilletDotCom => todo!(),
            Website::BakingMischiefDotCom => todo!(),
            Website::BakelsDotComDotAu => todo!(),
            Website::BakingSenseDotCom => todo!(),
            Website::BarefootContessaDotCom => todo!(),
            Website::BareFeetInTheKitchenDotCom => todo!(),
            Website::BbcDotCoDotUk => todo!(),
            Website::BbcGoodFoodDotCom => todo!(),
            Website::BettyBossiDotCh => todo!(),
            Website::BettyCrockerDotCom => todo!(),
            Website::BeyondKimcheeDotCom => todo!(),
            Website::BiancazaPatkaDotCom => todo!(),
            Website::BigOvenDotCom => todo!(),
            Website::BlogDotGialloZafferanoDotIt => todo!(),
            Website::BlueApronDotCom => todo!(),
            Website::BlueJeanChefDotCom => todo!(),
            Website::BreadtopiaDotCom => todo!(),
            Website::BrianLagerstromDotCom => todo!(),
            Website::BriceletBaklavaDotCh => todo!(),
            Website::BritishBakelsDotCoDotUk => todo!(),
            Website::BodybuildingDotCom => todo!(),
            Website::BonAppetitDotCom => todo!(),
            Website::BongEatsDotCom => todo!(),
            Website::BottomlessGreensDotCom => todo!(),
            Website::BowlOfDeliciousDotCom => todo!(),
            Website::BudgetBytesDotCom => todo!(),
            Website::CafeDelitesDotCom => todo!(),
            Website::CanadaDotCa => todo!(),
            Website::CastironKetoDotCom => todo!(),
            Website::CdKitchenDotCom => todo!(),
            Website::CestMaFourneeDotCom => todo!(),
            Website::ChatelaineDotCom => todo!(),
            Website::ChefKochDotDe => todo!(),
            Website::ChefNiniDotCom => todo!(),
            Website::ChefSavvyDotCom => todo!(),
            Website::CheJorgeDotCom => todo!(),
            Website::ChetnamakanDotCoDotUk => todo!(),
            Website::ChineseCookingDemystifiedDotSubstackDotCom => todo!(),
            Website::ClaudiaAbrilComBr => todo!(),
            Website::ClosetCookingDotCom => todo!(),
            Website::ColruytDotBe => todo!(),
            Website::ComidinhasdoChefDotCom => todo!(),
            Website::CookEatShareDotCom => todo!(),
            Website::CookieAndKateDotCom => todo!(),
            Website::CookpadDotCom => todo!(),
            Website::CookTalkDotCom => todo!(),
            Website::CoopDotSe => todo!(),
            Website::CopykatDotCom => todo!(),
            Website::CostcoDotCom => todo!(),
            Website::CountryLivingDotCom => todo!(),
            Website::CreativeCanningDotCom => todo!(),
            Website::CucchiaioDotIt => todo!(),
            Website::CulyDotNl => todo!(),
            Website::CuisineAndTravelDotCom => todo!(),
            Website::CuisineazDotCom => todo!(),
            Website::CyberCookDotComDotBr => todo!(),
            Website::DamnDeliciousDotNet => todo!(),
            Website::DaringGourmetDotCom => todo!(),
            Website::DavidLebovitzDotCom => todo!(),
            Website::DelishDotCom => todo!(),
            Website::DherbsDotCom => todo!(),
            Website::DinnerAtTheZooDotCom => todo!(),
            Website::DinnerThenDessertDotCom => todo!(),
            Website::DishDotCoDotNz => todo!(),
            Website::DitchTheCarbsDotCom => todo!(),
            Website::DomesticateMeDotCom => todo!(),
            Website::DonnaHayDotComDotAu => todo!(),
            Website::DownshiftologyDotCom => todo!(),
            Website::DrDotdk => todo!(),
            Website::DreenaburtonDotCom => todo!(),
            Website::DrinkoteketDotSe => todo!(),
            Website::EatingBirdFoodDotCom => todo!(),
            Website::EatingWellDotCom => todo!(),
            Website::EatLiveRunDotCom => todo!(),
            Website::EatSmarterDotCom => todo!(),
            Website::EatWell101DotCom => todo!(),
            Website::EatWhatTonightDotCom => todo!(),
            Website::ElaveganDotCom => todo!(),
            Website::ElephantasticVeganDotCom => todo!(),
            Website::EmmikochteinfachDotDe => todo!(),
            Website::EntertainingWithBethDotCom => todo!(),
            Website::EpicuriousDotCom => todo!(),
            Website::ErrensKitchenDotCom => todo!(),
            Website::EtenvaneefkeDotNl => todo!(),
            Website::ExpressenDotSe => todo!(),
            Website::EvolvingTableDotCom => todo!(),
            Website::FamilyFoodOnTheTableDotCom => todo!(),
            Website::FarmhouseDeliveryDotCom => todo!(),
            Website::FarmhouseOnBooneDotCom => todo!(),
            Website::FattoInCasaDaBenedettaDotIt => todo!(),
            Website::FeastingAtHomeDotCom => todo!(),
            Website::FelixDotKitchen => todo!(),
            Website::FifteenSpatulasDotCom => todo!(),
            Website::FineDiningLoversDotCom => todo!(),
            Website::FindingTimeForCookingDotCom => todo!(),
            Website::FitMenCookDotCom => todo!(),
            Website::FitsLowCookerQueenDotCom => todo!(),
            Website::FoodDotCom => todo!(),
            Website::Food52DotCom => todo!(),
            Website::FoodalDotCom => todo!(),
            Website::FoodAndWineDotCom => todo!(),
            Website::FoodByMariaDotCom => todo!(),
            Website::FoodieCrushDotCom => todo!(),
            Website::FoodNetworkDotCoDotUk => todo!(),
            Website::FoodRepublicDotCom => todo!(),
            Website::FoolProofLivingDotCom => todo!(),
            Website::ForksOverKnivesDotCom => todo!(),
            Website::ForkToSpoonDotCom => todo!(),
            Website::FrancescaKooktDotNl => todo!(),
            Website::FranzoesischKochenDotDe => todo!(),
            Website::FredriksfikaDotAllasDotSe => todo!(),
            Website::GastroPlantDotCom => todo!(),
            Website::GazoakleyChefDotCom => todo!(),
            Website::GesundAktivDotCom => todo!(),
            Website::GialloZafferanoDotCom => todo!(),
            Website::GimmeSomeOvenDotCom => todo!(),
            Website::GloboDotCom => todo!(),
            Website::GlutenFreeTablesDotCom => todo!(),
            Website::GodtDotNo => todo!(),
            Website::GonnaWantSecondsDotCom => todo!(),
            Website::GoodEatingsDotCom => todo!(),
            Website::GoodFoodDiscoveriesDotCom => todo!(),
            Website::GoodHouseKeepingDotCom => todo!(),
            Website::GoodToDotCom => todo!(),
            Website::GourmetTravellerDotComDotAu => todo!(),
            Website::GurkiDotNo => todo!(),
            Website::GrandFraisDotCom => todo!(),
            Website::GreatBritishChefsDotCom => todo!(),
            Website::GreeneviDotCom => todo!(),
            Website::GrimGrainsDotCom => todo!(),
            Website::GroupRecipesDotCom => todo!(),
            Website::HalfBakedHarvestDotCom => todo!(),
            Website::HandleTheHeatDotCom => todo!(),
            Website::HassanChefDotCom => todo!(),
            Website::HeadbangersKitchenDotCom => todo!(),
            Website::HealthyLittleFoodiesDotCom => todo!(),
            Website::HeatherChristoDotCom => todo!(),
            Website::HelloFreshDotCom => todo!(),
            Website::HomebrewAnswersDotCom => todo!(),
            Website::HomeChefDotCom => todo!(),
            Website::HostTheToastDotCom => todo!(),
            Website::IcaDotSe => todo!(),
            Website::ImWorthyDotCom => todo!(),
            Website::InBloomBakeryDotCom => todo!(),
            Website::IndianHealthyRecipesDotCom => todo!(),
            Website::InnitDotCom => todo!(),
            Website::InsanelyGoodRecipesDotCom => todo!(),
            Website::InspiralizedDotCom => todo!(),
            Website::InstantPotDotCom => todo!(),
            Website::JamieOliverDotCom => todo!(),
            Website::JaimysKitchenDotNl => todo!(),
            Website::JarofLemonsDotCom => todo!(),
            Website::JimCooksFoodGoodDotCom => todo!(),
            Website::JoCooksDotCom => todo!(),
            Website::JoyFoodSunshineDotCom => todo!(),
            Website::JoyTheBakerDotCom => todo!(),
            Website::JulieGoodwinDotComDotAu => todo!(),
            Website::JumboDotCom => todo!(),
            Website::JustATasteDotCom => todo!(),
            Website::JustBentoDotCom => todo!(),
            Website::JustOneCookBookDotCom => todo!(),
            Website::KeepinItKindDotCom => todo!(),
            Website::KennyMcGovernDotCom => todo!(),
            Website::KingArthurBakingDotCom => todo!(),
            Website::KitchenAidDotComDotAu => todo!(),
            Website::KitchenSanctuaryDotCom => todo!(),
            Website::KitchenStoriesDotCom => todo!(),
            Website::KochbarDotDe => todo!(),
            Website::KochbucherDotCom => todo!(),
            Website::KoketDotSe => todo!(),
            Website::KookjijDotNl => todo!(),
            Website::KptnCookDotCom => todo!(),
            Website::KristinesKitchenBlogDotCom => todo!(),
            Website::KuchniaDomowaDotPl => todo!(),
            Website::KuchynalidlaDotSk => todo!(),
            Website::KwestiasmakuDotCom => todo!(),
            Website::LahbcoDotCom => todo!(),
            Website::LatelierDeRoxaneDotCom => todo!(),
            Website::LeanAndGreenRecipesDotNet => todo!(),
            Website::LeckerDotDe => todo!(),
            Website::LeCremeDeLaCrumbDotCom => todo!(),
            Website::LekkerenSimpelDotCom => todo!(),
            Website::LeukeReceptenDotNl => todo!(),
            Website::LifestyleOfAFoodieDotCom => todo!(),
            Website::LidlDotNl => todo!(),
            Website::LidlKochenDotDe => todo!(),
            Website::LithuanianInTheUsaDotCom => todo!(),
            Website::LittleSpiceJarDotCom => todo!(),
            Website::LivelyTableDotCom => todo!(),
            Website::LivingTheGreenLifeDotCom => todo!(),
            Website::LoveAndLemonsDotCom => todo!(),
            Website::LovingItVeganDotCom => todo!(),
            Website::MaangchiDotCom => todo!(),
            Website::MadensVerdenDotdk => todo!(),
            Website::MadsvinDotCom => todo!(),
            Website::MarmitonDotOrg => todo!(),
            Website::MarthaStewartDotCom => todo!(),
            Website::MatpratDotNo => todo!(),
            Website::McCormickDotCom => todo!(),
            Website::MeljoulwanDotCom => todo!(),
            Website::MelsKitchenCafeDotCom => todo!(),
            Website::MexicanMadeMeatlessDotCom => todo!(),
            Website::MindmegetteDotHu => todo!(),
            Website::MinimalistBakerDotCom => todo!(),
            Website::MinistryOfCurryDotCom => todo!(),
            Website::MisyaDotInfo => todo!(),
            Website::ModernHoneyDotCom => todo!(),
            Website::MomonTimeoutDotCom => todo!(),
            Website::MomsDishDotCom => todo!(),
            Website::MomsWithCrockpotsDotCom => todo!(),
            Website::MotherThymeDotCom => todo!(),
            Website::MoulinexDotFr => todo!(),
            Website::MundoDeReceitasBimbyDotComDotPt => todo!(),
            Website::MyBakingAddictionDotCom => todo!(),
            Website::MyJewishLearningDotCom => todo!(),
            Website::MyKitchen101DotCom => todo!(),
            Website::MyKoreanKitchenDotCom => todo!(),
            Website::MyGingerGarlicKitchenDotCom => todo!(),
            Website::MyKitchen101enDotCom => todo!(),
            Website::MyPlateDotGov => todo!(),
            Website::MyRecipesDotCom => todo!(),
            Website::NatashasKitchenDotCom => todo!(),
            Website::NigellaDotCom => todo!(),
            Website::NinjaTestKitchenDotEu => todo!(),
            Website::NourishedByNutritionDotCom => todo!(),
            Website::NosaltyDotHu => todo!(),
            Website::NotEnoughCinnamonDotCom => todo!(),
            Website::NrkDotNo => todo!(),
            Website::Number2PencilDotCom => todo!(),
            Website::NutritionFactsDotOrg => todo!(),
            Website::NyTimesDotCom => todo!(),
            Website::OhSheGlowsDotCom => todo!(),
            Website::OkokoReceptenDotNl => todo!(),
            Website::OmnivoresCookbookDotCom => todo!(),
            Website::OnceUponAChefDotCom => todo!(),
            Website::OhMyVeggiesDotCom => todo!(),
            Website::OneSweetAppetiteDotCom => todo!(),
            Website::OwenHanDotCom => todo!(),
            Website::PaleoRunningMommaDotCom => todo!(),
            Website::PanelinhaDotComDotBr => todo!(),
            Website::PaniniHappyDotCom => todo!(),
            Website::ParsleyAndParmDotCom => todo!(),
            Website::PersnicketyPlatesDotCom => todo!(),
            Website::PickupLimesDotCom => todo!(),
            Website::PinchOfYumDotCom => todo!(),
            Website::PinkOwlKitchenDotCom => todo!(),
            Website::PingoDoceDotPt => todo!(),
            Website::PlatingPixelsDotCom => todo!(),
            Website::PlentyVeganDotCom => todo!(),
            Website::PloetzBlogDotDe => todo!(),
            Website::PlowingThroughLifeDotCom => todo!(),
            Website::PopSugarDotCoDotUk => todo!(),
            Website::PotatoRollsDotGom => todo!(),
            Website::PracticalSelfRelianceDotCom => todo!(),
            Website::PressureLuckCookingDotCom => todo!(),
            Website::PrimalEdgeHealthDotCom => todo!(),
            Website::ProjectGezondDotNl => todo!(),
            Website::PrzepisyDotPl => todo!(),
            Website::PurelyPopeDotCom => todo!(),
            Website::PureWowDotCom => todo!(),
            Website::PurpleCarrotDotCom => todo!(),
            Website::PuurgezondDotNl => todo!(),
            Website::QuitoqueDotFr => todo!(),
            Website::RachlmansFieldDotCom => todo!(),
            Website::RadioFranceDotFr => todo!(),
            Website::RainbowPlantLifeDotCom => todo!(),
            Website::RealSimpleDotCom => todo!(),
            Website::ReceitasNestleDotComDotBr => todo!(),
            Website::RecettesDotQcDotCa => todo!(),
            Website::RecipeGirlDotCom => todo!(),
            Website::RecipeRunnerDotCom => todo!(),
            Website::RecipeTinEatsDotCom => todo!(),
            Website::RedditDotCom => todo!(),
            Website::RedhouseSpiceDotCom => todo!(),
            Website::ReisHungerDotDe => todo!(),
            Website::RezeptWeltDotDe => todo!(),
            Website::RicettaDotIt => todo!(),
            Website::RicettePerBimbyDotIt => todo!(),
            Website::RobinasBellDotCom => todo!(),
            Website::RosannaPansinoDotCom => todo!(),
            Website::RutgerbaktDotNl => todo!(),
            Website::RecipeCommunityDotComDotAu => todo!(),
            Website::SaboresaJinomotoDotComDotBr => todo!(),
            Website::SallysBakingAddictionDotCom => todo!(),
            Website::SallysBlogDotDe => todo!(),
            Website::SaltAndLavenderDotCom => todo!(),
            Website::SaltPepperSkilletDotCom => todo!(),
            Website::SarahsVeganGuideDotCom => todo!(),
            Website::SaveurDotCom => todo!(),
            Website::SavoryNothingsDotCom => todo!(),
            Website::SeriousEatsDotCom => todo!(),
            Website::SimpleVeganistaDotCom => todo!(),
            Website::SimplyCookitDotCom => todo!(),
            Website::SimplyQuinoaDotCom => todo!(),
            Website::SimplyRecipesDotCom => todo!(),
            Website::SimplyWhiskedDotCom => todo!(),
            Website::SkinnyTasteDotCom => todo!(),
            Website::SmittenKitchenDotCom => todo!(),
            Website::SoborsDotHu => todo!(),
            Website::SouthernCastIronDotCom => todo!(),
            Website::SouthernLivingDotCom => todo!(),
            Website::SpendWithPenniesDotCom => todo!(),
            Website::SpiceboxTravelsDotCom => todo!(),
            Website::StaySnatchedDotCom => todo!(),
            Website::SteamyKitchenDotCom => todo!(),
            Website::StreetKitchenDotCo => todo!(),
            Website::StrongrFastrDotCom => todo!(),
            Website::SunBasketDotCom => todo!(),
            Website::SundPaabudgetDotdk => todo!(),
            Website::SunsetDotCom => todo!(),
            Website::SweetcsDesignsDotCom => todo!(),
            Website::SweetPeasAndSaffronDotCom => todo!(),
            Website::TasteAtlasDotCom => todo!(),
            Website::TasteOfHomeDotCom => todo!(),
            Website::TastesBetterFromScratchDotCom => todo!(),
            Website::TastesOfLizzyTDotCom => todo!(),
            Website::TastyDotCo => todo!(),
            Website::TastyKitchenDotCom => todo!(),
            Website::TescoDotCom => todo!(),
            Website::ThatVeganDadDotNet => todo!(),
            Website::TheCleverCarrotDotCom => todo!(),
            Website::TheCookieRookieDotCom => todo!(),
            Website::TheCookingGuyDotCom => todo!(),
            Website::TheExpertGuidesDotCom => todo!(),
            Website::TheFoodFlamingoDotCom => todo!(),
            Website::TheGucchaDotCom => todo!(),
            Website::TheHappyFoodieDotCoDotUk => todo!(),
            Website::TheHeartySoulDotCom => todo!(),
            Website::TheKitchenCommunityDotOrg => todo!(),
            Website::TheKitchenMagPieDotCom => todo!(),
            Website::TheKitchnDotCom => todo!(),
            Website::TheMagicalSlowCookerDotCom => todo!(),
            Website::TheNutritiousKitchenDotCo => todo!(),
            Website::TheModernProperDotCom => todo!(),
            Website::ThePalatableLifeDotCom => todo!(),
            Website::ThePioneerWomanDotCom => todo!(),
            Website::TheRecipeCriticDotCom => todo!(),
            Website::TheSaltyMarshmallowDotCom => todo!(),
            Website::TheSpruceEatsDotCom => todo!(),
            Website::TheVintageMixerDotCom => todo!(),
            Website::TheWoksOfLifeDotCom => todo!(),
            Website::ThinliciousDotCom => todo!(),
            Website::TidyMomDotNet => todo!(),
            Website::TimesOfIndiaDotCom => todo!(),
            Website::TineDotNo => todo!(),
            Website::TudogostosoDotComDotBr => todo!(),
            Website::TwoPeasAndTheirPodDotCom => todo!(),
            Website::TwoSleeversDotCom => todo!(),
            Website::UitPaulinesKeukenDotNl => todo!(),
            Website::UnsophistiCookDotCom => todo!(),
            Website::UsaPearsDotOrg => todo!(),
            Website::ValdemarsroDotdk => todo!(),
            Website::VanillaAndBeanDotCom => todo!(),
            Website::VeganPratiqueDotFr => todo!(),
            Website::VegetarBloggenDotNo => todo!(),
            Website::VegolosiDotIt => todo!(),
            Website::VegRecipesOfIndiaDotCom => todo!(),
            Website::WaitRoseDotCom => todo!(),
            Website::WatchWhatUEatDotCom => todo!(),
            Website::WeAreNotMarthaDotCom => todo!(),
            Website::WeightWatchersDotCom => todo!(),
            Website::WellPlatedDotCom => todo!(),
            Website::WhatsGabyCookingDotCom => todo!(),
            Website::WholeFoodsMarketDotCoDotUk => todo!(),
            Website::WikibooksDotOrg => todo!(),
            Website::WikibooksDotOrgMobile => todo!(),
            Website::WomensWeeklyFoodDotComDotAu => todo!(),
            Website::WoopDotCoDotNz => todo!(),
            Website::YeMekDotNet => todo!(),
            Website::YumeliseDotFr => todo!(),
            Website::ZaatarAndZaytounDotCom => custom::parse_zaatar_and_zaytoun_dot_com(doc, url),
            Website::ZabihaHalal => unimplemented!(),
            Website::ZeitDotDe => todo!(),
            Website::ZenbellyDotCom => todo!(),
        }
    }
}

impl std::fmt::Display for Website {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.domain())
    }
}
