CREATE TABLE bold_indices_instructions (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    instruction_id int8 NOT NULL REFERENCES instructions (id) ON DELETE CASCADE,
    start_index int4 NOT NULL,
    end_index int4 NOT NULL,
    CHECK (end_index > start_index),
    UNIQUE (recipe_id, instruction_id, start_index, end_index)
);
