---
--- Main tables
---
CREATE TABLE nutrition (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_precalculated_by_source bool NOT NULL DEFAULT FALSE,
    calories_kcal int2 DEFAULT 0,
    total_carbohydrates float DEFAULT 0,
    sugars_g float DEFAULT 0,
    protein_g float DEFAULT 0,
    total_fat_g float DEFAULT 0,
    saturated_fat_g float DEFAULT 0,
    unsaturated_fat_g float DEFAULT 0,
    cholesterol_mg float DEFAULT 0,
    sodium_mg float DEFAULT 0,
    fiber_g float DEFAULT 0,
    trans_fat_g float DEFAULT 0
);

CREATE TABLE nutrition_sources (
    id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    url text NOT NULL,
    country text NOT NULL,
    created_on date NOT NULL DEFAULT CURRENT_DATE,
    updated_on date,
    UNIQUE (name, country)
);

CREATE TABLE fdc_foods (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_class text NOT NULL,
    description text NOT NULL,
    food_category text NOT NULL,
    fdc_id int8 NOT NULL,
    description_tsv tsvector GENERATED ALWAYS AS (to_tsvector('english', description)) STORED,
    UNIQUE (food_class, description)
);

CREATE TABLE fdc_nutrients (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fdc_id int8 NOT NULL,
    name text NOT NULL,
    unit_name text NOT NULL,
    UNIQUE (name, unit_name)
);

---
--- Association tables
---
CREATE TABLE fdc_foods_fdc_nutrients (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id int8 NOT NULL REFERENCES fdc_foods (id) ON DELETE CASCADE,
    nutrient_id int8 NOT NULL REFERENCES fdc_nutrients (id) ON DELETE CASCADE,
    amount float NOT NULL,
    min float,
    max float,
    UNIQUE (food_id, nutrient_id)
);

CREATE TABLE fdc_food_portions (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value float NOT NULL,
    modifier text NOT NULL,
    gram_weight float NOT NULL,
    amount float NOT NULL
);

CREATE TABLE fdc_food_portions_fdc_foods (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id int8 NOT NULL REFERENCES fdc_foods (id) ON DELETE CASCADE,
    portion_id int8 NOT NULL REFERENCES fdc_food_portions (id) ON DELETE CASCADE,
    UNIQUE (food_id, portion_id)
);

---
--- Indexes
---
CREATE INDEX idx_fdc_foods_description_fts ON fdc_foods USING gin (description_tsv);

---
--- Functions
---
CREATE OR REPLACE FUNCTION update_nutrition_sources_updated_on_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    UPDATE
        nutrition_sources
    SET
        updated_on = now()
    WHERE
        name = 'USDA FoodData Central';
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER update_nutrition_sources_updated_on
    AFTER INSERT OR UPDATE ON fdc_foods
    FOR EACH STATEMENT
    EXECUTE FUNCTION update_nutrition_sources_updated_on_column ();

---
--- Inserts
---
INSERT INTO nutrition_sources (name, description, url, country)
    VALUES ('USDA FoodData Central', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', 'United States');

