---
--- Main tables
---
CREATE TABLE shopping_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  num_items int8 NOT NULL DEFAULT 0,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shopping_list_labels (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE users_shopping_list_labels (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  label_id int8 NOT NULL REFERENCES shopping_list_labels (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, label_id)
);

CREATE TABLE shopping_list_items (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopping_list_id uuid NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
  ingredient text NOT NULL CHECK (trim(ingredient) <> ''),
  quantity text CHECK (trim(quantity) <> ''),
  shopping_list_label_id int8 NOT NULL DEFAULT 1 REFERENCES shopping_list_labels (id) ON DELETE SET DEFAULT,
  position int4 NOT NULL DEFAULT 0 CHECK (position >= 0),
  is_checked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shopping_list_recipes (
  shopping_list_item_id int8 NOT NULL REFERENCES shopping_list_items (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (shopping_list_item_id, recipe_id)
);

CREATE TABLE shares_shopping_lists (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  list_id uuid NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP + interval '7 days'),
  last_accessed timestamptz NOT NULL DEFAULT now(),
  click_count int NOT NULL DEFAULT 0,
  UNIQUE (user_id, list_id)
);

CREATE UNIQUE INDEX uq_shopping_list_labels_name ON shopping_list_labels (lower(name));

CREATE UNIQUE INDEX uq_shopping_lists_user_name ON shopping_lists (user_id, lower(name));

CREATE UNIQUE INDEX ui_shopping_list_items_ingredient_labeled ON shopping_list_items (
  shopping_list_id,
  lower(ingredient),
  shopping_list_label_id
)
WHERE
  shopping_list_label_id IS NOT NULL;

CREATE UNIQUE INDEX uix_shopping_list_items_ingredient_unlabeled ON shopping_list_items (shopping_list_id, lower(ingredient))
WHERE
  shopping_list_label_id IS NULL;

---
--- Indexes
---
CREATE INDEX idx_shopping_list_items_shopping_list_label_id ON shopping_list_items (shopping_list_label_id);

CREATE INDEX idx_shopping_list_recipes_recipe_id ON shopping_list_recipes (recipe_id);

CREATE INDEX idx_shopping_list_items_list_order ON shopping_list_items (shopping_list_id, position);

---
--- Cron Jobs
---
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.schedule(
      'delete_expired_shares_shopping_lists',
      '0 0 * * *',
      'DELETE FROM shares_shopping_lists WHERE expires_at < NOW()'
    );
  END IF;
END;
$$;

---
--- Inserts
---
INSERT INTO
  shopping_list_labels (name)
VALUES
  ('No label');

---
--- Functions
---
CREATE FUNCTION update_shopping_list_items_position () RETURNS TRIGGER AS $$
BEGIN
  NEW.position := (
    SELECT COALESCE(MAX(position), 0) + 1
    FROM shopping_list_items
    WHERE shopping_list_id = NEW.shopping_list_id
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION update_shopping_list_num_items () RETURNS TRIGGER AS $$
BEGIN
  UPDATE shopping_lists
  SET num_items = (
    SELECT COUNT(*)
    FROM shopping_list_items
    WHERE shopping_list_id = NEW.shopping_list_id
  )
  WHERE id = NEW.shopping_list_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER update_shopping_lists_updated_at BEFORE
UPDATE ON shopping_lists FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_shopping_list_items_updated_at BEFORE
UPDATE ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_shopping_list_items_position BEFORE INSERT ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_shopping_list_items_position ();

CREATE TRIGGER update_shopping_list_num_items
AFTER INSERT
OR
UPDATE ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_shopping_list_num_items ();
