---
--- Main tables
---
CREATE TABLE shopping_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  num_items int8 NOT NULL DEFAULT 0,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shopping_list_labels (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE users_shopping_list_labels (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  label_id int8 NOT NULL REFERENCES shopping_list_labels (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, label_id)
);

CREATE TABLE shopping_list_items (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopping_list_id uuid NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
  ingredient text NOT NULL CHECK (trim(ingredient) <> ''),
  quantity text CHECK (trim(quantity) <> ''),
  notes text,
  shopping_list_label_id int8 NOT NULL DEFAULT 1 REFERENCES shopping_list_labels (id) ON DELETE SET DEFAULT,
  position int4 NOT NULL DEFAULT 0 CHECK (position >= 0),
  is_checked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shopping_list_recipes (
  shopping_list_item_id int8 NOT NULL REFERENCES shopping_list_items (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (shopping_list_item_id, recipe_id)
);

CREATE TABLE shares_shopping_lists (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  list_id uuid NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP + interval '7 days'),
  last_accessed timestamptz NOT NULL DEFAULT now(),
  click_count int NOT NULL DEFAULT 0,
  UNIQUE (user_id, list_id)
);

CREATE TABLE paper_categories (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE paper_sizes (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_category_id int2 NOT NULL REFERENCES paper_categories (id) ON DELETE CASCADE,
  name text NOT NULL,
  height_mm float NOT NULL,
  width_mm float NOT NULL,
  height_in float NOT NULL,
  width_in float NOT NULL
);

---
--- Indexes
---
CREATE UNIQUE INDEX uq_shopping_list_labels_name ON shopping_list_labels (lower(name));

CREATE UNIQUE INDEX uq_shopping_lists_user_name ON shopping_lists (user_id, lower(name));

CREATE UNIQUE INDEX ui_shopping_list_items_ingredient_labeled ON shopping_list_items (
  shopping_list_id,
  lower(ingredient),
  shopping_list_label_id
)
WHERE
  shopping_list_label_id IS NOT NULL;

CREATE UNIQUE INDEX uix_shopping_list_items_ingredient_unlabeled ON shopping_list_items (shopping_list_id, lower(ingredient))
WHERE
  shopping_list_label_id IS NULL;

CREATE INDEX idx_shopping_list_items_shopping_list_label_id ON shopping_list_items (shopping_list_label_id);

CREATE INDEX idx_shopping_list_recipes_recipe_id ON shopping_list_recipes (recipe_id);

CREATE INDEX idx_shopping_list_items_list_order ON shopping_list_items (shopping_list_id, position);

---
--- Cron Jobs
---
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.schedule(
      'delete_expired_shares_shopping_lists',
      '0 0 * * *',
      'DELETE FROM shares_shopping_lists WHERE expires_at < NOW()'
    );
  END IF;
END;
$$;

---
--- Functions
---
CREATE FUNCTION update_shopping_list_items_position () RETURNS TRIGGER AS $$
BEGIN
  NEW.position := (
    SELECT COALESCE(MAX(position), 0) + 1
    FROM shopping_list_items
    WHERE shopping_list_id = NEW.shopping_list_id
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_shopping_list_num_items () RETURNS TRIGGER AS $$
DECLARE
  list_id UUID;
BEGIN
  IF TG_OP = 'DELETE' THEN
    list_id := OLD.shopping_list_id;
  ELSE
    list_id := NEW.shopping_list_id;
  END IF;

  UPDATE shopping_lists
  SET num_items = (
    SELECT COUNT(*)
    FROM shopping_list_items
    WHERE shopping_list_id = list_id
  )
  WHERE id = list_id;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_default_paper_size_id () RETURNS int2 AS $$
  SELECT id
    FROM paper_sizes
    WHERE name = 'US Letter'
    LIMIT 1;
$$ LANGUAGE sql STABLE;

---
--- Triggers
---
CREATE TRIGGER update_shopping_lists_updated_at BEFORE
UPDATE ON shopping_lists FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_shopping_list_items_updated_at BEFORE
UPDATE ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_shopping_list_items_position BEFORE INSERT ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_shopping_list_items_position ();

CREATE TRIGGER update_shopping_list_num_items
AFTER INSERT
OR
UPDATE
OR DELETE ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_shopping_list_num_items ();

---
--- Inserts
---
INSERT INTO
  shopping_list_labels (name)
VALUES
  ('No label');

INSERT INTO
  paper_categories (name)
VALUES
  ('Standard US Sizes'),
  ('US Envelope Sizes'),
  ('ISO Envelopes'),
  ('ISO A Sizes'),
  ('ISO B Sizes'),
  ('ISO C Sizes'),
  ('North American ANSI Sizes'),
  ('North American ARCH Sizes');

WITH
  cats AS (
    SELECT
      id,
      name
    FROM
      paper_categories
  )
INSERT INTO
  paper_sizes (
    paper_category_id,
    name,
    width_mm,
    height_mm,
    width_in,
    height_in
  )
SELECT
  c.id,
  v.name,
  v.width_mm,
  v.height_mm,
  ROUND((v.width_mm / 25.4)::numeric, 4)::float,
  ROUND((v.height_mm / 25.4)::numeric, 4)::float
FROM
  (
    VALUES
      ('Standard US Sizes', 'US Letter', 216.0, 279.0),
      ('Standard US Sizes', 'US Legal', 215.9, 355.6),
      ('Standard US Sizes', 'US Tabloid', 279.0, 432.0),
      ('Standard US Sizes', 'US Executive', 190.5, 254.0),
      (
        'Standard US Sizes',
        'US Junior Legal',
        203.2,
        127.0
      ),
      (
        'Standard US Sizes',
        'US Half Letter',
        140.0,
        216.0
      ),
      (
        'Standard US Sizes',
        'US Government Letter',
        203.0,
        267.0
      ),
      (
        'Standard US Sizes',
        'US Government Legal',
        216.0,
        330.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope 6¾',
        165.0,
        92.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope 7¾ Monarch',
        191.0,
        98.0
      ),
      ('US Envelope Sizes', 'US Envelope 9', 225.0, 98.0),
      (
        'US Envelope Sizes',
        'US Envelope 10',
        241.0,
        104.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope 11',
        264.0,
        114.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope 14',
        292.0,
        127.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope A2 Lady Grey',
        146.0,
        111.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope A6 Thompsons',
        165.0,
        121.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope A7 Besselheim',
        184.0,
        133.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope A9 Diplomat',
        222.0,
        146.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope 10½',
        305.0,
        229.0
      ),
      (
        'US Envelope Sizes',
        'US Envelope 13½',
        330.0,
        254.0
      ),
      ('ISO Envelopes', 'ISO Envelope DL', 110.0, 220.0),
      ('ISO Envelopes', 'ISO Envelope B4', 250.0, 353.0),
      ('ISO Envelopes', 'ISO Envelope B5', 176.0, 250.0),
      ('ISO Envelopes', 'ISO Envelope B6', 125.0, 176.0),
      ('ISO Envelopes', 'ISO Envelope C3', 324.0, 458.0),
      ('ISO Envelopes', 'ISO Envelope C4', 229.0, 324.0),
      ('ISO Envelopes', 'ISO Envelope C4M', 318.0, 229.0),
      ('ISO Envelopes', 'ISO Envelope C5', 162.0, 229.0),
      ('ISO Envelopes', 'ISO Envelope C6', 114.0, 162.0),
      ('ISO Envelopes', 'ISO Envelope C7', 81.0, 114.0),
      ('ISO Envelopes', 'ISO Envelope R7', 120.0, 135.0),
      ('ISO Envelopes', 'ISO Envelope S4', 250.0, 330.0),
      ('ISO Envelopes', 'ISO Envelope S5', 185.0, 255.0),
      ('ISO A Sizes', 'ISO A0', 841.0, 1189.0),
      ('ISO A Sizes', 'ISO A1', 594.0, 841.0),
      ('ISO A Sizes', 'ISO A2', 420.0, 594.0),
      ('ISO A Sizes', 'ISO A3', 297.0, 420.0),
      ('ISO A Sizes', 'ISO A4', 210.0, 297.0),
      ('ISO A Sizes', 'ISO A5', 148.0, 210.0),
      ('ISO A Sizes', 'ISO A6', 105.0, 148.0),
      ('ISO A Sizes', 'ISO A7', 74.0, 105.0),
      ('ISO A Sizes', 'ISO A8', 52.0, 74.0),
      ('ISO A Sizes', 'ISO A9', 37.0, 52.0),
      ('ISO A Sizes', 'ISO A10', 26.0, 37.0),
      ('ISO A Sizes', 'ISO A11', 18.0, 24.0),
      ('ISO A Sizes', 'ISO A12', 13.0, 18.0),
      ('ISO A Sizes', 'ISO A13', 9.0, 13.0),
      ('ISO A Sizes', 'ISO 2A0', 1189.0, 1682.0),
      ('ISO A Sizes', 'ISO 4A0', 1682.0, 2378.0),
      ('ISO A Sizes', 'ISO A0+', 914.0, 1292.0),
      ('ISO A Sizes', 'ISO A1+', 609.0, 914.0),
      ('ISO A Sizes', 'ISO A3+', 329.0, 483.0),
      ('ISO B Sizes', 'ISO B0', 1000.0, 1414.0),
      ('ISO B Sizes', 'ISO B1', 707.0, 1000.0),
      ('ISO B Sizes', 'ISO B2', 500.0, 707.0),
      ('ISO B Sizes', 'ISO B3', 353.0, 500.0),
      ('ISO B Sizes', 'ISO B4', 250.0, 353.0),
      ('ISO B Sizes', 'ISO B5', 176.0, 250.0),
      ('ISO B Sizes', 'ISO B6', 125.0, 176.0),
      ('ISO B Sizes', 'ISO B7', 88.0, 125.0),
      ('ISO B Sizes', 'ISO B8', 62.0, 88.0),
      ('ISO B Sizes', 'ISO B0+', 1118.0, 1580.0),
      ('ISO B Sizes', 'ISO B1+', 720.0, 1020.0),
      ('ISO B Sizes', 'ISO B2+', 520.0, 720.0),
      ('ISO C Sizes', 'ISO C0', 917.0, 1297.0),
      ('ISO C Sizes', 'ISO C1', 648.0, 917.0),
      ('ISO C Sizes', 'ISO C2', 458.0, 648.0),
      ('ISO C Sizes', 'ISO C3', 324.0, 458.0),
      ('ISO C Sizes', 'ISO C4', 229.0, 324.0),
      ('ISO C Sizes', 'ISO C5', 162.0, 229.0),
      ('ISO C Sizes', 'ISO C6', 114.0, 162.0),
      (
        'North American ANSI Sizes',
        'ANSI E',
        1118.0,
        864.0
      ),
      (
        'North American ANSI Sizes',
        'ANSI D',
        559.0,
        864.0
      ),
      (
        'North American ANSI Sizes',
        'ANSI C',
        432.0,
        559.0
      ),
      (
        'North American ANSI Sizes',
        'ANSI B',
        279.0,
        432.0
      ),
      (
        'North American ANSI Sizes',
        'ANSI A',
        216.0,
        279.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH E3',
        686.0,
        991.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH E2',
        660.0,
        965.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH E1',
        762.0,
        1067.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH E',
        1914.0,
        1219.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH D',
        610.0,
        914.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH C',
        457.0,
        610.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH B',
        305.0,
        457.0
      ),
      (
        'North American ARCH Sizes',
        'ARCH A',
        229.0,
        305.0
      )
  ) AS v (category_name, name, width_mm, height_mm)
  JOIN cats c ON c.name = v.category_name;

---
--- Alters
---
ALTER TABLE user_settings
ADD COLUMN paper_size_id int2 NOT NULL DEFAULT get_default_paper_size_id ();
