---
--- Main tables
---
CREATE TABLE shopping_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shopping_list_labels (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE users_shopping_list_labels (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  label_id int8 NOT NULL REFERENCES shopping_list_labels (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, label_id)
);

CREATE TABLE shopping_list_items (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopping_list_id uuid NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
  ingredient text NOT NULL CHECK (trim(ingredient) <> ''),
  quantity text NOT NULL CHECK (trim(quantity) <> ''),
  shopping_list_label_id int8 REFERENCES shopping_list_labels (id) ON DELETE SET NULL,
  position int4 NOT NULL DEFAULT 0 CHECK (position >= 0),
  is_checked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shopping_list_recipes (
  shopping_list_item_id int8 NOT NULL REFERENCES shopping_list_items (id) ON DELETE CASCADE,
  recipe_id int8 NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  PRIMARY KEY (shopping_list_item_id, recipe_id)
);

CREATE UNIQUE INDEX uq_shopping_list_labels_name_ci ON shopping_list_labels (lower(name));

CREATE UNIQUE INDEX uq_shopping_lists_user_name_ci ON shopping_lists (user_id, lower(name));

---
--- Indexes
---
CREATE INDEX idx_shopping_list_items_shopping_list_label_id ON shopping_list_items (shopping_list_label_id);

CREATE INDEX idx_shopping_list_recipes_recipe_id ON shopping_list_recipes (recipe_id);

CREATE INDEX idx_shopping_list_items_list_order ON shopping_list_items (shopping_list_id, position);

---
--- Functions
---
CREATE FUNCTION update_shopping_list_items_position () RETURNS TRIGGER AS $$
BEGIN
  NEW.position := (
    SELECT COALESCE(MAX(position), 0) + 1
    FROM shopping_list_items
    WHERE shopping_list_id = NEW.shopping_list_id
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER update_shopping_lists_updated_at BEFORE
UPDATE ON shopping_lists FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_shopping_list_items_updated_at BEFORE
UPDATE ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column ();

CREATE TRIGGER update_shopping_list_items_position BEFORE INSERT ON shopping_list_items FOR EACH ROW
EXECUTE FUNCTION update_shopping_list_items_position ();
