services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/recipya_test
    network_mode: host

  db:
    container_name: recipya-rs-db
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: recipya_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
