# Cargo config file. 
# See: https://doc.rust-lang.org/cargo/reference/config.html

[env]
RUST_LOG = "recipya=debug,lib_core=debug,lib_web=debug,lib_auth=debug,lib_utils=debug"

DATABASE_URL = "postgres://postgres:postgres@localhost:5432/recipya"

SERVICE_EMAIL_FROM = "example@test.com"
SERVICE_EMAIL_SENDGRID_API_KEY = "YOUR_API_KEY"

SERVICE_INTEGRATIONS_AZURE_DI_ENDPOINT = ""
SERVICE_INTEGRATIONS_AZURE_DI_KEY = ""

SERVICE_ADDRESS_URL = "http://0.0.0.0:7324"
SERVICE_AUTOLOGIN = "false"
SERVICE_BYPASS_GUIDE = "false"
SERVICE_DEMO = "false"
SERVICE_NO_SIGNUPS = "false"
SERVICE_PRODUCTION = "false"

# Run `cargo run -p recipya-genkey` twice and paste the b64u encoded keys, once for the password and the other the token.
SERVICE_PASSWORD_KEY = "CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
SERVICE_TOKEN_KEY = "MN2z8mZgRymm0iojkVm1zkhnAXgXyhRdl6R2ODWST8LOIGS1ImV6sUvEDUncc0izt9xCzju2sGcEdGfSj23B0w"
SERVICE_TOKEN_DURATION_SEC = "1800"

SERVICE_DOCS_FOLDER = "web/docs/public"
SERVICE_WEB_FOLDER = "web/static"
