"""
-- Disclaimer Start --

AI usage:
This whole file, exluding this disclaimer, is slop generated by Claude Sonnet 5.5.
Reason is I wanted to translate all locales using a local LLM model without copy-pasting every value in Google Translate.

To run on your local machine:
1. Install llama.cpp: https://llama.app/
2. Run the llama server with the Index -Translate-35B-A3B-preview-GGUP (https://huggingface.co/IndexTeam/Index-Translate-35B-A3B-preview-GGUF) LLM model: `llama serve -hf IndexTeam/Index-Translate-35B-A3B-preview-GGUF:Q4_K_M`
3. Activate a virtual environment:
```bash
python -m venv venv
. venv/bin/activate
pip install fluent.syntax babel
```
5. Run the the script: `python translate_ftl.py`

-- Disclaimer End --

Translate Project Fluent (.ftl) files with a local llama.cpp server.

Layout expected:
    crates/l10n/en-CA/*.ftl      <- reference (English)
    crates/l10n/fr/*.ftl         <- copies of en-CA, not yet translated
    crates/l10n/ja/*.ftl
    ...

How it works:
  * Parses every file with fluent.syntax (official parser).
  * An entry in a locale file that is IDENTICAL to the en-CA entry is treated as
    "untranslated" and sent to the model (use --force to redo everything).
    Entries that already differ from en-CA are left alone.
  * Entries missing from a locale file are added from en-CA and translated.
  * A cache (.translate-cache.json, next to this script) records the en-CA text each entry was
    translated from. Entries translated by this script are never re-sent unless
    the en-CA entry (text or comment) changes, which also re-translates stale
    translations. Use --no-cache to ignore it, or delete a locale's key in the
    JSON file to redo that locale. Commit the cache file to share it.
  * The model translates one whole entry at a time (so it can adapt plural
    selectors), then the result is re-parsed and validated:
        - same identifier, same attribute names
        - same $variables, -terms, message references, functions
        - plural selector keys valid for the target language (needs `babel`)
        - non-plural selector keys unchanged
    On failure the error is fed back to the model and it retries; if it still
    fails, the English entry is kept and the failure is reported.
  * Comments are kept as-is (English).

Setup:
    pip install fluent.syntax babel
    llama-server -m your-model.gguf -c 8192 -np 4 --port 8080

Run:
    python translate_ftl.py --root crates/l10n --reference en-CA --workers 4
    python translate_ftl.py --locales fr de ja --dry-run

Note: files that get changed are re-serialized by fluent.syntax, so formatting
may be normalized slightly (whitespace/indentation) compared to the original.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import sys
import threading
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from babel import Locale, UnknownLocaleError  # type: ignore
from fluent.syntax import FluentParser, FluentSerializer, ast  # type: ignore
from fluent.syntax.visitor import Visitor  # type: ignore

SCRIPT_DIR = Path(__file__).resolve().parent
PARSER = FluentParser(with_spans=False)
SERIALIZER = FluentSerializer(with_junk=True)
CLDR_ORDER = ["zero", "one", "two", "few", "many", "other"]
LOG_LOCK = threading.Lock()


def log(msg: str) -> None:
    with LOG_LOCK:
        print(msg, flush=True)


# --------------------------------------------------------------------------- #
# AST helpers
# --------------------------------------------------------------------------- #
class Collector(Visitor):
    """Collects everything that must survive translation unchanged."""

    def __init__(self) -> None:
        self.vars: set = set()
        self.msg_refs: set = set()
        self.term_refs: set = set()
        self.funcs: set = set()
        self.selects: list = []  # list of lists of (kind, value)
        self.text: list = []

    def visit_VariableReference(self, node):
        self.vars.add(node.id.name)
        self.generic_visit(node)

    def visit_MessageReference(self, node):
        self.msg_refs.add((node.id.name, node.attribute.name if node.attribute else None))
        self.generic_visit(node)

    def visit_TermReference(self, node):
        self.term_refs.add((node.id.name, node.attribute.name if node.attribute else None))
        self.generic_visit(node)

    def visit_FunctionReference(self, node):
        self.funcs.add(node.id.name)
        self.generic_visit(node)

    def visit_SelectExpression(self, node):
        keys = []
        for v in node.variants:
            if isinstance(v.key, ast.Identifier):
                keys.append(("id", v.key.name))
            else:
                keys.append(("num", v.key.value))
        self.selects.append(keys)
        self.generic_visit(node)

    def visit_TextElement(self, node):
        self.text.append(node.value)


def is_entry(node) -> bool:
    return isinstance(node, (ast.Message, ast.Term))


def entry_key(e):
    return ("term" if isinstance(e, ast.Term) else "msg", e.id.name)


def entry_label(e) -> str:
    return ("-" if isinstance(e, ast.Term) else "") + e.id.name


def is_translatable(e) -> bool:
    c = Collector()
    c.visit(e)
    return any(re.search(r"[^\W\d_]", t) for t in c.text)


def entry_hash(e) -> str:
    """Hash of the reference entry (text + attached comment)."""
    return hashlib.sha256(SERIALIZER.serialize_entry(e).encode("utf-8")).hexdigest()[:16]


def load_cache(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except FileNotFoundError:
        return {}
    except (OSError, json.JSONDecodeError) as e:
        log(f"Warning: could not read cache {path} ({e}); starting with an empty cache.")
        return {}


def save_cache(path: Path, cache: dict) -> None:
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(cache, indent=1, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    tmp.replace(path)


# --------------------------------------------------------------------------- #
# Locale info
# --------------------------------------------------------------------------- #
def locale_info(code: str):
    """Return (English language name, plural categories or None)."""
    try:
        loc = Locale.parse(code.replace("-", "_"))
    except (ValueError, UnknownLocaleError):
        return code, None
    cats = set(loc.plural_form.tags) | {"other"}
    name = loc.get_display_name("en") or code
    return name, [c for c in CLDR_ORDER if c in cats]


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #
def parse_single(text: str):
    res = PARSER.parse(text)
    junk = [e for e in res.body if isinstance(e, ast.Junk)]
    if junk:
        ann = junk[0].annotations[0] if junk[0].annotations else None
        detail = f"{ann.code}: {ann.message}" if ann else "unknown error"
        raise ValueError(f"FTL syntax error ({detail})")
    entries = [e for e in res.body if is_entry(e)]
    if len(entries) != 1:
        raise ValueError(f"expected exactly one FTL entry, got {len(entries)}")
    return entries[0]


def validate(src, out, cats) -> None:
    if type(out) is not type(src):
        raise ValueError("entry type changed (message vs term)")
    if out.id.name != src.id.name:
        raise ValueError(f"identifier must stay '{src.id.name}', got '{out.id.name}'")
    if (src.value is None) != (out.value is None):
        raise ValueError("entry value presence changed")
    sa = {a.id.name for a in src.attributes}
    oa = {a.id.name for a in out.attributes}
    if sa != oa:
        raise ValueError(f"attributes must be {sorted(sa)}, got {sorted(oa)}")

    s, o = Collector(), Collector()
    s.visit(src)
    o.visit(out)
    for label, a, b in (
        ("$variables", s.vars, o.vars),
        ("message references", s.msg_refs, o.msg_refs),
        ("term references", s.term_refs, o.term_refs),
        ("functions", s.funcs, o.funcs),
    ):
        if a != b:
            raise ValueError(f"{label} must be {sorted(map(str, a))}, got {sorted(map(str, b))}")

    if len(s.selects) != len(o.selects):
        raise ValueError(f"expected {len(s.selects)} select expression(s), got {len(o.selects)}")
    for ss, oo in zip(s.selects, o.selects):
        src_ids = [v for k, v in ss if k == "id"]
        out_ids = [v for k, v in oo if k == "id"]
        plural = bool(src_ids) and all(i in CLDR_ORDER for i in src_ids)
        if plural:
            if cats:
                bad = [i for i in out_ids if i not in cats]
                if bad:
                    raise ValueError(
                        f"plural variant(s) {bad} are not valid for this language; "
                        f"allowed categories: {cats}"
                    )
        elif set(ss) != set(oo):
            raise ValueError(f"selector variant keys must stay {sorted(v for _, v in ss)}")


# --------------------------------------------------------------------------- #
# LLM
# --------------------------------------------------------------------------- #
SYSTEM_TEMPLATE = """You are a professional software localizer. You translate Project Fluent (.ftl) \
entries from English (Canada) into {lang} (locale code: {code}).

Rules:
1. Output ONLY the translated FTL entry. No code fences, no explanations.
2. Keep the identifier and every attribute name (e.g. `.title`) exactly as in the input. \
Translate only human-readable text.
3. Everything inside {{ }} placeables stays unchanged: $variables, -terms, message references, \
functions and their arguments, string literals. The curly braces are syntax: `{{ $name }}` must \
stay `{{ $name }}` with its braces, even if you add or change quotation marks around it.
4. Select expressions: keep the selector. For plural selectors, write the variants required by \
{lang}{cats_clause}. Add or remove plural variants as the language needs. Keep the `*` default \
marker on exactly one variant (normally `[other]`). For non-plural selectors keep the variant keys \
unchanged and translate only their text.
5. Do not translate brand/product names, URLs, keyboard shortcuts, or text in backticks.
6. Keep the same multi-line structure and indentation style as the input.
7. Use a natural, neutral, polite register suitable for software UI. Follow the typographic \
conventions of {lang} (punctuation, spacing, quotation marks). If you change quotation marks \
around a placeable, keep the braces inside them, e.g. « {{ $name }} », never « $name ».

Example (target French):
Input:
items-selected =
    {{ $count ->
        [one] {{ $count }} item selected
       *[other] {{ $count }} items selected
    }}
Output:
items-selected =
    {{ $count ->
        [one] {{ $count }} élément sélectionné
       *[other] {{ $count }} éléments sélectionnés
    }}"""


def chat(args, messages) -> str:
    body = {
        "messages": messages,
        "temperature": args.temperature,
        "max_tokens": args.max_tokens,
        "chat_template_kwargs": {"enable_thinking": False},  # ignored by non-thinking models
    }
    if args.model:
        body["model"] = args.model
    req = urllib.request.Request(
        args.server.rstrip("/") + "/v1/chat/completions",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=args.timeout) as resp:
        data = json.load(resp)
    return data["choices"][0]["message"]["content"] or ""


def clean_output(text: str) -> str:
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    text = text.strip()
    m = re.match(r"^```[a-zA-Z]*\n(.*?)\n```$", text, flags=re.DOTALL)
    if m:
        text = m.group(1)
    return text.strip()


def translate_entry(args, src, code, lang, cats):
    """Returns (translated_entry | None, error | None)."""
    comment = src.comment.content if src.comment else None
    bare = copy.deepcopy(src)
    bare.comment = None
    source_ftl = SERIALIZER.serialize_entry(bare).strip()

    cats_clause = f" (CLDR categories: {', '.join(cats)})" if cats else " (use its CLDR plural categories)"
    messages = [
        {"role": "system", "content": SYSTEM_TEMPLATE.format(lang=lang, code=code, cats_clause=cats_clause)},
        {
            "role": "user",
            "content": (
                f"Entry identifier: {entry_label(src)}\n"
                f"Translator comment: {comment or '(none)'}\n\n"
                f"Translate this entry:\n\n{source_ftl}"
            ),
        },
    ]

    last_err = None
    last_raw = ""
    for _ in range(args.retries + 1):
        try:
            raw = chat(args, messages)
        except (urllib.error.URLError, TimeoutError, OSError, KeyError, ValueError) as e:
            return None, f"request failed: {e}"
        last_raw = raw
        try:
            out = parse_single(clean_output(raw))
            validate(src, out, cats)
            out.comment = copy.deepcopy(src.comment)
            return out, None
        except ValueError as e:
            last_err = str(e)
            messages.append({"role": "assistant", "content": raw})
            messages.append(
                {"role": "user", "content": f"That output is invalid: {last_err}. Return the corrected FTL entry only."}
            )
    return None, f"{last_err} | last output: {last_raw!r}"


# --------------------------------------------------------------------------- #
# File / locale processing
# --------------------------------------------------------------------------- #
def process_file(args, cache, locale, lang, cats, ref_file: Path, tgt_file: Path, failures: list) -> int:
    rel = ref_file.relative_to(Path(args.root) / args.reference)
    tag = f"[{locale}/{rel}]"

    ref_res = PARSER.parse(ref_file.read_text(encoding="utf-8"))
    tgt_text = tgt_file.read_text(encoding="utf-8") if tgt_file.exists() else ref_file.read_text(encoding="utf-8")
    tgt_res = PARSER.parse(tgt_text)

    ref_map = {entry_key(e): e for e in ref_res.body if is_entry(e)}
    tgt_index = {entry_key(e): i for i, e in enumerate(tgt_res.body) if is_entry(e)}
    hashes = {entry_label(e): entry_hash(e) for e in ref_map.values()}
    file_cache = {} if args.no_cache else cache.get(locale, {}).get(str(rel), {})

    added = 0
    todo = []
    for k, ref_e in ref_map.items():
        label = entry_label(ref_e)
        was_missing = k not in tgt_index
        if was_missing:
            tgt_res.body.append(copy.deepcopy(ref_e))
            tgt_index[k] = len(tgt_res.body) - 1
            added += 1
        tgt_e = tgt_res.body[tgt_index[k]]
        if not args.force and not was_missing:
            cached = file_cache.get(label)
            if cached == hashes[label]:
                continue  # already translated by this script, reference unchanged
            if cached is None and not tgt_e.equals(ref_e):
                continue  # translated outside this script
            # otherwise: untranslated copy, or the reference changed since last time
        if is_translatable(ref_e):
            todo.append(k)

    if not todo and not added:
        log(f"{tag} nothing to do")
        return 0

    done = 0
    new_hashes = {}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futs = {pool.submit(translate_entry, args, ref_map[k], locale, lang, cats): k for k in todo}
        for fut in as_completed(futs):
            k = futs[fut]
            out, err = fut.result()
            label = entry_label(ref_map[k])
            if out is None:
                log(f"{tag} FAILED {label}: {err}")
                failures.append({"locale": locale, "file": str(rel), "id": label, "error": err})
            else:
                tgt_res.body[tgt_index[k]] = out
                new_hashes[label] = hashes[label]
                done += 1
                log(f"{tag} ok {label}")

    if args.dry_run:
        return done

    if done or added:
        tgt_file.parent.mkdir(parents=True, exist_ok=True)
        tgt_file.write_text(SERIALIZER.serialize(tgt_res), encoding="utf-8")
        log(f"{tag} wrote {done} translated, {added} added")
    if not args.no_cache and new_hashes:
        fc = cache.setdefault(locale, {}).setdefault(str(rel), {})
        fc.update(new_hashes)
        for lbl in [l for l in fc if l not in hashes]:
            del fc[lbl]  # entry removed from the reference
        save_cache(args.cache_path, cache)
    return done


def check_server(args) -> None:
    try:
        urllib.request.urlopen(args.server.rstrip("/") + "/health", timeout=10).read()
    except OSError as e:
        sys.exit(f"Cannot reach llama-server at {args.server} ({e}). Start it with: llama-server -m model.gguf --port 8080")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", default=str(SCRIPT_DIR), help="directory holding one folder per locale (default: the script's directory)")
    p.add_argument("--reference", default="en-CA")
    p.add_argument("--server", default="http://127.0.0.1:8080")
    p.add_argument("--model", default=None, help="optional model name sent to the server")
    p.add_argument("--locales", nargs="*", help="only these locales")
    p.add_argument("--skip", nargs="*", default=[], help="locales to skip")
    p.add_argument("--workers", type=int, default=1, help="parallel requests (match llama-server -np)")
    p.add_argument("--retries", type=int, default=2)
    p.add_argument("--temperature", type=float, default=0.2)
    p.add_argument("--max-tokens", type=int, default=1024)
    p.add_argument("--timeout", type=int, default=3000)
    p.add_argument("--force", action="store_true", help="retranslate entries even if they differ from the reference")
    p.add_argument("--dry-run", action="store_true", help="translate but do not write files")
    p.add_argument("--failures-file", default="l10n_failures.json")
    p.add_argument("--cache-file", default=None, help="default: .translate-cache.json next to this script")
    p.add_argument("--no-cache", action="store_true", help="ignore and don't update the cache")
    args = p.parse_args()

    root = Path(args.root)
    args.cache_path = Path(args.cache_file) if args.cache_file else SCRIPT_DIR / ".translate-cache.json"
    ref_dir = root / args.reference
    if not ref_dir.is_dir():
        sys.exit(f"Reference directory not found: {ref_dir}")
    ref_files = sorted(ref_dir.rglob("*.ftl"))
    if not ref_files:
        sys.exit(f"No .ftl files in {ref_dir}")

    locales = sorted(d.name for d in root.iterdir() if d.is_dir() and d.name != args.reference)
    if args.locales:
        locales = [l for l in locales if l in args.locales]
    locales = [l for l in locales if l not in args.skip]
    if not locales:
        sys.exit("No locales to process.")

    check_server(args)

    cache = {} if args.no_cache else load_cache(args.cache_path)
    failures: list = []
    total = 0
    try:
        for locale in locales:
            lang, cats = locale_info(locale)
            log(f"=== {locale} ({lang}) plural categories: {cats or 'unknown'}")
            for ref_file in ref_files:
                tgt_file = root / locale / ref_file.relative_to(ref_dir)
                total += process_file(args, cache, locale, lang, cats, ref_file, tgt_file, failures)
    except KeyboardInterrupt:
        log("Interrupted. Re-run to resume: translated entries are skipped automatically.")

    if failures:
        Path(args.failures_file).write_text(json.dumps(failures, indent=2, ensure_ascii=False), encoding="utf-8")
    log(f"\nDone. {total} entries translated, {len(failures)} failed"
        + (f" (see {args.failures_file})" if failures else ""))


if __name__ == "__main__":
    main()
