[package]
name = "integrations"
version = "0.1.0"
publish = false

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-stream.workspace = true
async-trait.workspace = true
base64.workspace = true
cooklang = "0.17.1"
derive_more.workspace = true
futures = "0.3.31"
futures-core.workspace = true
humantime.workspace = true
iso8601.workspace = true
libpaprika = { version = "0.4.1", default-features = false }
nom.workspace = true
recipemd = "0.2.0"
reqwest = { workspace = true, features = ["json"] }
schema-org.workspace = true
serde.workspace = true
serde-xml-rs = "0.8.2"
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
support.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
winnow = "0.7.13"
zip = "6.0.0"

[dev-dependencies]
pretty_assertions.workspace = true
testing = { path = "../testing", features = ["test-utils"] }
tokio.workspace = true
