[package]
name = "integrations"
version = "0.1.0"
publish = false

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-stream.workspace = true
async-trait.workspace = true
base64.workspace = true
csv = "1.4.0"
cooklang = "0.18.6"
derive_more.workspace = true
encoding_rs.workspace = true
futures.workspace = true
futures-core.workspace = true
humantime.workspace = true
iso8601.workspace = true
libpaprika = { version = "0.4.1", default-features = false }
recipemd = "0.2.0"
reqwest = { workspace = true, features = ["json"] }
schema-org.workspace = true
scraper.workspace = true
serde.workspace = true
serde-xml-rs = "0.8.2"
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
support.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
winnow.workspace = true
zip.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
test-fixtures.workspace = true
test-utils.workspace = true
tokio.workspace = true
tracing-test.workspace = true
