---
--- Tables
---
CREATE TABLE IF NOT EXISTS languages (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale TEXT NOT NULL,
    name TEXT NOT NULL,
    english_name TEXT NOT NULL
);

INSERT INTO
    languages (locale, name, english_name)
VALUES
    ('af', 'Afrikaans', 'Afrikaans'),
    ('az', 'Azərbaycan', 'Azerbaijani'),
    ('bs', 'Bosanski', 'Bosnian'),
    ('ca', 'Català', 'Catalan'),
    ('cy', 'Cymraeg', 'Welsh'),
    ('cs', 'Čeština', 'Czech'),
    ('da', 'Dansk', 'Danish'),
    ('de', 'Deutsch', 'German'),
    ('et', 'Eesti', 'Estonian'),
    ('en-CA', 'English (Canada)', 'English (Canada)'),
    ('en-GB', 'English (United Kingdom)', 'English (United Kingdom)'),
    ('en-US', 'English (United States)', 'English (United States)'),
    ('es', 'Español (España)', 'Spanish (Spain)'),
    ('es-419', 'Español (Latinoamérica)', 'Spanish (Latin America)'),
    ('eo', 'Esperanto', 'Esperanto'),
    ('eu', 'Euskara', 'Basque'),
    ('fil', 'Filipino', 'Filipino'),
    ('fr-CA', 'Français (Canada)', 'French (Canada)'),
    ('fr-FR', 'Français (France)', 'French (France)'),
    ('fo', 'Føroysk', 'Faroese'),
    ('gl', 'Galego', 'Galician'),
    ('hr', 'Hrvatski', 'Croatian'),
    ('id', 'Indonesia', 'Indonesian'),
    ('it', 'Italiano', 'Italian'),
    ('is', 'Íslenska', 'Icelandic'),
    ('sw', 'Kiswahili', 'Swahili'),
    ('lv', 'Latviešu', 'Latvian'),
    ('lt', 'Lietuvių', 'Lithuanian'),
    ('hu', 'Magyar', 'Hungarian'),
    ('mt', 'Malti', 'Maltese'),
    ('mi', 'Māori', 'Maori'),
    ('ms', 'Melayu', 'Malay'),
    ('nl', 'Nederlands', 'Dutch'),
    ('nb', 'Norsk (Bokmål)', 'Norwegian (Bokmål)'),
    ('nn', 'Norsk (Nynorsk)', 'Norwegian (Nynorsk)'),
    ('pl', 'Polski', 'Polish'),
    ('pt-BR', 'Português (Brasil)', 'Portuguese (Brazil)'),
    ('pt-PT', 'Português (Portugal)', 'Portuguese (Portugal)'),
    ('ro', 'Română', 'Romanian'),
    ('qu', 'Runasimi', 'Quechua'),
    ('tn', 'Setswana', 'Tswana'),
    ('sq', 'Shqip', 'Albanian'),
    ('sk', 'Slovenčina', 'Slovak'),
    ('sl', 'Slovenščina', 'Slovenian'),
    ('sr-Latn', 'Srpski (latinica)', 'Serbian (Latin)'),
    ('fi', 'Suomi', 'Finnish'),
    ('sv', 'Svenska', 'Swedish'),
    ('vi', 'Tiếng Việt', 'Vietnamese'),
    ('tr', 'Türkçe', 'Turkish'),
    ('ts', 'Xitsonga', 'Tsonga'),
    ('el', 'Ελληνικά', 'Greek'),
    ('be', 'Беларуская', 'Belarusian'),
    ('bg', 'Български', 'Bulgarian'),
    ('ky', 'Кыргызча', 'Kyrgyz'),
    ('mk', 'Македонски', 'Macedonian'),
    ('mn', 'Монгол', 'Mongolian'),
    ('ru', 'Русский', 'Russian'),
    ('sr', 'Српски (ћирилица)', 'Serbian (Cyrillic)'),
    ('uk', 'Українська', 'Ukrainian'),
    ('kk', 'Қазақ', 'Kazakh'),
    ('hy', 'հայերեն', 'Armenian'),
    ('he', 'עברית', 'Hebrew'),
    ('ur', 'اردو', 'Urdu'),
    ('ar', 'العربية', 'Arabic'),
    ('fa', 'فارسی', 'Persian'),
    ('dv', 'ދިވެހި', 'Divehi'),
    ('kok', 'कोंकणी', 'Konkani'),
    ('ne', 'नेपाली', 'Nepali'),
    ('mr', 'मराठी', 'Marathi'),
    ('sa', 'संस्कृत', 'Sanskrit'),
    ('hi', 'हिन्दी', 'Hindi'),
    ('as', 'অসমীয়া', 'Assamese'),
    ('bn', 'বাংলা', 'Bangla'),
    ('pa', 'ਪੰਜਾਬੀ', 'Punjabi'),
    ('gu', 'ગુજરાતી', 'Gujarati'),
    ('or', 'ଓଡ଼ିଆ', 'Odia'),
    ('ta', 'தமிழ்', 'Tamil'),
    ('te', 'తెలుగు', 'Telugu'),
    ('kn', 'ಕನ್ನಡ', 'Kannada'),
    ('ml', 'മലയാളം', 'Malayalam'),
    ('si', 'සිංහල', 'Sinhala'),
    ('th', 'ไทย', 'Thai'),
    ('lo', 'ລາວ', 'Lao'),
    ('ka', 'Ქართული', 'Georgian'),
    ('ko', '한국어', 'Korean'),
    ('am', 'አማርኛ', 'Amharic'),
    ('km', 'ខ្មែរ', 'Khmer'),
    ('zh-HK', '中文（香港）', 'Chinese (Hong Kong)'),
    ('ja', '日本語', 'Japanese'),
    ('zh-CN', '简体中文', 'Chinese (Simplified)'),
    ('zh-TW', '繁體中文', 'Chinese (Traditional)');


---
--- Alterations
---
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS language_id int8 REFERENCES languages (id) ON DELETE CASCADE;


-- safety-assured:start
UPDATE user_settings SET language_id = (SELECT id FROM languages WHERE locale = 'en-CA');
-- safety-assured:end

-- safety-assured:start
ALTER TABLE user_settings ALTER COLUMN language_id SET NOT NULL;
-- safety-assured:end

---
--- Functions
---
CREATE FUNCTION set_default_language_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.language_id IS NULL THEN
    NEW.language_id := (SELECT id FROM languages WHERE locale = 'en-CA');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER set_default_user_language_id_before_insert
BEFORE INSERT ON user_settings
FOR EACH ROW
EXECUTE FUNCTION set_default_language_id();
