[package]
name = "lib-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
derive_more = { workspace = true }
iso8601 = { version = "0.6.1", features = ["serde"] }
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.22.0"
serde = { workspace = true }
serde_json = { workspace = true }
url = { version = "2.5.4", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "1.4.1"

[lib]
doctest = false

[lints]
workspace = true
