---
--- Main tables
---
CREATE TABLE report_types (
    id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL
);

CREATE TABLE reports (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type_id int2 NOT NULL REFERENCES report_types (id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    exec_time_ms int8 NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE reports_logs (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id int8 NOT NULL REFERENCES reports (id) ON DELETE CASCADE,
    title text NOT NULL,
    is_success bool NOT NULL,
    is_warning bool NOT NULL,
    is_error bool NOT NULL,
    error_reason text NOT NULL DEFAULT ''
);

---
--- Inserts
---
INSERT INTO report_types (name)
    VALUES ('import');

