---
--- Main tables
---
CREATE TABLE report_types_primary (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE report_types_secondary (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE report_types_tertiary (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE reports (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type_primary_id int2 NOT NULL REFERENCES report_types_primary (id) ON DELETE CASCADE,
  report_type_secondary_id int2 REFERENCES report_types_secondary (id) ON DELETE CASCADE,
  report_type_tertiary_id int2 REFERENCES report_types_tertiary (id) ON DELETE CASCADE,
  items_total int4 NOT NULL DEFAULT 0,
  items_success int4 NOT NULL DEFAULT 0,
  items_skipped int4 NOT NULL DEFAULT 0,
  items_failed int4 NOT NULL DEFAULT 0,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  total_exec_time_ms int8 NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE levels (
  id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE reports_logs (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seq_num int4 NOT NULL,
  report_id int8 NOT NULL REFERENCES reports (id) ON DELETE CASCADE,
  entity_name text NOT NULL,
  level_id int2 NOT NULL REFERENCES levels (id) ON DELETE RESTRICT,
  error_code text,
  error_reason text,
  exec_time_ms int8 NOT NULL,
  UNIQUE (report_id, seq_num)
);

---
--- Inserts
---
INSERT INTO
  report_types_primary (name)
VALUES
  ('import'),
  ('website');

INSERT INTO
  report_types_secondary (name)
VALUES
  ('api'),
  ('raw'),
  ('software');

INSERT INTO
  report_types_tertiary (name)
VALUES
  ('mealie'),
  ('nextcloud'),
  ('tandoor'),
  ('json'),
  ('accuchef'),
  ('bigoven'),
  ('cheftap'),
  ('cooklang'),
  ('cookmate'),
  ('crouton'),
  ('kalorio'),
  ('mastercook'),
  ('mealmaster'),
  ('paprika'),
  ('recipemd'),
  ('recipesage'),
  ('rezkonv'),
  ('saffron');

INSERT INTO
  levels (name)
VALUES
  ('info'),
  ('success'),
  ('warning'),
  ('error');
