use std::{fmt::Write, fs, path::Path};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct WebsiteConfig {
    name: String,
    domain: String,
    variant: String,
    url: String,
    test: TestUrls,
    cuisine: Option<String>,
}

struct FileContent {
    metadata: Vec<(String, String, Option<String>)>,
    enum_variants: Vec<String>,
    from_domain_arms: String,
    domain_arms: String,
    test_urls_arms: String,
    count: i64,
}

impl FileContent {
    const fn new() -> Self {
        Self {
            metadata: Vec::new(),
            enum_variants: Vec::new(),
            from_domain_arms: String::new(),
            domain_arms: String::new(),
            test_urls_arms: String::new(),
            count: 0,
        }
    }

    fn generate(self) -> String {
        let count = self.count;
        let domain_arms = self.domain_arms;
        let test_urls_arms = self.test_urls_arms;
        let from_domain_arms = self.from_domain_arms;
        let enum_variants = self.enum_variants;
        let metadata = self.metadata;

        format!(
            r#"// This file is auto-generated by build.rs
    // Do not edit manually - changes will be overwritten.
    // Generated from data/websites.csv ({count} websites)

    // Holds the details of a website.
    pub struct WebsiteMetadata<'a> {{
        pub host: &'a str,
        pub url: &'a str,
        pub cuisine: Option<&'a str>,
    }}

    impl<'a> WebsiteMetadata<'a> {{
        const fn new(host: &'a str, url: &'a str, cuisine: Option<&'a str>) -> Self {{
            Self {{
                host,
                url,
                cuisine,
            }}
        }}
    }}

    /// Enumeration of all supported recipe websites.
    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum Website {{
    {}}}

    impl Website {{
        /// Returns the domain name of the website.
        pub const fn domain(&self) -> &'static str {{
            match self {{
    {domain_arms}        }}
        }}

        /// Creates a `Website` instance from a domain string.
        /// Strips "www." prefix automatically.
        pub fn from_domain(domain: &str) -> Option<Self> {{
            match domain.trim_start_matches("www.") {{
    {from_domain_arms}            _ => None,
            }}
        }}

        /// Returns test URLs for this website (used in unit tests).
        pub fn test_urls(&self) -> Vec<&'static str> {{
            match self {{
    {test_urls_arms}        }}
        }}

        /// Returns an iterator over all website variants.
        pub fn all<'a>() -> Vec<WebsiteMetadata<'a>> {{
            vec![
    {}
            ]
        }}
    }}
        "#,
            enum_variants.into_iter().fold(String::new(), |mut acc, v| {
                writeln!(acc, "\t{v},").unwrap();
                acc
            }),
            metadata.into_iter().enumerate().fold(
                String::new(),
                |mut acc, (i, (name, variant, cuisine))| {
                    if i > 0 {
                        acc.push_str(",\n");
                    }
                    write!(
                        acc,
                        "\t\t\tWebsiteMetadata::new(\"{name}\", \"https://{variant}\", {cuisine:?})"
                    )
                    .unwrap();
                    acc
                }
            )
        )
    }
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum TestUrls {
    Single(String),
    Multiple(Vec<String>),
}

impl TestUrls {
    fn to_vec(&self) -> Vec<String> {
        match self {
            Self::Single(s) => vec![s.clone()],
            Self::Multiple(v) => v.clone(),
        }
    }
}

#[derive(Debug, Deserialize)]
struct Config {
    #[serde(rename = "website")]
    websites: Vec<WebsiteConfig>,
}

fn main() {
    println!("cargo::rerun-if-changed=data/");

    let config = fetch_websites();

    let mut file_content = FileContent::new();

    for website in &config.websites {
        if !website
            .variant
            .chars()
            .all(|c| c.is_alphanumeric() || c == '_')
        {
            panic!(
                "Invalid variant name '{}' - must be valid Rust identifier",
                website.variant
            );
        }

        file_content.metadata.push((
            website.name.clone(),
            website.url.clone(),
            website.cuisine.clone(),
        ));
        file_content.enum_variants.push(website.variant.clone());
        writeln!(
            file_content.from_domain_arms,
            "            \"{}\" => Some(Self::{}),",
            website.domain, website.variant
        )
        .unwrap();
        writeln!(
            file_content.domain_arms,
            "            Self::{} => \"{}\",",
            website.variant, website.domain
        )
        .unwrap();
        writeln!(
            file_content.test_urls_arms,
            "            Self::{} => vec![{}],",
            website.variant,
            website
                .test
                .to_vec()
                .iter()
                .map(|url| format!("\"{url}\""))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();

        file_content.count += 1;
    }

    let out_dir = "src";
    let dest_path = Path::new(out_dir).join("generated_websites.rs");
    let num_websites = file_content.count;

    fs::write(&dest_path, file_content.generate()).expect("Failed to write generated_websites.rs");

    println!("Generated {num_websites} website variants");
}

fn fetch_websites() -> Config {
    let mut content = String::with_capacity(32 * 1024);
    for entry in fs::read_dir("data/").expect("Failed to read data/ directory") {
        let entry = entry.expect("Failed to read entry");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("toml") {
            content.push_str(
                &fs::read_to_string(&path)
                    .unwrap_or_else(|_| panic!("Failed to read {}", path.display())),
            );
        }
    }

    toml::from_str(&content).expect("Failed to parse data/websites.toml")
}
