use std::{fs, path::Path};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct WebsiteConfig {
    name: String,
    domain: String,
    variant: String,
    url: String,
    test: TestUrls,
    cuisine: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum TestUrls {
    Single(String),
    Multiple(Vec<String>),
}

impl TestUrls {
    fn to_vec(&self) -> Vec<String> {
        match self {
            TestUrls::Single(s) => vec![s.clone()],
            TestUrls::Multiple(v) => v.clone(),
        }
    }
}

#[derive(Debug, Deserialize)]
struct Config {
    #[serde(rename = "website")]
    websites: Vec<WebsiteConfig>,
}

fn main() {
    println!("cargo::rerun-if-changed=data/");

    let mut content = String::with_capacity(32 * 1024);
    for entry in fs::read_dir("data/").expect("Failed to read data/ directory") {
        let entry = entry.expect("Failed to read entry");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("toml") {
            content
                .push_str(&fs::read_to_string(&path).expect(&format!("Failed to read {path:?}")));
        }
    }

    let config: Config = toml::from_str(&content).expect("Failed to parse data/websites.toml");

    let mut metadata = Vec::new();
    let mut enum_variants = Vec::new();
    let mut from_domain_arms = String::new();
    let mut domain_arms = String::new();
    let mut test_urls_arms = String::new();

    let mut count = 0;

    for website in &config.websites {
        if !website
            .variant
            .chars()
            .all(|c| c.is_alphanumeric() || c == '_')
        {
            panic!(
                "Invalid variant name '{}' - must be valid Rust identifier",
                website.variant
            );
        }

        metadata.push((&website.name, &website.url, &website.cuisine));
        enum_variants.push(website.variant.clone());
        from_domain_arms.push_str(&format!(
            "            \"{}\" => Some(Self::{}),\n",
            website.domain, website.variant
        ));
        domain_arms.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            website.variant, website.domain
        ));
        test_urls_arms.push_str(&format!(
            "            Self::{} => vec![{}],\n",
            website.variant,
            website
                .test
                .to_vec()
                .iter()
                .map(|url| format!("\"{}\"", url))
                .collect::<Vec<_>>()
                .join(", ")
        ));

        count += 1;
    }

    let generated_code = format!(
        r#"// This file is auto-generated by build.rs
// Do not edit manually - changes will be overwritten.
// Generated from data/websites.csv ({count} websites)

// Holds the details of a website.
pub struct WebsiteMetadata<'a> {{
    pub host: &'a str,
    pub url: &'a str,
    pub cuisine: Option<&'a str>,
}}

impl<'a> WebsiteMetadata<'a> {{
    fn new(host: &'a str, url: &'a str, cuisine: Option<&'a str>) -> Self {{
        Self {{
            host,
            url,
            cuisine,
        }}
    }}
}}

/// Enumeration of all supported recipe websites.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {{
{}}}

impl Website {{
    /// Returns the domain name of the website.
    pub fn domain(&self) -> &'static str {{
        match self {{
{domain_arms}        }}
    }}

    /// Creates a `Website` instance from a domain string.
    /// Strips "www." prefix automatically.
    pub fn from_domain(domain: &str) -> Option<Self> {{
        match domain.trim_start_matches("www.") {{
{from_domain_arms}            _ => None,
        }}
    }}

    /// Returns test URLs for this website (used in unit tests).
    pub fn test_urls(&self) -> Vec<&'static str> {{
        match self {{
{test_urls_arms}        }}
    }}

    /// Returns an iterator over all website variants.
    pub fn all<'a>() -> Vec<WebsiteMetadata<'a>> {{
        vec![
{}
        ]
    }}
}}
    "#,
        enum_variants
            .clone()
            .into_iter()
            .map(|v| format!("\t{v},\n"))
            .collect::<Vec<_>>()
            .join(""),
        metadata
            .into_iter()
            .map(|(name, variant, cuisine)| format!(
                "\t\t\tWebsiteMetadata::new(\"{name}\", \"https://{variant}\", {cuisine:?})"
            ))
            .collect::<Vec<_>>()
            .join(",\n")
    );

    let out_dir = "src";
    let dest_path = Path::new(out_dir).join("generated_websites.rs");

    fs::write(&dest_path, generated_code).expect("Failed to write generated_websites.rs");

    println!("Generated {count} website variants");
}
