---
--- Main tables
---
CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    email text NOT NULL UNIQUE CHECK (lower(email) = email),
    password_hash varchar(255) NOT NULL,
    password_salt uuid NOT NULL DEFAULT gen_random_uuid (),
    token_salt uuid NOT NULL DEFAULT gen_random_uuid (),
    is_remember_me bool NOT NULL DEFAULT FALSE,
    is_email_verified bool NOT NULL DEFAULT FALSE,
    is_admin bool NOT NULL DEFAULT FALSE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_tokens (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selector char(12),
    hash_validator char(64),
    expires timestamptz DEFAULT (now() + interval '1 month'),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE counts (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    recipes int DEFAULT 0,
    cookbooks int DEFAULT 0
);

CREATE TABLE themes (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE email_verification_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE password_reset_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE refresh_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    last_used_at timestamptz NOT NULL DEFAULT NOW()
);

---
--- Indexes
---
CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_users_is_email_verified ON users (is_email_verified);

CREATE INDEX idx_users_created_at ON users (created_at);

CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens (token);

CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens (user_id);

CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens (expires_at);

CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens (token);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);

CREATE INDEX idx_refresh_tokens_token ON refresh_tokens (token);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

---
--- Functions
---
CREATE FUNCTION update_updated_at_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column ();

---
--- Inserts
---
INSERT INTO themes (name)
VALUES
    ('default'),
    ('system'),
    ('light'),
    ('dark'),
    ('abyss'),
    ('acid'),
    ('aqua'),
    ('autumn'),
    ('black'),
    ('bumblebee'),
    ('business'),
    ('caramellatte'),
    ('coffee'),
    ('corporate'),
    ('cmyk'),
    ('cupcake'),
    ('cyberpunk'),
    ('dim'),
    ('dracula'),
    ('emerald'),
    ('fantasy'),
    ('forest'),
    ('garden'),
    ('halloween'),
    ('lemonade'),
    ('lofi'),
    ('luxury'),
    ('night'),
    ('nord'),
    ('pastel'),
    ('retro'),
    ('silk'),
    ('sunset'),
    ('synthwave'),
    ('valentine'),
    ('wireframe'),
    ('winter');

