---
--- Extensions
---
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_cron;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'pg_cron not installed or cannot be created';
END
$$;

---
--- Main tables
---
CREATE TABLE app (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_update_available bool DEFAULT FALSE,
    updated_at timestamptz NOT NULL DEFAULT now(),
    update_last_checked_at timestamptz NOT NULL DEFAULT now()
);

---
--- Functions
---
CREATE FUNCTION update_last_checked_at_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.update_last_checked_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER update_app_last_checked_at
    BEFORE UPDATE OF is_update_available ON app
    FOR EACH ROW
    EXECUTE FUNCTION update_last_checked_at_column ();

---
--- Inserts
---
INSERT INTO app (id)
    VALUES (1);

