use reqwest::Url;
use std::{collections::HashMap, fmt::Formatter, sync::OnceLock};

use crate::{Error, Result};

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Website {
    O101cookbooksDotCom,
    O15gramsDotCom,
    O24kitchenDotNl,
    O750gDotCom,
    AbuelasCounterDotCom,
    ACoupleCooksDotCom,
    AddapinchDotCom,
    AfghanKitchenRecipesDotCom,
    AFlavorJournalDotCom,
    AhDotNl,
    AkispetretzikisDotCom,
    AlexandraCooksDotCom,
    ALittleBitYummyDotCom,
    AllCladDotCom,
    AldiDotComDotAu,
    AllTheHealthyThingsDotCom,
    AllRecipesDotCom,
    AltonBrownDotCom,
    AmazingRibsDotCom,
    AmbitiousKitchenDotCom,
    AmericasTestKitchenDotCom,
    AngielaEatsDotCom,
    AniagotujeDotPl,
    AntilliaansEtenDotNl,
    ArchanasKitchenDotCom,
    ArgiroDotGr,
    ArlaDotSe,
    AtelierDesChefsDotFr,
    AverieCooksDotCom,
    AvocadoSkilletDotCom,
    BakingMischiefDotCom,
    BakelsDotComDotAu,
    BakingSenseDotCom,
    BarefootContessaDotCom,
    BareFeetInTheKitchenDotCom,
    BbcDotCoDotUk,
    BbcGoodFoodDotCom,
    BettybossiDotCh,
    BettyCrockerDotCom,
    BeyondKimcheeDotCom,
    BiancazaPatkaDotCom,
    BigOvenDotCom,
    BlogDotGiallozafferanoDotIt,
    BlueApronDotCom,
    BlueJeanchefDotCom,
    BreadtopiaDotCom,
    BrianLagerstromDotCom,
    BriceletBaklavaDotCh,
    BritishBakelsDotCoDotUk,
    BodybuildingDotCom,
    BonAppetitDotCom,
    BongEatsDotCom,
    BottomlessGreensDotCom,
    BowlOfDeliciousDotCom,
    BudgetBytesDotCom,
    CafeDelitesDotCom,
    CanadaDotCa,
    CastironketoDotCom,
    CdKitchenDotCom,
    CestMaFourneeDotCom,
    ChatelaineDotCom,
    ChefkochDotDe,
    ChefniniDotCom,
    ChefSavvyDotCom,
    ChejorgeDotCom,
    ChetnamakanDotCoDotUk,
    ChineseCookingDemystifiedDotSubstackDotCom,
    ClaudiaAbrilComBr,
    ClosetCookingDotCom,
    ColruytDotBe,
    ComidinhasdoChefDotCom,
    CookEatShareDotCom,
    CookieAndKateDotCom,
    CookpadDotCom,
    CookTalkDotCom,
    CoopDotSe,
    CopykatDotCom,
    CostcoDotCom,
    CountryLivingDotCom,
    CreativeCanningDotCom,
    CucchiaioDotIt,
    CulyDotNl,
    CuisineAndTravelDotCom,
    CuisineazDotCom,
    CyberCookDotComDotBr,
    DamnDeliciousDotNet,
    DaringGourmetDotCom,
    DavidleBovitzDotCom,
    DelishDotCom,
    DherbsDotCom,
    DinnerAtTheZooDotCom,
    DinnerThenDessertDotCom,
    DishDotCoDotNz,
    DitchTheCarbsDotCom,
    DomesticateMeDotCom,
    DonnaHayDotComDotAu,
    DownshiftologyDotCom,
    DrDotdk,
    DreenaburtonDotCom,
    DrinkoteketDotSe,
    EatingBirdFoodDotCom,
    EatingWellDotCom,
    EatLiveRunDotCom,
    EatSmarterDotCom,
    EatWell101DotCom,
    EatWhatTonightDotCom,
    ElaveganDotCom,
    ElephantasticVeganDotCom,
    EmmikochteinfachDotDe,
    EntertainingWithBethDotCom,
    EpicuriousDotCom,
    ErrensKitchenDotCom,
    EtenvaneefkeDotNl,
    ExpressenDotSe,
    EvolvingTableDotCom,
    FamilyFoodOnTheTableDotCom,
    FarmhouseDeliveryDotCom,
    FarmhouseOnBooneDotCom,
    FattoincasadabenedettaDotIt,
    FeastingAtHomeDotCom,
    FelixDotKitchen,
    FifteenSpatulasDotCom,
    FineDiningLoversDotCom,
    FindingTimeForCookingDotCom,
    FitmenCookDotCom,
    FitsLowCookerQueenDotCom,
    FoodDotCom,
    Food52DotCom,
    FoodalDotCom,
    FoodAndWineDotCom,
    FoodByMariaDotCom,
    FoodieCrushDotCom,
    FoodNetworkDotCoDotUk,
    FoodRepublicDotCom,
    FoolProofLivingDotCom,
    ForksOverKnivesDotCom,
    ForkToSpoonDotCom,
    FrancescakooktDotNl,
    FranzoesischKochenDotDe,
    FredriksfikaDotAllasDotSe,
    GastroPlantDotCom,
    GazoakleyChefDotCom,
    GesundAktivDotCom,
    GiallozafferanoDotCom,
    GimmeSomeOvenDotCom,
    GloboDotCom,
    GlutenFreeTablesDotCom,
    GodtDotNo,
    GonnaWantSecondsDotCom,
    GoodEatingsDotCom,
    GoodFoodDiscoveriesDotCom,
    GoodHouseKeepingDotCom,
    GoodtoDotCom,
    GourmetTravellerDotComDotAu,
    GurkiDotNo,
    GrandFraisDotCom,
    GreatBritishChefsDotCom,
    GreeneviDotCom,
    GrimGrainsDotCom,
    GroupRecipesDotCom,
    HalfBakedHarvestDotCom,
    HandleTheHeatDotCom,
    HassanChefDotCom,
    HeadbangersKitchenDotCom,
    HealthyLittleFoodiesDotCom,
    HeatherChristoDotCom,
    HelloFreshDotCom,
    HomebrewAnswersDotCom,
    HomeChefDotCom,
    HostTheToastDotCom,
    IcaDotSe,
    ImWorthyDotCom,
    InBloomBakeryDotCom,
    IndianHealthyRecipesDotCom,
    InnitDotCom,
    InsanelyGoodRecipesDotCom,
    InspiralizedDotCom,
    InstantPotDotCom,
    JamieOliverDotCom,
    JaimysKitchenDotNl,
    JarofLemonsDotCom,
    JimCooksFoodGoodDotCom,
    JoCooksDotCom,
    JoyFoodSunshineDotCom,
    JoyTheBakerDotCom,
    JulieGoodwinDotComDotAu,
    JumboDotCom,
    JustATasteDotCom,
    JustBentoDotCom,
    JustOneCookBookDotCom,
    KeepinItKindDotCom,
    KennyMcGovernDotCom,
    KingArthurBakingDotCom,
    KitchenAidDotComDotAu,
    KitchenSanctuaryDotCom,
    KitchenStoriesDotCom,
    KochbarDotDe,
    KochbucherDotCom,
    KoketDotSe,
    KookjijDotNl,
    KptnCookDotCom,
    KristinesKitchenBlogDotCom,
    KuchniaDomowaDotPl,
    KuchynalidlaDotSk,
    KwestiasmakuDotCom,
    LahbcoDotCom,
    LatelierDeRoxaneDotCom,
    LeanandGreenRecipesDotNet,
    LeckerDotDe,
    LecremedelacrumbDotCom,
    LekkerenSimpelDotCom,
    LeukeReceptenDotNl,
    LifestyleOfAFoodieDotCom,
    LidlDotNl,
    LidlKochenDotDe,
    LithuanianInTheUsaDotCom,
    LittleSpiceJarDotCom,
    LivelyTableDotCom,
    LivingTheGreenLifeDotCom,
    LoveAndLemonsDotCom,
    LovingItVeganDotCom,
    MaangchiDotCom,
    MadensVerdenDotdk,
    MadsvinDotCom,
    MarmitonDotOrg,
    MarthaStewartDotCom,
    MatpratDotNo,
    McCormickDotCom,
    MeljoulwanDotCom,
    MelsKitchenCafeDotCom,
    MexicanMadeMeatlessDotCom,
    MindmegetteDotHu,
    MinimalistBakerDotCom,
    MinistryOfCurryDotCom,
    MisyaDotInfo,
    ModernHoneyDotCom,
    MomonTimeoutDotCom,
    MomsDishDotCom,
    MomsWithCrockpotsDotCom,
    MotherThymeDotCom,
    MoulinexDotFr,
    MundoDeReceitasBimbyDotComDotPt,
    MyBakingAddictionDotCom,
    MyJewishLearningDotCom,
    MyKitchen101DotCom,
    MyKoreanKitchenDotCom,
    MyGingerGarlicKitchenDotCom,
    MyKitchen101enDotCom,
    MyPlateDotGov,
    MyRecipesDotCom,
    NatashasKitchenDotCom,
    NigellaDotCom,
    NinjaTestKitchenDotEu,
    NourishedByNutritionDotCom,
    NosaltyDotHu,
    NotEnoughCinnamonDotCom,
    NrkDotNo,
    Number2PencilDotCom,
    NutritionFactsDotOrg,
    NyTimesDotCom,
    OhSheGlowsDotCom,
    OkokoReceptenDotNl,
    OmnivoresCookbookDotCom,
    OnceUponaChefDotCom,
    OhMyVeggiesDotCom,
    OneSweetAppetiteDotCom,
    OwenHanDotCom,
    PaleoRunningMommaDotCom,
    PanelinhaDotComDotBr,
    PaniniHappyDotCom,
    ParsleyAndParmDotCom,
    PersnicketyPlatesDotCom,
    PickupLimesDotCom,
    PinchOfYumDotCom,
    PinkOwlKitchenDotCom,
    PingoDoceDotPt,
    PlatingPixelsDotCom,
    PlentyVeganDotCom,
    PloetzblogDotDe,
    PlowingThroughLifeDotCom,
    PopSugarDotCoDotUk,
    PotatoRollsDotGom,
    PracticalSelfRelianceDotCom,
    PressureLuckCookingDotCom,
    PrimalEdgeHealthDotCom,
    ProjectGezondDotNl,
    PrzepisyDotPl,
    PurelyPopeDotCom,
    PureWowDotCom,
    PurpleCarrotDotCom,
    PuurgezondDotNl,
    QuitoqueDotFr,
    RachlmansFieldDotCom,
    RadioFranceDotFr,
    RainbowPlantLifeDotCom,
    RealSimpleDotCom,
    ReceitasNestleDotComDotBr,
    RecettesDotQcDotCa,
    RecipeGirlDotCom,
    RecipeRunnerDotCom,
    RecipeTinEatsDotCom,
    RedditDotCom,
    RedhouseSpiceDotCom,
    ReisHungerDotDe,
    RezeptWeltDotDe,
    RicettaDotIt,
    RicettePerBimbyDotIt,
    RobinasBellDotCom,
    RosannaPansinoDotCom,
    RutgerbaktDotNl,
    RecipeCommunityDotComDotAu,
    SaboresaJinomotoDotComDotBr,
    SallysBakingAddictionDotCom,
    SallysBlogDotDe,
    SaltAndLavenderDotCom,
    SaltPepperSkilletDotCom,
    SarahsVeganGuideDotCom,
    SaveurDotCom,
    SavoryNothingsDotCom,
    SeriousEatsDotCom,
    SimpleVeganistaDotCom,
    SimplyCookitDotCom,
    SimplyQuinoaDotCom,
    SimplyRecipesDotCom,
    SimplyWhiskedDotCom,
    SkinnyTasteDotCom,
    SmittenKitchenDotCom,
    SoborsDotHu,
    SouthernCastIronDotCom,
    SouthernLivingDotCom,
    SpendWithPenniesDotCom,
    SpiceboxTravelsDotCom,
    StaySnatchedDotCom,
    SteamyKitchenDotCom,
    StreetKitchenDotCo,
    StrongrFastrDotCom,
    SunBasketDotCom,
    SundPaabudgetDotdk,
    SunsetDotCom,
    SweetcsDesignsDotCom,
    SweetPeasAnSsaffronDotCom,
    TasteAtlasDotCom,
    TasteOfHomeDotCom,
    TastesBetterFromScratchDotCom,
    TastesOfLizzytDotCom,
    TastyDotCo,
    TastyKitchenDotCom,
    TescoDotCom,
    ThatVeganDadDotNet,
    TheCleverCarrotDotCom,
    TheCookieRookieDotCom,
    TheCookingGuyDotCom,
    TheExpertGuidesDotCom,
    TheFoodFlamingoDotCom,
    TheGucchaDotCom,
    TheHappyFoodieDotCoDotUk,
    TheHeartySoulDotCom,
    TheKitchenCommunityDotOrg,
    TheKitchenMagPieDotCom,
    TheKitchnDotCom,
    TheMagicalSlowCookerDotCom,
    TheNutritiousKitchenDotCo,
    TheModernProperDotCom,
    ThePalatableLifeDotCom,
    ThePioneerWomanDotCom,
    TheRecipeCriticDotCom,
    TheSaltyMarshmallowDotCom,
    TheSpruceEatsDotCom,
    TheVintageMixerDotCom,
    TheWoksOfLifeDotCom,
    ThinliciousDotCom,
    TidyMomDotNet,
    TimesOfIndiaDotCom,
    TineDotNo,
    TudogostosoDotComDotBr,
    TwoPeasAndTheirPodDotCom,
    TwoSleeversDotCom,
    UitPaulinesKeukenDotNl,
    UnsophistiCookDotCom,
    UsaPearsDotOrg,
    ValdemarsroDotdk,
    VanillaAndBeanDotCom,
    VeganPratiqueDotFr,
    VegetarBloggenDotNo,
    VegolosiDotIt,
    VegRecipesOfIndiaDotCom,
    WaitRoseDotCom,
    WatchWhatUEatDotCom,
    WearenotMarthaDotCom,
    WeightWatchersDotCom,
    WellPlatedDotCom,
    WhatsGabyCookingDotCom,
    WholeFoodsMarketDotCoDotUk,
    WikibooksDotOrg,
    WikibooksDotOrgMobile,
    WomensWeeklyFoodDotComDotAu,
    WoopDotCoDotNz,
    YeMekDotNet,
    YumeliseDotFr,
    ZeitDotDe,
    ZenbellyDotCom,
}

impl Website {
    pub fn from(url: &str) -> Result<Self> {
        let url = match Url::parse(url).map_err(|err| Error::Parse(err.to_string())) {
            Ok(url) => url,
            Err(_) => return Err(Error::UnknownWebsite),
        };

        let domain = match url.domain() {
            None => return Err(Error::UnknownWebsite),
            Some(domain) => domain,
        };

        match websites_map_to_website().get(domain) {
            Some(&website) => Ok(website),
            None => Err(Error::UnknownWebsite),
        }
    }
}

impl std::fmt::Display for Website {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match websites_map_to_domain().get_key_value(self) {
            Some((_, url)) => write!(f, "{url}"),
            None => write!(f, "URL not found"),
        }
    }
}

fn websites_map_to_domain() -> &'static HashMap<Website, String> {
    static INSTANCE: OnceLock<HashMap<Website, String>> = OnceLock::new();

    INSTANCE.get_or_init(|| {
        HashMap::from([
            (
                Website::O101cookbooksDotCom,
                "www.101cookbooks.com".to_string(),
            ),
            (Website::O15gramsDotCom, "15gram.be".to_string()),
            (Website::O24kitchenDotNl, "www.24kitchen.nl".to_string()),
            (Website::O750gDotCom, "www.750g.com".to_string()),
            (
                Website::AbuelasCounterDotCom,
                "abuelascounter.com".to_string(),
            ),
            (
                Website::ACoupleCooksDotCom,
                "www.acouplecooks.com".to_string(),
            ),
            (Website::AddapinchDotCom, "addapinch.com".to_string()),
            (
                Website::AfghanKitchenRecipesDotCom,
                "www.afghankitchenrecipes.com".to_string(),
            ),
            (
                Website::AFlavorJournalDotCom,
                "aflavorjournal.com".to_string(),
            ),
            (Website::AhDotNl, "www.ah.nl".to_string()),
            (
                Website::AkispetretzikisDotCom,
                "akispetretzikis.com".to_string(),
            ),
            (
                Website::AlexandraCooksDotCom,
                "alexandracooks.com".to_string(),
            ),
            (
                Website::ALittleBitYummyDotCom,
                "alittlebityummy.com".to_string(),
            ),
            (Website::AllCladDotCom, "www.all-clad.com".to_string()),
            (Website::AldiDotComDotAu, "www.aldi.com.au".to_string()),
            (
                Website::AllTheHealthyThingsDotCom,
                "allthehealthythings.com".to_string(),
            ),
            (Website::AllRecipesDotCom, "www.allrecipes.com".to_string()),
            (Website::AltonBrownDotCom, "altonbrown.com".to_string()),
            (Website::AmazingRibsDotCom, "amazingribs.com".to_string()),
            (
                Website::AmbitiousKitchenDotCom,
                "www.ambitiouskitchen.com".to_string(),
            ),
            (
                Website::AmericasTestKitchenDotCom,
                "www.americastestkitchen.com".to_string(),
            ),
            (
                Website::AngielaEatsDotCom,
                "www.angielaeats.com".to_string(),
            ),
            (Website::AniagotujeDotPl, "aniagotuje.pl".to_string()),
            (
                Website::AntilliaansEtenDotNl,
                "www.antilliaans-eten.nl".to_string(),
            ),
            (
                Website::ArchanasKitchenDotCom,
                "www.archanaskitchen.com".to_string(),
            ),
            (Website::ArgiroDotGr, "www.argiro.gr".to_string()),
            (Website::ArlaDotSe, "www.arla.se".to_string()),
            (
                Website::AtelierDesChefsDotFr,
                "www.atelierdeschefs.fr".to_string(),
            ),
            (
                Website::AverieCooksDotCom,
                "www.averiecooks.com".to_string(),
            ),
            (
                Website::AvocadoSkilletDotCom,
                "avocadoskillet.com".to_string(),
            ),
            (
                Website::BakingMischiefDotCom,
                "bakingmischief.com".to_string(),
            ),
            (Website::BakelsDotComDotAu, "www.bakels.com.au".to_string()),
            (
                Website::BakingSenseDotCom,
                "www.baking-sense.com".to_string(),
            ),
            (
                Website::BarefootContessaDotCom,
                "barefootcontessa.com".to_string(),
            ),
            (
                Website::BareFeetInTheKitchenDotCom,
                "barefeetinthekitchen.com".to_string(),
            ),
            (Website::BbcDotCoDotUk, "www.bbc.co.uk".to_string()),
            (
                Website::BbcGoodFoodDotCom,
                "www.bbcgoodfood.com".to_string(),
            ),
            (Website::BettybossiDotCh, "www.bettybossi.ch".to_string()),
            (
                Website::BettyCrockerDotCom,
                "www.bettycrocker.com".to_string(),
            ),
            (
                Website::BeyondKimcheeDotCom,
                "www.beyondkimchee.com".to_string(),
            ),
            (
                Website::BiancazaPatkaDotCom,
                "biancazapatka.com".to_string(),
            ),
            (Website::BigOvenDotCom, "www.bigoven.com".to_string()),
            (
                Website::BlogDotGiallozafferanoDotIt,
                "blog.giallozafferano.it".to_string(),
            ),
            (Website::BlueApronDotCom, "www.blueapron.com".to_string()),
            (Website::BlueJeanchefDotCom, "bluejeanchef.com".to_string()),
            (Website::BreadtopiaDotCom, "breadtopia.com".to_string()),
            (
                Website::BrianLagerstromDotCom,
                "www.brianlagerstrom.com".to_string(),
            ),
            (
                Website::BriceletBaklavaDotCh,
                "briceletbaklava.ch".to_string(),
            ),
            (
                Website::BritishBakelsDotCoDotUk,
                "www.britishbakels.co.uk".to_string(),
            ),
            (
                Website::BodybuildingDotCom,
                "www.bodybuilding.com".to_string(),
            ),
            (Website::BonAppetitDotCom, "www.bonappetit.com".to_string()),
            (Website::BongEatsDotCom, "www.bongeats.com".to_string()),
            (
                Website::BottomlessGreensDotCom,
                "bottomlessgreens.com".to_string(),
            ),
            (
                Website::BowlOfDeliciousDotCom,
                "www.bowlofdelicious.com".to_string(),
            ),
            (
                Website::BudgetBytesDotCom,
                "www.budgetbytes.com".to_string(),
            ),
            (Website::CafeDelitesDotCom, "cafedelites.com".to_string()),
            (Website::CanadaDotCa, "food-guide.canada.ca".to_string()),
            (
                Website::CastironketoDotCom,
                "www.castironketo.net".to_string(),
            ),
            (Website::CdKitchenDotCom, "www.cdkitchen.com".to_string()),
            (
                Website::CestMaFourneeDotCom,
                "www.cestmafournee.com".to_string(),
            ),
            (Website::ChatelaineDotCom, "chatelaine.com".to_string()),
            (Website::ChefkochDotDe, "www.chefkoch.de".to_string()),
            (Website::ChefniniDotCom, "www.chefnini.com".to_string()),
            (Website::ChefSavvyDotCom, "chefsavvy.com".to_string()),
            (Website::ChejorgeDotCom, "chejorge.com".to_string()),
            (
                Website::ChetnamakanDotCoDotUk,
                "chetnamakan.co.uk".to_string(),
            ),
            (
                Website::ChineseCookingDemystifiedDotSubstackDotCom,
                "chinesecookingdemystified.substack.com".to_string(),
            ),
            (
                Website::ClaudiaAbrilComBr,
                "claudia.abril.com.br".to_string(),
            ),
            (
                Website::ClosetCookingDotCom,
                "www.closetcooking.com".to_string(),
            ),
            (Website::ColruytDotBe, "www.colruyt.be".to_string()),
            (
                Website::ComidinhasdoChefDotCom,
                "comidinhasdochef.com".to_string(),
            ),
            (Website::CookEatShareDotCom, "cookeatshare.com".to_string()),
            (
                Website::CookieAndKateDotCom,
                "cookieandkate.com".to_string(),
            ),
            (Website::CookpadDotCom, "cookpad.com".to_string()),
            (Website::CookTalkDotCom, "cook-talk.com".to_string()),
            (Website::CoopDotSe, "www.coop.se".to_string()),
            (Website::CopykatDotCom, "copykat.com".to_string()),
            (Website::CostcoDotCom, "www.costco.com".to_string()),
            (
                Website::CountryLivingDotCom,
                "www.countryliving.com".to_string(),
            ),
            (
                Website::CreativeCanningDotCom,
                "creativecanning.com".to_string(),
            ),
            (Website::CucchiaioDotIt, "www.cucchiaio.it".to_string()),
            (Website::CulyDotNl, "www.culy.nl".to_string()),
            (
                Website::CuisineAndTravelDotCom,
                "www.cuisineandtravel.com".to_string(),
            ),
            (Website::CuisineazDotCom, "www.cuisineaz.com".to_string()),
            (
                Website::CyberCookDotComDotBr,
                "cybercook.com.br".to_string(),
            ),
            (
                Website::DamnDeliciousDotNet,
                "damndelicious.net".to_string(),
            ),
            (
                Website::DaringGourmetDotCom,
                "www.daringgourmet.com".to_string(),
            ),
            (
                Website::DavidleBovitzDotCom,
                "www.davidlebovitz.com".to_string(),
            ),
            (Website::DelishDotCom, "www.delish.com".to_string()),
            (Website::DherbsDotCom, "www.dherbs.com".to_string()),
            (
                Website::DinnerAtTheZooDotCom,
                "www.dinneratthezoo.com".to_string(),
            ),
            (
                Website::DinnerThenDessertDotCom,
                "dinnerthendessert.com".to_string(),
            ),
            (Website::DishDotCoDotNz, "dish.co.nz".to_string()),
            (
                Website::DitchTheCarbsDotCom,
                "www.ditchthecarbs.com".to_string(),
            ),
            (
                Website::DomesticateMeDotCom,
                "domesticate-me.com".to_string(),
            ),
            (
                Website::DonnaHayDotComDotAu,
                "www.donnahay.com.au".to_string(),
            ),
            (
                Website::DownshiftologyDotCom,
                "downshiftology.com".to_string(),
            ),
            (Website::DrDotdk, "www.dr.dk".to_string()),
            (Website::DreenaburtonDotCom, "dreenaburton.com".to_string()),
            (Website::DrinkoteketDotSe, "drinkoteket.se".to_string()),
            (
                Website::EatingBirdFoodDotCom,
                "www.eatingbirdfood.com".to_string(),
            ),
            (Website::EatingWellDotCom, "www.eatingwell.com".to_string()),
            (Website::EatLiveRunDotCom, "www.eatliverun.com".to_string()),
            (Website::EatSmarterDotCom, "eatsmarter.com".to_string()),
            (Website::EatWell101DotCom, "www.eatwell101.com".to_string()),
            (
                Website::EatWhatTonightDotCom,
                "eatwhattonight.com".to_string(),
            ),
            (Website::ElaveganDotCom, "elavegan.com".to_string()),
            (
                Website::ElephantasticVeganDotCom,
                "www.elephantasticvegan.com".to_string(),
            ),
            (
                Website::EmmikochteinfachDotDe,
                "emmikochteinfach.de".to_string(),
            ),
            (
                Website::EntertainingWithBethDotCom,
                "entertainingwithbeth.com".to_string(),
            ),
            (Website::EpicuriousDotCom, "www.epicurious.com".to_string()),
            (
                Website::ErrensKitchenDotCom,
                "www.errenskitchen.com".to_string(),
            ),
            (
                Website::EtenvaneefkeDotNl,
                "www.etenvaneefke.nl".to_string(),
            ),
            (
                Website::ExpressenDotSe,
                "alltommat.expressen.se".to_string(),
            ),
            (
                Website::EvolvingTableDotCom,
                "www.evolvingtable.com".to_string(),
            ),
            (
                Website::FamilyFoodOnTheTableDotCom,
                "www.familyfoodonthetable.com".to_string(),
            ),
            (
                Website::FarmhouseDeliveryDotCom,
                "recipes.farmhousedelivery.com".to_string(),
            ),
            (
                Website::FarmhouseOnBooneDotCom,
                "www.farmhouseonboone.com".to_string(),
            ),
            (
                Website::FattoincasadabenedettaDotIt,
                "www.fattoincasadabenedetta.it".to_string(),
            ),
            (
                Website::FeastingAtHomeDotCom,
                "www.feastingathome.com".to_string(),
            ),
            (Website::FelixDotKitchen, "felix.kitchen".to_string()),
            (
                Website::FifteenSpatulasDotCom,
                "www.fifteenspatulas.com".to_string(),
            ),
            (
                Website::FineDiningLoversDotCom,
                "www.finedininglovers.com".to_string(),
            ),
            (
                Website::FindingTimeForCookingDotCom,
                "findingtimeforcooking.com".to_string(),
            ),
            (Website::FitmenCookDotCom, "fitmencook.com".to_string()),
            (
                Website::FitsLowCookerQueenDotCom,
                "fitslowcookerqueen.com".to_string(),
            ),
            (Website::FoodDotCom, "www.food.com".to_string()),
            (Website::Food52DotCom, "food52.com".to_string()),
            (Website::FoodalDotCom, "foodal.com".to_string()),
            (
                Website::FoodAndWineDotCom,
                "www.foodandwine.com".to_string(),
            ),
            (
                Website::FoodByMariaDotCom,
                "www.foodbymaria.com".to_string(),
            ),
            (
                Website::FoodieCrushDotCom,
                "www.foodiecrush.com".to_string(),
            ),
            (
                Website::FoodNetworkDotCoDotUk,
                "foodnetwork.co.uk".to_string(),
            ),
            (
                Website::FoodRepublicDotCom,
                "www.foodrepublic.com".to_string(),
            ),
            (
                Website::FoolProofLivingDotCom,
                "foolproofliving.com".to_string(),
            ),
            (
                Website::ForksOverKnivesDotCom,
                "www.forksoverknives.com".to_string(),
            ),
            (Website::ForkToSpoonDotCom, "forktospoon.com".to_string()),
            (
                Website::FrancescakooktDotNl,
                "www.francescakookt.nl".to_string(),
            ),
            (
                Website::FranzoesischKochenDotDe,
                "www.franzoesischkochen.de".to_string(),
            ),
            (
                Website::FredriksfikaDotAllasDotSe,
                "fredriksfika.allas.se".to_string(),
            ),
            (Website::GastroPlantDotCom, "gastroplant.com".to_string()),
            (
                Website::GazoakleyChefDotCom,
                "www.gazoakleychef.com".to_string(),
            ),
            (
                Website::GesundAktivDotCom,
                "www.gesund-aktiv.com".to_string(),
            ),
            (
                Website::GiallozafferanoDotCom,
                "www.giallozafferano.com".to_string(),
            ),
            (
                Website::GimmeSomeOvenDotCom,
                "www.gimmesomeoven.com".to_string(),
            ),
            (Website::GloboDotCom, "receitas.globo.com".to_string()),
            (
                Website::GlutenFreeTablesDotCom,
                "glutenfreetables.com".to_string(),
            ),
            (Website::GodtDotNo, "www.godt.no".to_string()),
            (
                Website::GonnaWantSecondsDotCom,
                "www.gonnawantseconds.com".to_string(),
            ),
            (Website::GoodEatingsDotCom, "goodeatings.com".to_string()),
            (
                Website::GoodFoodDiscoveriesDotCom,
                "goodfooddiscoveries.com".to_string(),
            ),
            (
                Website::GoodHouseKeepingDotCom,
                "www.goodhousekeeping.com".to_string(),
            ),
            (Website::GoodtoDotCom, "www.goodto.com".to_string()),
            (
                Website::GourmetTravellerDotComDotAu,
                "www.gourmettraveller.com.au".to_string(),
            ),
            (Website::GurkiDotNo, "gurki.no".to_string()),
            (Website::GrandFraisDotCom, "www.grandfrais.com".to_string()),
            (
                Website::GreatBritishChefsDotCom,
                "www.greatbritishchefs.com".to_string(),
            ),
            (Website::GreeneviDotCom, "greenevi.com".to_string()),
            (Website::GrimGrainsDotCom, "grimgrains.com".to_string()),
            (
                Website::GroupRecipesDotCom,
                "www.grouprecipes.com".to_string(),
            ),
            (
                Website::HalfBakedHarvestDotCom,
                "www.halfbakedharvest.com".to_string(),
            ),
            (
                Website::HandleTheHeatDotCom,
                "handletheheat.com".to_string(),
            ),
            (Website::HassanChefDotCom, "www.hassanchef.com".to_string()),
            (
                Website::HeadbangersKitchenDotCom,
                "headbangerskitchen.com".to_string(),
            ),
            (
                Website::HealthyLittleFoodiesDotCom,
                "www.healthylittlefoodies.com".to_string(),
            ),
            (
                Website::HeatherChristoDotCom,
                "heatherchristo.com".to_string(),
            ),
            (Website::HelloFreshDotCom, "www.hellofresh.com".to_string()),
            (
                Website::HomebrewAnswersDotCom,
                "homebrewanswers.com".to_string(),
            ),
            (Website::HomeChefDotCom, "www.homechef.com".to_string()),
            (Website::HostTheToastDotCom, "hostthetoast.com".to_string()),
            (Website::IcaDotSe, "www.ica.se".to_string()),
            (Website::ImWorthyDotCom, "im-worthy.com".to_string()),
            (
                Website::InBloomBakeryDotCom,
                "inbloombakery.com".to_string(),
            ),
            (
                Website::IndianHealthyRecipesDotCom,
                "www.indianhealthyrecipes.com".to_string(),
            ),
            (Website::InnitDotCom, "www.innit.com".to_string()),
            (
                Website::InsanelyGoodRecipesDotCom,
                "insanelygoodrecipes.com".to_string(),
            ),
            (Website::InspiralizedDotCom, "inspiralized.com".to_string()),
            (Website::InstantPotDotCom, "instantpot.com".to_string()),
            (
                Website::JamieOliverDotCom,
                "www.jamieoliver.com".to_string(),
            ),
            (Website::JaimysKitchenDotNl, "jaimyskitchen.nl".to_string()),
            (
                Website::JarofLemonsDotCom,
                "www.jaroflemons.com".to_string(),
            ),
            (
                Website::JimCooksFoodGoodDotCom,
                "jimcooksfoodgood.com".to_string(),
            ),
            (Website::JoCooksDotCom, "www.jocooks.com".to_string()),
            (
                Website::JoyFoodSunshineDotCom,
                "joyfoodsunshine.com".to_string(),
            ),
            (Website::JoyTheBakerDotCom, "joythebaker.com".to_string()),
            (
                Website::JulieGoodwinDotComDotAu,
                "juliegoodwin.com.au".to_string(),
            ),
            (Website::JumboDotCom, "www.jumbo.com".to_string()),
            (Website::JustATasteDotCom, "www.justataste.com".to_string()),
            (Website::JustBentoDotCom, "justbento.com".to_string()),
            (
                Website::JustOneCookBookDotCom,
                "www.justonecookbook.com".to_string(),
            ),
            (Website::KeepinItKindDotCom, "keepinitkind.com".to_string()),
            (
                Website::KennyMcGovernDotCom,
                "kennymcgovern.com".to_string(),
            ),
            (
                Website::KingArthurBakingDotCom,
                "www.kingarthurbaking.com".to_string(),
            ),
            (
                Website::KitchenAidDotComDotAu,
                "kitchenaid.com.au".to_string(),
            ),
            (
                Website::KitchenSanctuaryDotCom,
                "www.kitchensanctuary.com".to_string(),
            ),
            (
                Website::KitchenStoriesDotCom,
                "www.kitchenstories.com".to_string(),
            ),
            (Website::KochbarDotDe, "www.kochbar.de".to_string()),
            (Website::KochbucherDotCom, "kochbucher.com".to_string()),
            (Website::KoketDotSe, "www.koket.se".to_string()),
            (Website::KookjijDotNl, "www.kookjij.nl".to_string()),
            (Website::KptnCookDotCom, "mobile.kptncook.com".to_string()),
            (
                Website::KristinesKitchenBlogDotCom,
                "kristineskitchenblog.com".to_string(),
            ),
            (
                Website::KuchniaDomowaDotPl,
                "www.kuchnia-domowa.pl".to_string(),
            ),
            (Website::KuchynalidlaDotSk, "kuchynalidla.sk".to_string()),
            (
                Website::KwestiasmakuDotCom,
                "www.kwestiasmaku.com".to_string(),
            ),
            (Website::LahbcoDotCom, "www.lahbco.com".to_string()),
            (
                Website::LatelierDeRoxaneDotCom,
                "www.latelierderoxane.com".to_string(),
            ),
            (
                Website::LeanandGreenRecipesDotNet,
                "leanandgreenrecipes.net".to_string(),
            ),
            (Website::LeckerDotDe, "www.lecker.de".to_string()),
            (
                Website::LecremedelacrumbDotCom,
                "www.lecremedelacrumb.com".to_string(),
            ),
            (
                Website::LekkerenSimpelDotCom,
                "www.lekkerensimpel.com".to_string(),
            ),
            (
                Website::LeukeReceptenDotNl,
                "www.leukerecepten.nl".to_string(),
            ),
            (
                Website::LifestyleOfAFoodieDotCom,
                "lifestyleofafoodie.com".to_string(),
            ),
            (Website::LidlDotNl, "recepten.lidl.nl".to_string()),
            (Website::LidlKochenDotDe, "www.lidl-kochen.de".to_string()),
            (
                Website::LithuanianInTheUsaDotCom,
                "lithuanianintheusa.com".to_string(),
            ),
            (
                Website::LittleSpiceJarDotCom,
                "littlespicejar.com".to_string(),
            ),
            (Website::LivelyTableDotCom, "livelytable.com".to_string()),
            (
                Website::LivingTheGreenLifeDotCom,
                "livingthegreenlife.com".to_string(),
            ),
            (
                Website::LoveAndLemonsDotCom,
                "www.loveandlemons.com".to_string(),
            ),
            (
                Website::LovingItVeganDotCom,
                "lovingitvegan.com".to_string(),
            ),
            (Website::MaangchiDotCom, "www.maangchi.com".to_string()),
            (Website::MadensVerdenDotdk, "madensverden.dk".to_string()),
            (Website::MadsvinDotCom, "madsvin.com".to_string()),
            (Website::MarmitonDotOrg, "www.marmiton.org".to_string()),
            (
                Website::MarthaStewartDotCom,
                "www.marthastewart.com".to_string(),
            ),
            (Website::MatpratDotNo, "www.matprat.no".to_string()),
            (Website::McCormickDotCom, "www.mccormick.com".to_string()),
            (Website::MeljoulwanDotCom, "meljoulwan.com".to_string()),
            (
                Website::MelsKitchenCafeDotCom,
                "www.melskitchencafe.com".to_string(),
            ),
            (
                Website::MexicanMadeMeatlessDotCom,
                "mexicanmademeatless.com".to_string(),
            ),
            (Website::MindmegetteDotHu, "www.mindmegette.hu".to_string()),
            (
                Website::MinimalistBakerDotCom,
                "minimalistbaker.com".to_string(),
            ),
            (
                Website::MinistryOfCurryDotCom,
                "ministryofcurry.com".to_string(),
            ),
            (Website::MisyaDotInfo, "www.misya.info".to_string()),
            (
                Website::ModernHoneyDotCom,
                "www.modernhoney.com".to_string(),
            ),
            (
                Website::MomonTimeoutDotCom,
                "www.momontimeout.com".to_string(),
            ),
            (Website::MomsDishDotCom, "momsdish.com".to_string()),
            (
                Website::MomsWithCrockpotsDotCom,
                "momswithcrockpots.com".to_string(),
            ),
            (
                Website::MotherThymeDotCom,
                "www.motherthyme.com".to_string(),
            ),
            (
                Website::MundoDeReceitasBimbyDotComDotPt,
                "www.mundodereceitasbimby.com.pt".to_string(),
            ),
            (
                Website::MyBakingAddictionDotCom,
                "www.mybakingaddiction.com".to_string(),
            ),
            (
                Website::MyJewishLearningDotCom,
                "www.myjewishlearning.com".to_string(),
            ),
            (Website::MyKitchen101DotCom, "mykitchen101.com".to_string()),
            (
                Website::MyKoreanKitchenDotCom,
                "mykoreankitchen.com".to_string(),
            ),
            (
                Website::MyGingerGarlicKitchenDotCom,
                "www.mygingergarlickitchen.com".to_string(),
            ),
            (
                Website::MyKitchen101enDotCom,
                "mykitchen101en.com".to_string(),
            ),
            (Website::MyPlateDotGov, "www.myplate.gov".to_string()),
            (Website::MyRecipesDotCom, "www.myrecipes.com".to_string()),
            (
                Website::NatashasKitchenDotCom,
                "natashaskitchen.com".to_string(),
            ),
            (Website::NigellaDotCom, "www.nigella.com".to_string()),
            (
                Website::NinjaTestKitchenDotEu,
                "ninjatestkitchen.eu".to_string(),
            ),
            (
                Website::NourishedByNutritionDotCom,
                "nourishedbynutrition.com".to_string(),
            ),
            (Website::NosaltyDotHu, "www.nosalty.hu".to_string()),
            (
                Website::NotEnoughCinnamonDotCom,
                "www.notenoughcinnamon.com".to_string(),
            ),
            (Website::NrkDotNo, "www.nrk.no".to_string()),
            (
                Website::Number2PencilDotCom,
                "www.number-2-pencil.com".to_string(),
            ),
            (
                Website::NutritionFactsDotOrg,
                "nutritionfacts.org".to_string(),
            ),
            (Website::NyTimesDotCom, "cooking.nytimes.com".to_string()),
            (Website::OhSheGlowsDotCom, "ohsheglows.com".to_string()),
            (
                Website::OkokoReceptenDotNl,
                "www.okokorecepten.nl".to_string(),
            ),
            (
                Website::OmnivoresCookbookDotCom,
                "omnivorescookbook.com".to_string(),
            ),
            (
                Website::OnceUponaChefDotCom,
                "www.onceuponachef.com".to_string(),
            ),
            (Website::OhMyVeggiesDotCom, "ohmyveggies.com".to_string()),
            (
                Website::OneSweetAppetiteDotCom,
                "onesweetappetite.com".to_string(),
            ),
            (Website::OwenHanDotCom, "www.owen-han.com".to_string()),
            (
                Website::PaleoRunningMommaDotCom,
                "www.paleorunningmomma.com".to_string(),
            ),
            (
                Website::PanelinhaDotComDotBr,
                "www.panelinha.com.br".to_string(),
            ),
            (Website::PaniniHappyDotCom, "paninihappy.com".to_string()),
            (
                Website::ParsleyAndParmDotCom,
                "parsleyandparm.com".to_string(),
            ),
            (
                Website::PersnicketyPlatesDotCom,
                "www.persnicketyplates.com".to_string(),
            ),
            (
                Website::PickupLimesDotCom,
                "www.pickuplimes.com".to_string(),
            ),
            (Website::PinchOfYumDotCom, "pinchofyum.com".to_string()),
            (
                Website::PinkOwlKitchenDotCom,
                "pinkowlkitchen.com".to_string(),
            ),
            (Website::PingoDoceDotPt, "www.pingodoce.pt".to_string()),
            (
                Website::PlatingPixelsDotCom,
                "www.platingpixels.com".to_string(),
            ),
            (Website::PlentyVeganDotCom, "plentyvegan.com".to_string()),
            (Website::PloetzblogDotDe, "www.ploetzblog.de".to_string()),
            (
                Website::PlowingThroughLifeDotCom,
                "plowingthroughlife.com".to_string(),
            ),
            (
                Website::PopSugarDotCoDotUk,
                "www.popsugar.co.uk".to_string(),
            ),
            (Website::PotatoRollsDotGom, "potatorolls.com".to_string()),
            (
                Website::PracticalSelfRelianceDotCom,
                "practicalselfreliance.com".to_string(),
            ),
            (
                Website::PressureLuckCookingDotCom,
                "pressureluckcooking.com".to_string(),
            ),
            (
                Website::PrimalEdgeHealthDotCom,
                "www.primaledgehealth.com".to_string(),
            ),
            (
                Website::ProjectGezondDotNl,
                "www.projectgezond.nl".to_string(),
            ),
            (Website::PrzepisyDotPl, "www.przepisy.pl".to_string()),
            (Website::PurelyPopeDotCom, "purelypope.com".to_string()),
            (Website::PureWowDotCom, "www.purewow.com".to_string()),
            (
                Website::PurpleCarrotDotCom,
                "www.purplecarrot.com".to_string(),
            ),
            (Website::PuurgezondDotNl, "www.puurgezond.nl".to_string()),
            (Website::QuitoqueDotFr, "www.quitoque.fr".to_string()),
            (
                Website::RachlmansFieldDotCom,
                "rachlmansfield.com".to_string(),
            ),
            (Website::RadioFranceDotFr, "www.radiofrance.fr".to_string()),
            (
                Website::RainbowPlantLifeDotCom,
                "rainbowplantlife.com".to_string(),
            ),
            (Website::RealSimpleDotCom, "www.realsimple.com".to_string()),
            (
                Website::ReceitasNestleDotComDotBr,
                "www.receitasnestle.com.br".to_string(),
            ),
            (
                Website::RecettesDotQcDotCa,
                "www.recettes.qc.ca".to_string(),
            ),
            (Website::RecipeGirlDotCom, "www.recipegirl.com".to_string()),
            (Website::RecipeRunnerDotCom, "reciperunner.com".to_string()),
            (
                Website::RecipeTinEatsDotCom,
                "www.recipetineats.com".to_string(),
            ),
            (Website::RedditDotCom, "old.reddit.com".to_string()),
            (
                Website::RedhouseSpiceDotCom,
                "redhousespice.com".to_string(),
            ),
            (Website::ReisHungerDotDe, "www.reishunger.de".to_string()),
            (Website::RezeptWeltDotDe, "www.rezeptwelt.de".to_string()),
            (Website::RicettaDotIt, "ricetta.it".to_string()),
            (
                Website::RicettePerBimbyDotIt,
                "www.ricetteperbimby.it".to_string(),
            ),
            (Website::RobinasBellDotCom, "robinasbell.com".to_string()),
            (
                Website::RosannaPansinoDotCom,
                "rosannapansino.com".to_string(),
            ),
            (Website::RutgerbaktDotNl, "rutgerbakt.nl".to_string()),
            (
                Website::RecipeCommunityDotComDotAu,
                "www.recipecommunity.com.au".to_string(),
            ),
            (
                Website::SaboresaJinomotoDotComDotBr,
                "www.saboresajinomoto.com.br".to_string(),
            ),
            (
                Website::SallysBakingAddictionDotCom,
                "sallysbakingaddiction.com".to_string(),
            ),
            (Website::SallysBlogDotDe, "sallys-blog.de".to_string()),
            (
                Website::SaltAndLavenderDotCom,
                "www.saltandlavender.com".to_string(),
            ),
            (
                Website::SaltPepperSkilletDotCom,
                "saltpepperskillet.com".to_string(),
            ),
            (
                Website::SarahsVeganGuideDotCom,
                "sarahsveganguide.com".to_string(),
            ),
            (Website::SaveurDotCom, "www.saveur.com".to_string()),
            (
                Website::SavoryNothingsDotCom,
                "www.savorynothings.com".to_string(),
            ),
            (
                Website::SeriousEatsDotCom,
                "www.seriouseats.com".to_string(),
            ),
            (
                Website::SimpleVeganistaDotCom,
                "simple-veganista.com".to_string(),
            ),
            (
                Website::SimplyCookitDotCom,
                "www.simply-cookit.com".to_string(),
            ),
            (
                Website::SimplyQuinoaDotCom,
                "www.simplyquinoa.com".to_string(),
            ),
            (
                Website::SimplyRecipesDotCom,
                "www.simplyrecipes.com".to_string(),
            ),
            (
                Website::SimplyWhiskedDotCom,
                "www.simplywhisked.com".to_string(),
            ),
            (
                Website::SkinnyTasteDotCom,
                "www.skinnytaste.com".to_string(),
            ),
            (
                Website::SmittenKitchenDotCom,
                "smittenkitchen.com".to_string(),
            ),
            (Website::SoborsDotHu, "sobors.hu".to_string()),
            (
                Website::SouthernCastIronDotCom,
                "southerncastiron.com".to_string(),
            ),
            (
                Website::SouthernLivingDotCom,
                "www.southernliving.com".to_string(),
            ),
            (
                Website::SpendWithPenniesDotCom,
                "www.spendwithpennies.com".to_string(),
            ),
            (
                Website::SpiceboxTravelsDotCom,
                "spiceboxtravels.com".to_string(),
            ),
            (
                Website::StaySnatchedDotCom,
                "www.staysnatched.com".to_string(),
            ),
            (
                Website::SteamyKitchenDotCom,
                "steamykitchen.com".to_string(),
            ),
            (Website::StreetKitchenDotCo, "streetkitchen.co".to_string()),
            (
                Website::StrongrFastrDotCom,
                "www.strongrfastr.com".to_string(),
            ),
            (Website::SunBasketDotCom, "sunbasket.com".to_string()),
            (Website::SundPaabudgetDotdk, "sundpaabudget.dk".to_string()),
            (Website::SunsetDotCom, "www.sunset.com".to_string()),
            (
                Website::SweetcsDesignsDotCom,
                "sweetcsdesigns.com".to_string(),
            ),
            (
                Website::SweetPeasAnSsaffronDotCom,
                "sweetpeasandsaffron.com".to_string(),
            ),
            (Website::TasteAtlasDotCom, "www.tasteatlas.com".to_string()),
            (
                Website::TasteOfHomeDotCom,
                "www.tasteofhome.com".to_string(),
            ),
            (
                Website::TastesBetterFromScratchDotCom,
                "tastesbetterfromscratch.com".to_string(),
            ),
            (
                Website::TastesOfLizzytDotCom,
                "www.tastesoflizzyt.com".to_string(),
            ),
            (Website::TastyDotCo, "tasty.co".to_string()),
            (Website::TastyKitchenDotCom, "tastykitchen.com".to_string()),
            (Website::TescoDotCom, "realfood.tesco.com".to_string()),
            (
                Website::ThatVeganDadDotNet,
                "www.thatvegandad.net".to_string(),
            ),
            (
                Website::TheCleverCarrotDotCom,
                "www.theclevercarrot.com".to_string(),
            ),
            (
                Website::TheCookieRookieDotCom,
                "www.thecookierookie.com".to_string(),
            ),
            (
                Website::TheCookingGuyDotCom,
                "www.thecookingguy.com".to_string(),
            ),
            (
                Website::TheExpertGuidesDotCom,
                "theexpertguides.com".to_string(),
            ),
            (
                Website::TheFoodFlamingoDotCom,
                "thefoodflamingo.com".to_string(),
            ),
            (Website::TheGucchaDotCom, "www.theguccha.com".to_string()),
            (
                Website::TheHappyFoodieDotCoDotUk,
                "thehappyfoodie.co.uk".to_string(),
            ),
            (
                Website::TheHeartySoulDotCom,
                "theheartysoul.com".to_string(),
            ),
            (
                Website::TheKitchenCommunityDotOrg,
                "thekitchencommunity.org".to_string(),
            ),
            (
                Website::TheKitchenMagPieDotCom,
                "www.thekitchenmagpie.com".to_string(),
            ),
            (Website::TheKitchnDotCom, "www.thekitchn.com".to_string()),
            (
                Website::TheMagicalSlowCookerDotCom,
                "www.themagicalslowcooker.com".to_string(),
            ),
            (
                Website::TheNutritiousKitchenDotCo,
                "thenutritiouskitchen.co".to_string(),
            ),
            (
                Website::TheModernProperDotCom,
                "themodernproper.com".to_string(),
            ),
            (
                Website::ThePalatableLifeDotCom,
                "www.thepalatablelife.com".to_string(),
            ),
            (
                Website::ThePioneerWomanDotCom,
                "www.thepioneerwoman.com".to_string(),
            ),
            (
                Website::TheRecipeCriticDotCom,
                "therecipecritic.com".to_string(),
            ),
            (
                Website::TheSaltyMarshmallowDotCom,
                "thesaltymarshmallow.com".to_string(),
            ),
            (
                Website::TheSpruceEatsDotCom,
                "www.thespruceeats.com".to_string(),
            ),
            (
                Website::TheVintageMixerDotCom,
                "www.thevintagemixer.com".to_string(),
            ),
            (
                Website::TheWoksOfLifeDotCom,
                "thewoksoflife.com".to_string(),
            ),
            (Website::ThinliciousDotCom, "thinlicious.com".to_string()),
            (Website::TidyMomDotNet, "tidymom.net".to_string()),
            (
                Website::TimesOfIndiaDotCom,
                "recipes.timesofindia.com".to_string(),
            ),
            (Website::TineDotNo, "www.tine.no".to_string()),
            (
                Website::TudogostosoDotComDotBr,
                "www.tudogostoso.com.br".to_string(),
            ),
            (
                Website::TwoPeasAndTheirPodDotCom,
                "www.twopeasandtheirpod.com".to_string(),
            ),
            (Website::TwoSleeversDotCom, "twosleevers.com".to_string()),
            (
                Website::UitPaulinesKeukenDotNl,
                "uitpaulineskeuken.nl".to_string(),
            ),
            (
                Website::UnsophistiCookDotCom,
                "unsophisticook.com".to_string(),
            ),
            (Website::UsaPearsDotOrg, "usapears.org".to_string()),
            (Website::ValdemarsroDotdk, "www.valdemarsro.dk".to_string()),
            (
                Website::VanillaAndBeanDotCom,
                "vanillaandbean.com".to_string(),
            ),
            (Website::VeganPratiqueDotFr, "vegan-pratique.fr".to_string()),
            (
                Website::VegetarBloggenDotNo,
                "www.vegetarbloggen.no".to_string(),
            ),
            (Website::VegolosiDotIt, "www.vegolosi.it".to_string()),
            (
                Website::VegRecipesOfIndiaDotCom,
                "www.vegrecipesofindia.com".to_string(),
            ),
            (Website::WaitRoseDotCom, "www.waitrose.com".to_string()),
            (
                Website::WatchWhatUEatDotCom,
                "www.watchwhatueat.com".to_string(),
            ),
            (
                Website::WearenotMarthaDotCom,
                "wearenotmartha.com".to_string(),
            ),
            (
                Website::WeightWatchersDotCom,
                "www.weightwatchers.com".to_string(),
            ),
            (Website::WellPlatedDotCom, "www.wellplated.com".to_string()),
            (
                Website::WhatsGabyCookingDotCom,
                "whatsgabycooking.com".to_string(),
            ),
            (
                Website::WholeFoodsMarketDotCoDotUk,
                "www.wholefoodsmarket.co.uk".to_string(),
            ),
            (Website::WikibooksDotOrg, "en.wikibooks.org".to_string()),
            (
                Website::WikibooksDotOrgMobile,
                "en.m.wikibooks.org".to_string(),
            ),
            (
                Website::WomensWeeklyFoodDotComDotAu,
                "www.womensweeklyfood.com.au".to_string(),
            ),
            (Website::WoopDotCoDotNz, "woop.co.nz".to_string()),
            (Website::YeMekDotNet, "ye-mek.net".to_string()),
            (Website::YumeliseDotFr, "www.yumelise.fr".to_string()),
            (Website::ZeitDotDe, "www.zeit.de".to_string()),
            (Website::ZenbellyDotCom, "www.zenbelly.com".to_string()),
        ])
    })
}

fn websites_map_to_website() -> &'static HashMap<String, Website> {
    static INSTANCE: OnceLock<HashMap<String, Website>> = OnceLock::new();

    INSTANCE.get_or_init(|| {
        let mut map: HashMap<String, Website> = HashMap::new();
        websites_map_to_domain()
            .iter()
            .for_each(|(&website, domain)| {
                let _ = map.insert(domain.clone(), website);
            });
        map
    })
}
