---
--- Main tables
---
CREATE TABLE cookbooks (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    image uuid,
    count int DEFAULT 0,
    user_id uuid REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (title, user_id)
);

---
--- Association tables
---
CREATE TABLE cookbooks_recipes (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cookbook_id int8 REFERENCES cookbooks (id) ON DELETE CASCADE,
    recipe_id int8 REFERENCES recipes (id) ON DELETE CASCADE,
    order_index int2 NOT NULL,
    UNIQUE (cookbook_id, recipe_id)
);

CREATE TABLE shares_cookbooks (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link text NOT NULL,
    user_id uuid REFERENCES users (id) ON DELETE CASCADE,
    cookbook_id int8 REFERENCES cookbooks (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (link, cookbook_id)
);

---
--- Functions
---
CREATE FUNCTION increment_cookbooks_count_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    UPDATE
        cookbooks
    SET
        count = count + 1
    WHERE
        NEW.cookbook_id = id;
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;

CREATE FUNCTION increment_counts_cookbook_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    UPDATE
        counts
    SET
        cookbooks = cookbooks + 1
    WHERE
        user_id = NEW.user_id;
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;

CREATE FUNCTION decrement_counts_cookbook_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    UPDATE
        counts
    SET
        cookbooks = cookbooks - 1
    WHERE
        user_id = OLD.user_id;
    --     DELETE
    --     FROM cookbooks_fts
    --     WHERE id = OLD.id
    --       AND user_id = OLD.user_id;
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;

CREATE FUNCTION decrement_cookbooks_count_column ()
    RETURNS TRIGGER
    AS $$
BEGIN
    UPDATE
        cookbooks
    SET
        count = count - 1
    WHERE
        OLD.cookbook_id = id;
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;

---
--- Triggers
---
CREATE TRIGGER increment_cookbook_count
    AFTER INSERT ON cookbooks_recipes
    FOR EACH ROW
    EXECUTE FUNCTION increment_cookbooks_count_column ();

CREATE TRIGGER increment_counts_cookbook
    AFTER INSERT ON cookbooks
    FOR EACH ROW
    EXECUTE FUNCTION increment_counts_cookbook_column ();

CREATE TRIGGER decrement_counts_cookbook
    AFTER DELETE ON cookbooks
    FOR EACH ROW
    EXECUTE FUNCTION decrement_counts_cookbook_column ();

CREATE TRIGGER decrement_cookbook_count
    AFTER DELETE ON cookbooks_recipes
    FOR EACH ROW
    EXECUTE FUNCTION decrement_cookbooks_count_column ();

