[package]
name = "schema-org"
version = "0.0.0"
description = "Rust representations of Schema.org recipe-related types generated using schemy."

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
json-schema = ["dep:schemars"]
default = []

[dependencies]
iso8601.workspace = true
schemars = { version = "1.1.0", optional = true }
serde.workspace = true
serde_json.workspace = true
