[package]
name = "recipe-schema"
version = "0.1.0"
publish = true
description = "Rust representations of Schema.org recipe-related types."

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
iso8601.workspace = true
reqwest.workspace = true
schemars = "1.0.4"
serde.workspace = true
serde_json.workspace = true
support.workspace = true
tracing.workspace = true
url.workspace = true
