[package]
name = "math"
version = "0.0.0"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
measurements = {  version = "0.11", features = ["std"] }
regex = { workspace = true }
strum = { workspace = true }
