name: Nightly

#on:
#  schedule:
#    - cron: "0 0 * * *"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    outputs:
      numCommits: ${{ steps.numCommits.outputs.commits }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get new commits
        id: numCommits
        run: echo "commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"

  binaries:
    timeout-minutes: 60
    needs: commits
    runs-on: ${{ matrix.os }}
    if: ${{ needs.commits.outputs.numCommits > 0 }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: recipya-nightly-x86_64-unknown-linux-musl

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: recipya-nightly-x86_64-unknown-linux-gnu

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: recipya-nightly-aarch64-unknown-linux-gnu

          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            artifact: recipya-nightly-armv7-unknown-linux-gnueabihf

          #- os: macos-latest
          #  target: x86_64-apple-darwin
          #  artifact: recipya-nightly-x86_64-apple-darwin

          #- os: macos-latest
          #  target: aarch64-apple-darwin
          #  artifact: recipya-nightly-aarch64-apple-darwin

          #- os: windows-latest
          #  target: x86_64-pc-windows-msvc
          #  artifact: recipya-nightly-x86_64-pc-windows-msvc.exe

          #- os: windows-latest
          #  target: x86_64-pc-windows-gnu
          #  artifact: recipya-nightly-x86_64-pc-windows-gnu.exe
          
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Archive
        shell: bash
        run: |         
          mkdir -p staging-directory
          cross build --target ${{ matrix.target }} --release

          BINARY_NAME="recipya-rs"
          OUTPUT_PATH="staging-directory/${{ matrix.artifact }}"

          cp "target/${{ matrix.target }}/release/${BINARY_NAME}" "${OUTPUT_PATH}"
          cp ./deploy/.env.example $OUTPUT_PATH/.env
          
          if [ "${{ runner.os }}" = "Windows" ]; then
            sha256sum "${OUTPUT_PATH}" > "${OUTPUT_PATH}.sha256"
          else
            shasum -a 256 "${OUTPUT_PATH}" | awk '{ print $1 }' > "${OUTPUT_PATH}.sha256"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: staging-directory
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: binaries

    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: nightly
          prerelease: false
          title: "Nightly Build"
          files: |
            downloads/**/recipya-nightly-*
            downloads/**/recipya-nightly-*.sha256
            downloads/**/.env
            LICENSE
  
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    needs: release
    
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            ARCH=${{ matrix.platform == 'linux/amd64' && 'x86_64' || 'arm64' }}
          tags: |
            reaper99/recipya-rs:latest 
            ghcr.io/${{ github.repository_owner }}/recipya-rs:latest
