name: Nightly

#on:
#  schedule:
#    - cron: "0 0 * * *"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    outputs:
      numCommits: ${{ steps.numCommits.outputs.commits }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get new commits
        id: numCommits
        run: echo "commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"

  binaries:
    timeout-minutes: 60
    needs: commits
    runs-on: ${{ matrix.os }}
    #if: ${{ needs.commits.outputs.numCommits > 0 }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - build: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: recipya-nightly-x86_64-unknown-linux-musl

          - build: linux-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: recipya-nightly-x86_64-unknown-linux-gnu

          - build: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: recipya-nightly-aarch64-unknown-linux-gnu

          #- build: linux
          #  os: ubuntu-latest
          #  target: armv7-unknown-linux-gnueabihf
          #  artifact: recipya-nightly-armv7-unknown-linux-gnueabihf

          - build: macos-x86
            os: macos-latest
            target: x86_64-apple-darwin
            artifact: recipya-nightly-x86_64-apple-darwin

          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
            artifact: recipya-nightly-aarch64-apple-darwin

          - build: windows-mvsc
            os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: recipya-nightly-x86_64-pc-windows-msvc.exe

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            artifact: recipya-nightly-x86_64-pc-windows-gnu.exe
            msys2_packages: >-
              make
              mingw-w64-x86_64-toolchain
              mingw-w64-x86_64-cmake
              mingw-w64-x86_64-nasm # Install NASM from MinGW repository

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        if: matrix.target == 'x86_64-pc-windows-gnu'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: ${{ matrix.msys2_packages }}
          pacman-update: true
          update: true
          path-type: inherit

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - if: ${{ runner.os == 'Linux' }}
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: |
            musl-tools 
            libsqlite3-dev 
            gcc-13 
            gcc-13-aarch64-linux-gnu 
            gcc-aarch64-linux-gnu 
            aarch64-linux-gnu-gcc
            gcc-arm-linux-gnueabihf
            gcc-mingw-w64-x86-64-win32
          version: 1.0
      
      - name: Set up libpq for ${{ matrix.target }}
        if: runner.os == 'macOS'
        run: |
          brew install libpq
          if [ "${{ matrix.target }}" = "x86_64-apple-darwin" ]; then
            echo "LIBRARY_PATH=/usr/local/opt/libpq/lib" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/local/opt/libpq/lib/pkgconfig" >> $GITHUB_ENV
            echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
          else
            echo "LIBRARY_PATH=/opt/homebrew/opt/libpq/lib" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/opt/homebrew/opt/libpq/lib/pkgconfig" >> $GITHUB_ENV
          fi


          #if [ "${{ matrix.target }}" = "x86_64-apple-darwin" ]; then
          #  arch -x86_64 /usr/local/Homebrew/bin/brew install libpq
          #  echo "LIBRARY_PATH=/usr/local/opt/libpq/lib" >> $GITHUB_ENV
          #  echo "PKG_CONFIG_PATH=/usr/local/opt/libpq/lib/pkgconfig" >> $GITHUB_ENV
          #  echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
          #else
          #  echo "LIBRARY_PATH=$(brew --prefix libpq)/lib" >> $GITHUB_ENV
          #  echo "C_INCLUDE_PATH=$(brew --prefix libpq)/include" >> $GITHUB_ENV
          #  echo "PKG_CONFIG_PATH=$(brew --prefix libpq)/lib/pkgconfig" >> $GITHUB_ENV
          #  echo "PATH=$(brew --prefix libpq)/bin:$PATH" >> $GITHUB_ENV
          #fi

      - name: Install Rustup targets
        run: rustup target add ${{ matrix.target }}

      - name: Determine Shell for Build
        id: determine_shell
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" && "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]; then
            echo "SELECTED_SHELL=msys2 {0}" >> $GITHUB_OUTPUT
          else
            echo "SELECTED_SHELL=bash" >> $GITHUB_OUTPUT
          fi

      - name: Build Archive
        shell: ${{ steps.determine_shell.outputs.SELECTED_SHELL }}
        run: |
          echo "Using shell: $SHELL" # For verifying which shell is active
          echo "Building for target: ${{ matrix.target }} on OS: ${{ matrix.os }}"
          
          OUTPUT_PATH=staging-directory
          mkdir -p $OUTPUT_PATH
          
          cargo build --target ${{ matrix.target }} --release
          
          BINARY_NAME="recipya-rs"
          if [ "${{ runner.os }}" = "Windows" ]; then
            BINARY_NAME="recipya-rs.exe"
          fi
          
          cp target/${{ matrix.target }}/release/$BINARY_NAME $OUTPUT_PATH/${{ matrix.artifact }}
          cp ./deploy/.env.example $OUTPUT_PATH/.env
          
          if [ "${{ runner.os }}" = "Windows" ]; then
            if [[ "$SHELL" == *"msys2"* ]]; then # Check if we are in msys2 shell
              sha256sum $OUTPUT_PATH/${{ matrix.artifact }} > $OUTPUT_PATH/${{ matrix.artifact }}.sha256
            else
              certutil -hashfile "$OUTPUT_PATH/${{ matrix.artifact }}" SHA256 | findstr /v "hash" > "$OUTPUT_PATH/${{ matrix.artifact }}.sha256.tmp"
              powershell -Command "(Get-Content '$OUTPUT_PATH/${{ matrix.artifact }}.sha256.tmp').Trim() -replace ' ', '' | Set-Content '$OUTPUT_PATH/${{ matrix.artifact }}.sha256'"
              del "$OUTPUT_PATH/${{ matrix.artifact }}.sha256.tmp"
            fi
          else
            GENERATED_SHA_256=$(shasum -a 256 $OUTPUT_PATH/${{ matrix.artifact }} | awk '{print $1}')
            echo $GENERATED_SHA_256 > $OUTPUT_PATH/${{ matrix.artifact }}.sha256
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: staging-directory
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: binaries

    steps:
      - uses: actions/checkout@v4

      - name: Download Nightly Build x86_64-unknown-linux-musl
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-x86_64-unknown-linux-musl
          path: downloads

      - name: Download Nightly Build x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-x86_64-unknown-linux-gnu
          path: downloads

      - name: Download Nightly Build aarch64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-aarch64-unknown-linux-gnu
          path: downloads

      #- name: Download Nightly Build armv7-unknown-linux-gnueabihf
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: recipya-nightly-armv7-unknown-linux-gnueabihf
      #    path: downloads

      - name: Download Nightly Build x86_64-apple-darwin
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-x86_64-apple-darwin
          path: downloads

      - name: Download Nightly Build aarch64-apple-darwin
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-aarch64-apple-darwin
          path: downloads

      - name: Download Nightly Build x86_64-pc-windows-msvc
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-x86_64-pc-windows-msvc.exe
          path: downloads

      - name: Download Nightly Build x86_64-pc-windows-gnu
        uses: actions/download-artifact@v4
        with:
          name: recipya-nightly-x86_64-pc-windows-gnu.exe
          path: downloads

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          automatic_release_tag: nightly
          prerelease: false
          title: "Nightly Build"
          # downloads/recipya-nightly-armv7-unknown-linux-gnueabihf
          # downloads/recipya-nightly-armv7-unknown-linux-gnueabihf.sha256
          files: |
            downloads/recipya-nightly-x86_64-unknown-linux-musl
            downloads/recipya-nightly-x86_64-unknown-linux-musl.sha256
            downloads/recipya-nightly-x86_64-unknown-linux-gnu
            downloads/recipya-nightly-x86_64-unknown-linux-gnu.sha256
            downloads/recipya-nightly-aarch64-unknown-linux-gnu
            downloads/recipya-nightly-aarch64-unknown-linux-gnu.sha256
            downloads/recipya-nightly-x86_64-apple-darwin
            downloads/recipya-nightly-x86_64-apple-darwin.sha256
            downloads/recipya-nightly-aarch64-apple-darwin
            downloads/recipya-nightly-aarch64-apple-darwin.sha256
            downloads/recipya-nightly-x86_64-pc-windows-msvc.exe
            downloads/recipya-nightly-x86_64-pc-windows-msvc.exe.sha256
            downloads/recipya-nightly-x86_64-pc-windows-gnu.exe
            downloads/recipya-nightly-x86_64-pc-windows-gnu.exe.sha256
            downloads/.env
            LICENSE
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    needs: release
    
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            ARCH=${{ matrix.platform == 'linux/amd64' && 'x86_64' || 'arm64' }}
          tags: |
            reaper99/recipya-rs:latest 
            ghcr.io/${{ github.repository_owner }}/recipya-rs:latest
