name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: stable

      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: postgres
          password: postgres
          database: recipya
          port: 5432
          postgres-version: "17"
          ssl: "false"
        id: postgres

      - run: |
            psql -U postgres -c "CREATE DATABASE recipya;"
            psql -U postgres -c "CREATE DATABASE recipya_test;"

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Test
        run: cargo test
