name: Rust
permissions:
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.0
          components: clippy

      - uses: mozilla-actions/sccache-action@v0.0.10

      - name: Cache cargo registry & bins
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - uses: taiki-e/install-action@nextest

      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: postgres
          password: postgres
          database: recipya_test
          port: 5432
          postgres-version: "17"
          ssl: "false"
        id: postgres

      - name: Install diesel_cli
        run: |
          command -v diesel || \
          cargo install diesel_cli --no-default-features --features postgres

      - run: diesel migration run
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Clippy (all targets)
        run: cargo clippy --all-targets -- -D warnings

      - name: Build tests
        run: cargo nextest run --no-run --locked
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
          APP_ENV: "test"

      - name: Test dev build
        uses: nick-fields/retry@v2
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
          RECIPYA_BASE_URL: "http://localhost:8078"
          RECIPYA_IS_AUTOLOGIN: "false"
          RECIPYA_IS_DEMO: "false"
          RECIPYA_IS_ALLOW_SIGNUPS: "false"
          SMTP_FROM_EMAIL: "example@gmail.com"
          SMTP_HOST: "smtp.gmail.com"
          SMTP_USERNAME: "example@gmail.com"
          SMTP_PASSWORD: "abcd abcd bcd abcd"
          APP_ENV: "test"
        with:
          timeout_minutes: 30
          max_attempts: 3
          # command: cargo nextest run --locked
          command: cargo nextest run --success-output immediate --failure-output immediate

      - name: Test release build every 10 runs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: nick-fields/retry@v2
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
          RECIPYA_BASE_URL: "http://localhost:8078"
          RECIPYA_IS_AUTOLOGIN: "false"
          RECIPYA_IS_DEMO: "false"
          RECIPYA_IS_ALLOW_SIGNUPS: "false"
          SMTP_FROM_EMAIL: "example@gmail.com"
          SMTP_HOST: "smtp.gmail.com"
          SMTP_USERNAME: "example@gmail.com"
          SMTP_PASSWORD: "abcd abcd bcd abcd"
          APP_ENV: "test"
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cargo nextest run --release --locked

      - name: sccache stats
        run: ${SCCACHE_PATH} --show-stats
